# tool: scribe-data
# All Hebrew (Q9288) verbs.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)  # Extracts the lexeme ID from the URL
  ?infinitive
  ?pastFPS ?pastSPS ?pastTPS
  ?pastFPP ?pastSPP ?pastTPP
  ?presMasculine ?presFeminine ?presPlural

WHERE {
  ?lexeme dct:language wd:he ;  # Filters for Hebrew verbs
         wikibase:lexicalCategory wd:Q24905 .  # Specifies the lexical category for verbs

  # Infinitive (required)
  ?lexeme ontolex:lexicalForm ?infinitiveForm .
  ?infinitiveForm ontolex:representation ?infinitive ;
          wikibase:grammaticalFeature wd:Q179230 .  # Infinitive grammatical feature

  # Past Tense Conjugations (optional)
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPSForm .
    ?pastFPSForm ontolex:representation ?pastFPS ;
        wikibase:grammaticalFeature wd:Q21714344 ;  # 1st person singular past
        wikibase:grammaticalFeature wd:Q110786 ;  # Past tense
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
        wikibase:grammaticalFeature wd:Q1994301 ;  # Masculine gender
  } .
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSForm .
    ?pastSPSForm ontolex:representation ?pastSPS ;
        wikibase:grammaticalFeature wd:Q51929049 ;  # 3rd person singular past
        wikibase:grammaticalFeature wd:Q110786 ;  # Past tense
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
        wikibase:grammaticalFeature wd:Q499327 ;  # Masculine gender
  } .
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSForm .
    ?pastTPSForm ontolex:representation ?pastTPS ;
        wikibase:grammaticalFeature wd:Q51929074 ;  # 3rd person plural past
        wikibase:grammaticalFeature wd:Q110786 ;  # Past tense
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
  } .
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPPForm .
    ?pastFPPForm ontolex:representation ?pastFPP ;
        wikibase:grammaticalFeature wd:Q21714344 ;  # 1st person singular past
        wikibase:grammaticalFeature wd:Q146786 ;  # Feminine gender
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
  } .
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPForm .
    ?pastSPPForm ontolex:representation ?pastSPP ;
        wikibase:grammaticalFeature wd:Q51929049 ;  # 3rd person singular past
        wikibase:grammaticalFeature wd:Q146786 ;  # Feminine gender
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
  } .
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPForm .
    ?pastTPPForm ontolex:representation ?pastTPP ;
        wikibase:grammaticalFeature wd:Q51929074 ;  # 3rd person plural past
        wikibase:grammaticalFeature wd:Q146786 ;  # Feminine gender
        wikibase:grammaticalFeature wd:Q682111 ;  # Singular number
  } .
}