# tool: scribe-data
# All Hebrew (Q9288) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pastFPS
  ?pastSPSF
  ?pastSPSM
  ?pastTPSF
  ?pastTPSM
  ?pastFPP
  ?pastSPPF
  ?pastSPPM
  ?pastTPPF
  ?pastTPPM

WHERE {
  ?lexeme dct:language wd:Q9288 ;
    wikibase:lexicalCategory wd:Q24905 .

  # MARK: Past

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPForm .
    ?pastTPPForm ontolex:representation ?pastTPP ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786, wd:Q1994301 .
      FILTER(lang(?pastTPP) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSFForm .
    ?pastSPSFForm ontolex:representation ?pastSPSF ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q1994301, wd:Q1775415 .
      FILTER(lang(?pastSPSF) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSMForm .
    ?pastSPSMForm ontolex:representation ?pastSPSM ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q1994301, wd:Q499327 .
      FILTER(lang(?pastSPSM) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSFForm .
    ?pastTPSFForm ontolex:representation ?pastTPSF ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, wd:Q1994301, wd:Q1775415 .
      FILTER(lang(?pastTPSF) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSMForm .
    ?pastTPSMForm ontolex:representation ?pastTPSM ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, wd:Q1994301, wd:Q499327 .
      FILTER(lang(?pastTPSM) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPPForm .
    ?pastFPPForm ontolex:representation ?pastFPP ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q1994301 .
      FILTER(lang(?pastFPP) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPFForm .
    ?pastSPPFForm ontolex:representation ?pastSPPF ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q1994301, wd:Q1775415 .
      FILTER(lang(?pastSPPF) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPMForm .
    ?pastSPPMForm ontolex:representation ?pastSPPM ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q1994301, wd:Q499327 .
      FILTER(lang(?pastSPPM) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPFForm .
    ?pastTPPFForm ontolex:representation ?pastTPPF ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786, wd:Q1994301, wd:Q1775415 .
      FILTER(lang(?pastTPPF) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPMForm .
    ?pastTPPMForm ontolex:representation ?pastTPPM ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786, wd:Q1994301, wd:Q499327 .
      FILTER(lang(?pastTPPM) = "he") .
  }
}
