# tool: scribe-data
# All Hebrew (Q9288) verbs.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb

WHERE {
  ?lexeme dct:language wd:Q9288 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  BIND(lang(?verb) as ?language)
  FILTER(?language = "he")
}
