# tool: scribe-data
# All Hebrew (Q9288) verbs and the currently implemented tenses for each.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pastFPS ?pastSPSF ?pastSPSM ?pastTPSF ?pastTPSM
  ?pastFPP ?pastSPPF ?pastSPPM ?pastTPPF ?pastTPPM

WHERE {
  ?lexeme dct:language wd:Q9288 ;
    wikibase:lexicalCategory wd:Q24905 .

  # MARK: Past

  # FPS
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPForm .
    ?pastTPPForm ontolex:representation ?pastTPP ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      FILTER(lang(?pastTPP) = "he")
  } .

  # SPS Feminine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSFForm .
    ?pastSPSFForm ontolex:representation ?pastSPSF ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      FILTER(lang(?pastSPSF) = "he")
  } .

  # SPS Masculine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSMForm .
    ?pastSPSMForm ontolex:representation ?pastSPSM ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      FILTER(lang(?pastSPSM) = "he")
  } .

  # TPS Feminine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSFForm .
    ?pastTPSFForm ontolex:representation ?pastTPSF ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      FILTER(lang(?pastTPSF) = "he")
  } .

  # TPS Masculine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSMForm .
    ?pastTPSMForm ontolex:representation ?pastTPSM ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      FILTER(lang(?pastTPSM) = "he")
  } .

  # FPP
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPPForm .
    ?pastFPPForm ontolex:representation ?pastFPP ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      FILTER(lang(?pastFPP) = "he")
  } .

  # SPP Feminine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPFForm .
    ?pastSPPFForm ontolex:representation ?pastSPPF ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      FILTER(lang(?pastSPPF) = "he")
  } .

  # SPP Masculine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPMForm .
    ?pastSPPMForm ontolex:representation ?pastSPPM ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      FILTER(lang(?pastSPPM) = "he")
  } .

  # TPP Feminine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPFForm .
    ?pastTPPFForm ontolex:representation ?pastTPPF ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      FILTER(lang(?pastTPPF) = "he")
  } .

  # TPP Masculine
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPPMForm .
    ?pastTPPMForm ontolex:representation ?pastTPPM ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1994301 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      FILTER(lang(?pastTPPM) = "he")
  } .
}
