# tool: scribe-data
# All Nigerian Pidgin (Q33655) adverbs.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adverb

WHERE {
  ?lexeme dct:language wd:Q33655;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb .
}
