# tool: scribe-data
# All German (Q188) prepositions (Q4833830) and the given forms.
# Enter this query at https://query.wikidata.org/.

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?preposition
  ?grammaticalCase

WHERE {
  ?lexeme dct:language wd:Q188;
    wikibase:lexicalCategory wd:Q4833830;
    wikibase:lemma ?preposition;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme wdt:P5713 ?caseForm.
  }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
    ?lemma rdfs:label ?preposition.
    ?caseForm rdfs:label ?grammaticalCase.
  }
}
