# tool: scribe-data
# All Polish (Q809) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?singularGenitive
  ?singularDative
  ?singularAccusative

WHERE {
  ?lexeme dct:language wd:Q809 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeForm .
    ?singularDativeForm ontolex:representation ?singularDative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeForm .
    ?singularAccusativeForm ontolex:representation ?singularAccusative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078 .
  }
}
