# tool: scribe-data
# All polish (Q809) personal_pronouns (Q468801) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?personal_pronouns
    ?singularGenitive
  ?singularNominative
  ?singularInstrumental
  ?singularAccusative
  ?singularLocative
  ?singularDative
  ?genitive
  ?nominative
  ?instrumental
  ?accusative
  ?locative
  ?dative
  ?vocative
    WHERE {
    ?lexeme dct:language wd:Q809 ;
        wikibase:lexicalCategory wd:Q468801 ;
        wikibase:lemma ?personal_pronouns .
        FILTER(lang(?personal_pronouns) = "pl")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
            ?singularGenitiveForm ontolex:representation ?singularGenitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNominativeForm .
            ?singularNominativeForm ontolex:representation ?singularNominative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularInstrumentalForm .
            ?singularInstrumentalForm ontolex:representation ?singularInstrumental ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q192997 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAccusativeForm .
            ?singularAccusativeForm ontolex:representation ?singularAccusative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146078 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularLocativeForm .
            ?singularLocativeForm ontolex:representation ?singularLocative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q202142 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularDativeForm .
            ?singularDativeForm ontolex:representation ?singularDative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?instrumentalForm .
            ?instrumentalForm ontolex:representation ?instrumental ;
                wikibase:grammaticalFeature wd:Q192997 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeForm .
            ?accusativeForm ontolex:representation ?accusative ;
                wikibase:grammaticalFeature wd:Q146078 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?locativeForm .
            ?locativeForm ontolex:representation ?locative ;
                wikibase:grammaticalFeature wd:Q202142 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dativeForm .
            ?dativeForm ontolex:representation ?dative ;
                wikibase:grammaticalFeature wd:Q145599 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?vocativeForm .
            ?vocativeForm ontolex:representation ?vocative ;
                wikibase:grammaticalFeature wd:Q185077 .
        }
}