# tool: scribe-data
# All Esperanto (Q143) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?volitive
  ?conditional
  ?infinitive
  ?presentIndicative
  ?indicativePast
  ?futureIndicative

WHERE {
  ?lexeme dct:language wd:Q143 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?volitiveForm .
    ?volitiveForm ontolex:representation ?volitive ;
      wikibase:grammaticalFeature wd:Q2532941 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalForm .
    ?conditionalForm ontolex:representation ?conditional ;
      wikibase:grammaticalFeature wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveForm .
    ?infinitiveForm ontolex:representation ?infinitive ;
      wikibase:grammaticalFeature wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentIndicativeForm .
    ?presentIndicativeForm ontolex:representation ?presentIndicative ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativePastForm .
    ?indicativePastForm ontolex:representation ?indicativePast ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureIndicativeForm .
    ?futureIndicativeForm ontolex:representation ?futureIndicative ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q682111 .
  }
}
