# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?vocativeMasculineInanimateSingular
  ?vocativeMasculineInanimatePlural
  ?vocativeMasculineInanimateSingularSuperlative
  ?vocativeMasculineInanimateSingularPositive
  ?vocativeMasculineInanimatePluralSuperlative
  ?vocativeMasculineInanimatePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularForm .
    ?vocativeMasculineInanimateSingularForm ontolex:representation ?vocativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralForm .
    ?vocativeMasculineInanimatePluralForm ontolex:representation ?vocativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularSuperlativeForm .
    ?vocativeMasculineInanimateSingularSuperlativeForm ontolex:representation ?vocativeMasculineInanimateSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularPositiveForm .
    ?vocativeMasculineInanimateSingularPositiveForm ontolex:representation ?vocativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralSuperlativeForm .
    ?vocativeMasculineInanimatePluralSuperlativeForm ontolex:representation ?vocativeMasculineInanimatePluralSuperlative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralPositiveForm .
    ?vocativeMasculineInanimatePluralPositiveForm ontolex:representation ?vocativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }
}
