# tool: scribe-data
# All malayalam (Q36236) adjectives (Q34698) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjectives
    ?nominativePlural
  ?singularInstrumental
  ?pluralLocative
  ?dativePlural
  ?genitivePlural
  ?singularGenitive
  ?singularLocative
  ?pluralInstrumental
  ?singularDative
  ?singularNominative
  ?accusativePlural
  ?singularAccusative

WHERE {
  ?lexeme dct:language wd:Q36236 ;
  wikibase:lexicalCategory wd:Q34698 ;
  wikibase:lemma ?adjectives .
  FILTER(lang(?adjectives) = "ml")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm .
    ?nominativePluralForm ontolex:representation ?nominativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInstrumentalForm .
    ?singularInstrumentalForm ontolex:representation ?singularInstrumental ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralLocativeForm .
    ?pluralLocativeForm ontolex:representation ?pluralLocative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeForm .
    ?singularLocativeForm ontolex:representation ?singularLocative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralInstrumentalForm .
    ?pluralInstrumentalForm ontolex:representation ?pluralInstrumental ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeForm .
    ?singularDativeForm ontolex:representation ?singularDative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralForm .
    ?accusativePluralForm ontolex:representation ?accusativePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeForm .
    ?singularAccusativeForm ontolex:representation ?singularAccusative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078 .
  }
}
