# tool: scribe-data
# All Polish (Q809) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineAnimateSingularPassiveParticiple
  ?masculineAnimateSingularActiveParticiple
  ?masculineAnimatePluralPassiveParticiple
  ?masculineAnimatePluralActiveParticiple

WHERE {
  ?lexeme dct:language wd:Q809 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimateSingularPassiveParticipleForm .
    ?masculineAnimateSingularPassiveParticipleForm ontolex:representation ?masculineAnimateSingularPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q110786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimateSingularActiveParticipleForm .
    ?masculineAnimateSingularActiveParticipleForm ontolex:representation ?masculineAnimateSingularActiveParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q110786, wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimatePluralPassiveParticipleForm .
    ?masculineAnimatePluralPassiveParticipleForm ontolex:representation ?masculineAnimatePluralPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q146786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimatePluralActiveParticipleForm .
    ?masculineAnimatePluralActiveParticipleForm ontolex:representation ?masculineAnimatePluralActiveParticiple ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q146786, wd:Q72249355 .
  }
}
