# tool: scribe-data
# All Polish (Q809) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?feminineSingularPassiveParticiple
  ?feminineSingularActiveParticiple
  ?neuterSingularPassiveParticiple
  ?neuterSingularActiveParticiple
  ?neuterPluralPassiveParticiple
  ?neuterPluralActiveParticiple

WHERE {
  ?lexeme dct:language wd:Q809 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularPassiveParticipleForm .
    ?feminineSingularPassiveParticipleForm ontolex:representation ?feminineSingularPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularActiveParticipleForm .
    ?feminineSingularActiveParticipleForm ontolex:representation ?feminineSingularActiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786, wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterSingularPassiveParticipleForm .
    ?neuterSingularPassiveParticipleForm ontolex:representation ?neuterSingularPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q110786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterSingularActiveParticipleForm .
    ?neuterSingularActiveParticipleForm ontolex:representation ?neuterSingularActiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q110786, wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralPassiveParticipleForm .
    ?neuterPluralPassiveParticipleForm ontolex:representation ?neuterPluralPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPluralActiveParticipleForm .
    ?neuterPluralActiveParticipleForm ontolex:representation ?neuterPluralActiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146786, wd:Q72249355 .
  }
}
