# tool: scribe-data
# All Hindi Hindustani (Q11051) prepositions (Q4833830) and the given forms.
# Enter this query at https://query.wikidata.org/.

# Note: We need to filter for "hi" to remove Urdu (ur) words.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?preposition

WHERE {
  ?lexeme dct:language wd:Q11051 ;
    wikibase:lexicalCategory wd:Q4833830 ;
    wikibase:lemma ?preposition .
    FILTER(lang(?preposition) = "hi")
}
