# tool: scribe-data
# All Dagbani (Q32238) nouns and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  ?lexeme  # unique ID for the data entry
  ?noun  # lemma or label of the ID

WHERE {
  ?lexeme dct:language wd:Q32238 ;  # Dagbani language
    wikibase:lexicalCategory wd:Q1084 ;  # Nouns
    wikibase:lemma ?noun .
}
