# tool: scribe-data
# All spanish (Q1321) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?nouns
    ?singularPastImperfectThirdPerson
  ?singular
  ?pluralFeminine
  ?pastImperfectPluralSecondPerson
  ?singularFirstPersonSubjunctiveFuture
  ?pastImperfectPluralFirstPerson
  ?pluralFirstPersonImperative
  ?singularSubjunctiveFutureSecondPerson
  ?singularFirstPersonPreteriteIndicative
  ?pluralFutureSecondPersonIndicative
  ?pluralFirstPersonPreteriteIndicative
  ?pluralMasculine
  ?pluralSubjunctiveFutureSecondPerson
  ?pastImperfectPluralThirdPerson
  ?singularPlural
  ?singularFeminine
  ?singularPreteriteThirdPersonIndicative
  ?pluralFirstPersonSubjunctiveFuture
  ?singularSubjunctiveFutureThirdPerson
  ?pluralPresentSecondPersonIndicative
  ?pluralPresentThirdPersonIndicative
  ?singularPresentSecondPersonIndicative
  ?singularPresentThirdPersonIndicative
  ?singularPluralMasculine
  ?pluralPositive
  ?pluralFirstPersonFutureIndicative
  ?pluralImperativeSecondPerson
  ?pluralSubjunctiveFutureThirdPerson
  ?singularFirstPersonFutureIndicative
  ?pluralPresentFirstPersonIndicative
  ?singularMasculine
  ?singularPastImperfectSecondPerson
  ?singularPresentFirstPersonIndicative
  ?singularPastImperfectFirstPerson
  ?singularFutureSecondPersonIndicative
  ?pluralFutureThirdPersonIndicative
  ?singularImperativeSecondPerson
  ?gerund
  ?pluralPreteriteSecondPersonIndicative
  ?pluralPreteriteThirdPersonIndicative
  ?feminine
  ?singularFutureThirdPersonIndicative
  ?singularPreteriteSecondPersonIndicative
  ?infinitive
  ?participle
  ?singularPositive
  ?femininePlural
  ?masculineSingular
  ?masculinePlural
  ?feminineSingular
    WHERE {
    ?lexeme dct:language wd:Q1321 ;
        wikibase:lexicalCategory wd:Q1084 ;
        wikibase:lemma ?nouns .
        FILTER(lang(?nouns) = "es")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPastImperfectThirdPersonForm .
            ?singularPastImperfectThirdPersonForm ontolex:representation ?singularPastImperfectThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFeminineForm .
            ?pluralFeminineForm ontolex:representation ?pluralFeminine ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q1775415 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectPluralSecondPersonForm .
            ?pastImperfectPluralSecondPersonForm ontolex:representation ?pastImperfectPluralSecondPerson ;
                wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFirstPersonSubjunctiveFutureForm .
            ?singularFirstPersonSubjunctiveFutureForm ontolex:representation ?singularFirstPersonSubjunctiveFuture ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q473746, wd:Q501405 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectPluralFirstPersonForm .
            ?pastImperfectPluralFirstPersonForm ontolex:representation ?pastImperfectPluralFirstPerson ;
                wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFirstPersonImperativeForm .
            ?pluralFirstPersonImperativeForm ontolex:representation ?pluralFirstPersonImperative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q22716 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularSubjunctiveFutureSecondPersonForm .
            ?singularSubjunctiveFutureSecondPersonForm ontolex:representation ?singularSubjunctiveFutureSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q473746, wd:Q501405, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFirstPersonPreteriteIndicativeForm .
            ?singularFirstPersonPreteriteIndicativeForm ontolex:representation ?singularFirstPersonPreteriteIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q442485, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFutureSecondPersonIndicativeForm .
            ?pluralFutureSecondPersonIndicativeForm ontolex:representation ?pluralFutureSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFirstPersonPreteriteIndicativeForm .
            ?pluralFirstPersonPreteriteIndicativeForm ontolex:representation ?pluralFirstPersonPreteriteIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q442485, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
            ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralSubjunctiveFutureSecondPersonForm .
            ?pluralSubjunctiveFutureSecondPersonForm ontolex:representation ?pluralSubjunctiveFutureSecondPerson ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q473746, wd:Q501405, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastImperfectPluralThirdPersonForm .
            ?pastImperfectPluralThirdPersonForm ontolex:representation ?pastImperfectPluralThirdPerson ;
                wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPluralForm .
            ?singularPluralForm ontolex:representation ?singularPlural ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFeminineForm .
            ?singularFeminineForm ontolex:representation ?singularFeminine ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1775415 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPreteriteThirdPersonIndicativeForm .
            ?singularPreteriteThirdPersonIndicativeForm ontolex:representation ?singularPreteriteThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFirstPersonSubjunctiveFutureForm .
            ?pluralFirstPersonSubjunctiveFutureForm ontolex:representation ?pluralFirstPersonSubjunctiveFuture ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q473746, wd:Q501405 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularSubjunctiveFutureThirdPersonForm .
            ?singularSubjunctiveFutureThirdPersonForm ontolex:representation ?singularSubjunctiveFutureThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q473746, wd:Q501405, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonIndicativeForm .
            ?pluralPresentSecondPersonIndicativeForm ontolex:representation ?pluralPresentSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonIndicativeForm .
            ?pluralPresentThirdPersonIndicativeForm ontolex:representation ?pluralPresentThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonIndicativeForm .
            ?singularPresentSecondPersonIndicativeForm ontolex:representation ?singularPresentSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPresentThirdPersonIndicativeForm .
            ?singularPresentThirdPersonIndicativeForm ontolex:representation ?singularPresentThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPluralMasculineForm .
            ?singularPluralMasculineForm ontolex:representation ?singularPluralMasculine ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146786, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPositiveForm .
            ?pluralPositiveForm ontolex:representation ?pluralPositive ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q3482678 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFirstPersonFutureIndicativeForm .
            ?pluralFirstPersonFutureIndicativeForm ontolex:representation ?pluralFirstPersonFutureIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q21714344, wd:Q501405, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralImperativeSecondPersonForm .
            ?pluralImperativeSecondPersonForm ontolex:representation ?pluralImperativeSecondPerson ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q22716, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralSubjunctiveFutureThirdPersonForm .
            ?pluralSubjunctiveFutureThirdPersonForm ontolex:representation ?pluralSubjunctiveFutureThirdPerson ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q473746, wd:Q501405, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFirstPersonFutureIndicativeForm .
            ?singularFirstPersonFutureIndicativeForm ontolex:representation ?singularFirstPersonFutureIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q21714344, wd:Q501405, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonIndicativeForm .
            ?pluralPresentFirstPersonIndicativeForm ontolex:representation ?pluralPresentFirstPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularMasculineForm .
            ?singularMasculineForm ontolex:representation ?singularMasculine ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPastImperfectSecondPersonForm .
            ?singularPastImperfectSecondPersonForm ontolex:representation ?singularPastImperfectSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonIndicativeForm .
            ?singularPresentFirstPersonIndicativeForm ontolex:representation ?singularPresentFirstPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPastImperfectFirstPersonForm .
            ?singularPastImperfectFirstPersonForm ontolex:representation ?singularPastImperfectFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFutureSecondPersonIndicativeForm .
            ?singularFutureSecondPersonIndicativeForm ontolex:representation ?singularFutureSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFutureThirdPersonIndicativeForm .
            ?pluralFutureThirdPersonIndicativeForm ontolex:representation ?pluralFutureThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q501405, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularImperativeSecondPersonForm .
            ?singularImperativeSecondPersonForm ontolex:representation ?singularImperativeSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q22716, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?gerundForm .
            ?gerundForm ontolex:representation ?gerund ;
                wikibase:grammaticalFeature wd:Q1923028 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPreteriteSecondPersonIndicativeForm .
            ?pluralPreteriteSecondPersonIndicativeForm ontolex:representation ?pluralPreteriteSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPreteriteThirdPersonIndicativeForm .
            ?pluralPreteriteThirdPersonIndicativeForm ontolex:representation ?pluralPreteriteThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q442485, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineForm .
            ?feminineForm ontolex:representation ?feminine ;
                wikibase:grammaticalFeature wd:Q1775415 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFutureThirdPersonIndicativeForm .
            ?singularFutureThirdPersonIndicativeForm ontolex:representation ?singularFutureThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q501405, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPreteriteSecondPersonIndicativeForm .
            ?singularPreteriteSecondPersonIndicativeForm ontolex:representation ?singularPreteriteSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q442485, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?infinitiveForm .
            ?infinitiveForm ontolex:representation ?infinitive ;
                wikibase:grammaticalFeature wd:Q179230 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?participleForm .
            ?participleForm ontolex:representation ?participle ;
                wikibase:grammaticalFeature wd:Q814722 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPositiveForm .
            ?singularPositiveForm ontolex:representation ?singularPositive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q3482678 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?femininePluralForm .
            ?femininePluralForm ontolex:representation ?femininePlural ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineSingularForm .
            ?masculineSingularForm ontolex:representation ?masculineSingular ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculinePluralForm .
            ?masculinePluralForm ontolex:representation ?masculinePlural ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineSingularForm .
            ?feminineSingularForm ontolex:representation ?feminineSingular ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
        }
}