# tool: scribe-data
# All Urdu (from Hindustani Q11051) adverbs.
# Enter this query at https://query.wikidata.org/.
# Note the necessity to filter for "ur" to remove Hindi (hi) words.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adverb

WHERE {
  ?lexeme dct:language wd:Q11051 ;  # Urdu language (from Hindustani)
    wikibase:lexicalCategory wd:Q380057 ;  # Adverbs
    wikibase:lemma ?adverb .

  BIND(lang(?adverb) as ?langAdverb)
  FILTER(?langAdverb = "ur")

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]".
  }
}
