# tool: scribe-data
# All Esperanto (Q143) Proper Nouns.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?propernouns

WHERE {

  ?lexeme dct:language wd:Q143 ;  # Esperanto
    wikibase:lexicalCategory wd:Q147276 ;  # Proper Nouns
    wikibase:lemma ?propernouns .

  # Ensure we get only the lexeme forms that are adjectives in Esperanto
  FILTER(LANG(?propernouns) = "eo") .
}
