# tool: scribe-data
# All Korean (Q9176) postpositions (Q161873) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?postposition

WHERE {
  ?lexeme dct:language wd:Q9176 ;
    wikibase:lexicalCategory wd:Q161873 ;
    wikibase:lemma ?postposition .
}
