# tool: scribe-data
# All Russian (Q7737) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?prepositionalSingular
  ?prepositionalPlural
  ?prepositionalFeminineSingular
  ?prepositionalMasculineSingular

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalSingularForm .
    ?prepositionalSingularForm ontolex:representation ?prepositionalSingular ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalPluralForm .
    ?prepositionalPluralForm ontolex:representation ?prepositionalPlural ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalFeminineSingularForm .
    ?prepositionalFeminineSingularForm ontolex:representation ?prepositionalFeminineSingular ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalMasculineSingularForm .
    ?prepositionalMasculineSingularForm ontolex:representation ?prepositionalMasculineSingular ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q499327, wd:Q110786 .
  }
}
