# tool: scribe-data
# All italian (Q652) nouns (Q1084) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nouns
    ?singularMasculine
  ?singularFeminine
  ?pluralMasculine
  ?vocative
  ?pluralFeminine
  ?singular
  ?singularPlural

WHERE {
  ?lexeme dct:language wd:Q652 ;
  wikibase:lexicalCategory wd:Q1084 ;
  wikibase:lemma ?nouns .
  FILTER(lang(?nouns) = "it")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineForm .
    ?singularMasculineForm ontolex:representation ?singularMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineForm .
    ?singularFeminineForm ontolex:representation ?singularFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
    ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineForm .
    ?pluralFeminineForm ontolex:representation ?pluralFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPluralForm .
    ?singularPluralForm ontolex:representation ?singularPlural ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146786 .
  }
}
