# tool: scribe-data
# All German (Q188) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?indicativeActivePresentSecondPersonSingular
  ?indicativeActiveFutureSecondPersonPlural
  ?indicativeActivePerfectSecondPersonPlural
  ?indicativeActivePerfectThirdPersonPlural
  ?indicativeActivePluperfectFirstPersonPlural
  ?indicativeActivePluperfectThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q188 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePresentSecondPersonSingularForm .
    ?indicativeActivePresentSecondPersonSingularForm ontolex:representation ?indicativeActivePresentSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q192613, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActiveFutureSecondPersonPluralForm .
    ?indicativeActiveFutureSecondPersonPluralForm ontolex:representation ?indicativeActiveFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q501405, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePerfectSecondPersonPluralForm .
    ?indicativeActivePerfectSecondPersonPluralForm ontolex:representation ?indicativeActivePerfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q625420, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePerfectThirdPersonPluralForm .
    ?indicativeActivePerfectThirdPersonPluralForm ontolex:representation ?indicativeActivePerfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q625420, wd:Q51929074, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePluperfectFirstPersonPluralForm .
    ?indicativeActivePluperfectFirstPersonPluralForm ontolex:representation ?indicativeActivePluperfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q623742, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePluperfectThirdPersonPluralForm .
    ?indicativeActivePluperfectThirdPersonPluralForm ontolex:representation ?indicativeActivePluperfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q623742, wd:Q51929074, wd:Q146786 .
  }
}
