# tool: scribe-data
# All German (Q188) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?activeInfinitivePresent
  ?activeInfinitivePerfect
  ?activeImperativePresentSecondPersonSingular
  ?activeImperativePresentSecondPersonPlural
  ?activeImperativePresentSecondPersonSingularPlural

WHERE {
  ?lexeme dct:language wd:Q188 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeInfinitivePresentForm .
    ?activeInfinitivePresentForm ontolex:representation ?activeInfinitivePresent ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q179230, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeInfinitivePerfectForm .
    ?activeInfinitivePerfectForm ontolex:representation ?activeInfinitivePerfect ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q179230, wd:Q625420 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativePresentSecondPersonSingularForm .
    ?activeImperativePresentSecondPersonSingularForm ontolex:representation ?activeImperativePresentSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q192613, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativePresentSecondPersonPluralForm .
    ?activeImperativePresentSecondPersonPluralForm ontolex:representation ?activeImperativePresentSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q192613, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativePresentSecondPersonSingularPluralForm .
    ?activeImperativePresentSecondPersonSingularPluralForm ontolex:representation ?activeImperativePresentSecondPersonSingularPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q192613, wd:Q51929049, wd:Q110786, wd:Q146786 .
  }
}
