# tool: scribe-data
# All German (Q188) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?presentFirstPersonSingular
  ?presentFirstPersonPlural
  ?pluperfectFirstPersonSingular
  ?pluperfectFirstPersonPlural
  ?pluperfectSecondPersonSingular
  ?pluperfectSecondPersonPlural

WHERE {
  ?lexeme dct:language wd:Q188 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentFirstPersonSingularForm .
    ?presentFirstPersonSingularForm ontolex:representation ?presentFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentFirstPersonPluralForm .
    ?presentFirstPersonPluralForm ontolex:representation ?presentFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q192613, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonSingularForm .
    ?pluperfectFirstPersonSingularForm ontolex:representation ?pluperfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonPluralForm .
    ?pluperfectFirstPersonPluralForm ontolex:representation ?pluperfectFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonSingularForm .
    ?pluperfectSecondPersonSingularForm ontolex:representation ?pluperfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonPluralForm .
    ?pluperfectSecondPersonPluralForm ontolex:representation ?pluperfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q146786 .
  }
}
