# tool: scribe-data
# All  (Q7737) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?gender
  ?nominativeSingular
  ?nominativePlural

WHERE {
  ?lexeme dct:language wd:Q7737;
    wikibase:lexicalCategory wd:Q1084;
    wikibase:lemma ?noun;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme wdt:P5185 ?nounGender.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm.
    ?nominativeSingularForm ontolex:representation ?nominativeSingular;
    wikibase:grammaticalFeature wd:Q131105, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm.
    ?nominativePluralForm ontolex:representation ?nominativePlural;
    wikibase:grammaticalFeature wd:Q131105, wd:Q146786.
  }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
    ?nounGender rdfs:label ?gender.
  }
}
