# tool: scribe-data
# All Russian (Q7737) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?genitiveSingular
  ?genitivePlural
  ?nominativeAccusativeSingular
  ?nominativeAccusativePlural
  ?genitiveAccusativeSingular

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeAccusativeSingularForm .
    ?nominativeAccusativeSingularForm ontolex:representation ?nominativeAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeAccusativePluralForm .
    ?nominativeAccusativePluralForm ontolex:representation ?nominativeAccusativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146078, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveAccusativeSingularForm .
    ?genitiveAccusativeSingularForm ontolex:representation ?genitiveAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146078, wd:Q110786 .
  }
}
