# tool: scribe-data
# All latin (Q397) adverbs (Q380057) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?adverbs
    ?positive
    WHERE {
    ?lexeme dct:language wd:Q397 ;
        wikibase:lexicalCategory wd:Q380057 ;
        wikibase:lemma ?adverbs .
        FILTER(lang(?adverbs) = "la")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?positiveForm .
            ?positiveForm ontolex:representation ?positive ;
                wikibase:grammaticalFeature wd:Q3482678 .
        }
}