# tool: scribe-data
# All English (Q1860) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?singular
  ?plural

WHERE {
  ?lexeme dct:language wd:Q1860;
    wikibase:lexicalCategory wd:Q1084;
    wikibase:lemma ?noun;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?sForm.
    ?sForm ontolex:representation ?singular;
    wikibase:grammaticalFeature wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pForm.
    ?pForm ontolex:representation ?plural;
    wikibase:grammaticalFeature wd:Q146786.
  }
}
