# tool: scribe-data
# All English (Q1860) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?infinitive
  ?simplePresent
  ?presentParticiple
  ?simplePast
  ?englishPastParticiple
  ?simplePresentThirdPersonSingular

WHERE {
  ?lexeme dct:language wd:Q1860;
    wikibase:lexicalCategory wd:Q24905;
    wikibase:lemma ?verb;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infForm.
    ?infForm ontolex:representation ?infinitive;
    wikibase:grammaticalFeature wd:Q179230.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simPreForm.
    ?simPreForm ontolex:representation ?simplePresent;
    wikibase:grammaticalFeature wd:Q3910936.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?preParForm.
    ?preParForm ontolex:representation ?presentParticiple;
    wikibase:grammaticalFeature wd:Q10345583.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simPasForm.
    ?simPasForm ontolex:representation ?simplePast;
    wikibase:grammaticalFeature wd:Q1392475.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?engPasParForm.
    ?engPasParForm ontolex:representation ?englishPastParticiple;
    wikibase:grammaticalFeature wd:Q1230649.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simPreThiPerSinForm.
    ?simPreThiPerSinForm ontolex:representation ?simplePresentThirdPersonSingular;
    wikibase:grammaticalFeature wd:Q3910936, wd:Q51929074, wd:Q110786.
  }
}
