# tool: scribe-data
# All hebrew (Q9288) proper_nouns (Q147276) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?proper_nouns
    ?singularMasculine
  ?singularFeminine
  ?pluralMasculine
  ?pluralFeminine
  ?pluralConstructMasculine
  ?singularPausal
  ?feminine
  ?pluralConstructFeminine
  ?singular
  ?singularConstructMasculine
  ?singularConstructFeminine
  ?singularNominative

WHERE {
  ?lexeme dct:language wd:Q9288 ;
  wikibase:lexicalCategory wd:Q147276 ;
  wikibase:lemma ?proper_nouns .
  FILTER(lang(?proper_nouns) = "he")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineForm .
    ?singularMasculineForm ontolex:representation ?singularMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineForm .
    ?singularFeminineForm ontolex:representation ?singularFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
    ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineForm .
    ?pluralFeminineForm ontolex:representation ?pluralFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructMasculineForm .
    ?pluralConstructMasculineForm ontolex:representation ?pluralConstructMasculine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPausalForm .
    ?singularPausalForm ontolex:representation ?singularPausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineForm .
    ?feminineForm ontolex:representation ?feminine ;
      wikibase:grammaticalFeature wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralConstructFeminineForm .
    ?pluralConstructFeminineForm ontolex:representation ?pluralConstructFeminine ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1641446, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructMasculineForm .
    ?singularConstructMasculineForm ontolex:representation ?singularConstructMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularConstructFeminineForm .
    ?singularConstructFeminineForm ontolex:representation ?singularConstructFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1641446, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }
}
