# tool: scribe-data
# All Swedish (Q9027) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?vocative
  ?plural
  ?masculineSingular
  ?commonSingular
  ?feminineMasculineCommonSingular

WHERE {
  ?lexeme dct:language wd:Q9027 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularForm .
    ?masculineSingularForm ontolex:representation ?masculineSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?commonSingularForm .
    ?commonSingularForm ontolex:representation ?commonSingular ;
      wikibase:grammaticalFeature wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineCommonSingularForm .
    ?feminineMasculineCommonSingularForm ontolex:representation ?feminineMasculineCommonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q1305037, wd:Q110786 .
  }
}
