# tool: scribe-data
# All Kurmanji (Q36163) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?singularVocative
  ?singularDirectIndefinite
  ?singularDirectDefinite
  ?singularObliqueIndefinite
  ?singularObliqueDefinite

WHERE {
  ?lexeme dct:language wd:Q36163 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeForm .
    ?singularVocativeForm ontolex:representation ?singularVocative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDirectIndefiniteForm .
    ?singularDirectIndefiniteForm ontolex:representation ?singularDirectIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1751855, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDirectDefiniteForm .
    ?singularDirectDefiniteForm ontolex:representation ?singularDirectDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1751855, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueIndefiniteForm .
    ?singularObliqueIndefiniteForm ontolex:representation ?singularObliqueIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueDefiniteForm .
    ?singularObliqueDefiniteForm ontolex:representation ?singularObliqueDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197, wd:Q53997851 .
  }
}
