# tool: scribe-data
# All Kurmanji (Q36163) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?directIndefiniteSingular
  ?directIndefinitePlural
  ?obliqueMasculineSingular
  ?obliqueMasculinePlural
  ?obliqueIndefiniteSingular
  ?obliqueIndefinitePlural

WHERE {
  ?lexeme dct:language wd:Q36163 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directIndefiniteSingularForm .
    ?directIndefiniteSingularForm ontolex:representation ?directIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directIndefinitePluralForm .
    ?directIndefinitePluralForm ontolex:representation ?directIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueMasculineSingularForm .
    ?obliqueMasculineSingularForm ontolex:representation ?obliqueMasculineSingular ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueMasculinePluralForm .
    ?obliqueMasculinePluralForm ontolex:representation ?obliqueMasculinePlural ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueIndefiniteSingularForm .
    ?obliqueIndefiniteSingularForm ontolex:representation ?obliqueIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueIndefinitePluralForm .
    ?obliqueIndefinitePluralForm ontolex:representation ?obliqueIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q53997857, wd:Q146786 .
  }
}
