# tool: scribe-data
# All Ibibio language(unknown) adverbs.
# Enter this query at https://query.wikidata.org/.

SELECT 
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb

WHERE {
  ?lexeme dct:language wd:Q1033; # using nigeria as the language identifier
    wikibase:lexicalCategory wd:Q24905;
    wikibase:lemma ?verb .
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
