# tool: scribe-data
# All Malayalam (Q36236) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?dative
  ?dativeSingular
  ?dativePlural
  ?dativeThirdPersonSingular
  ?dativeThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q36236 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeThirdPersonSingularForm .
    ?dativeThirdPersonSingularForm ontolex:representation ?dativeThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeThirdPersonPluralForm .
    ?dativeThirdPersonPluralForm ontolex:representation ?dativeThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q51929074, wd:Q146786 .
  }
}
