# tool: scribe-data
# All Malayalam (Q36236) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?instrumental
  ?instrumentalSingular
  ?instrumentalPlural
  ?instrumentalThirdPersonSingular
  ?instrumentalThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q36236 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalForm .
    ?instrumentalForm ontolex:representation ?instrumental ;
      wikibase:grammaticalFeature wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalSingularForm .
    ?instrumentalSingularForm ontolex:representation ?instrumentalSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalPluralForm .
    ?instrumentalPluralForm ontolex:representation ?instrumentalPlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalThirdPersonSingularForm .
    ?instrumentalThirdPersonSingularForm ontolex:representation ?instrumentalThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalThirdPersonPluralForm .
    ?instrumentalThirdPersonPluralForm ontolex:representation ?instrumentalThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q51929074, wd:Q146786 .
  }
}
