# tool: scribe-data
# All Bengali (Q9610) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?feminine
  ?feminineComparative
  ?feminineSuperlative
  ?femininePositive

WHERE {
  ?lexeme dct:language wd:Q9610 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineForm .
    ?feminineForm ontolex:representation ?feminine ;
      wikibase:grammaticalFeature wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineComparativeForm .
    ?feminineComparativeForm ontolex:representation ?feminineComparative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSuperlativeForm .
    ?feminineSuperlativeForm ontolex:representation ?feminineSuperlative ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePositiveForm .
    ?femininePositiveForm ontolex:representation ?femininePositive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q3482678 .
  }
}
