# tool: scribe-data
# All Bokmål (Q25167) verbs and basic forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?presentPerfect
  ?imperative
  ?preterite
  ?infinitiveActive
  ?presentTenseActive
  ?infinitivePassive
  ?presentTensePassive
  ?infinitive
  ?activePresent

WHERE {
  ?lexeme dct:language wd:Q25167;
          wikibase:lexicalCategory wd:Q24905.

  # MARK: present perfect
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentPerfectForm.
    ?presentPerfectForm ontolex:representation ?presentPerfect;
      wikibase:grammaticalFeature wd:Q1240211.
  }

  # MARK: infinitive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveForm.
    ?infinitiveForm ontolex:representation ?infinitive;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1317831.
  }

  # MARK: imperative
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeForm.
    ?imperativeForm ontolex:representation ?imperative;
      wikibase:grammaticalFeature wd:Q22716.
  }

  # MARK: preterite
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?preteriteForm.
    ?preteriteForm ontolex:representation ?preterite;
      wikibase:grammaticalFeature wd:Q442485.
  }

  # MARK: infinitive active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveActiveForm.
    ?infinitiveActiveForm ontolex:representation ?infinitiveActive;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1317831.
  }

  # MARK: present tense active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentTenseActiveForm.
    ?presentTenseActiveForm ontolex:representation ?presentTenseActive;
      wikibase:grammaticalFeature wd:Q192613, wd:Q1317831.
  }

  # MARK: infinitive passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePassiveForm.
    ?infinitivePassiveForm ontolex:representation ?infinitivePassive;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1194697.
  }

  # MARK: present tense passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentTensePassiveForm.
    ?presentTensePassiveForm ontolex:representation ?presentTensePassive;
      wikibase:grammaticalFeature wd:Q192613, wd:Q1194697.
  }

  # MARK: active present
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePresentForm.
    ?activePresentForm ontolex:representation ?activePresent;
      wikibase:grammaticalFeature wd:Q192613, wd:Q1317831.
  }
}
