# tool: scribe-data
# All Russian (Q7737) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?dative
  ?dativeSingular
  ?dativeFirstPersonSingular
  ?dativeFirstPersonPlural
  ?dativeSecondPersonSingular
  ?dativeSecondPersonPlural

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFirstPersonSingularForm .
    ?dativeFirstPersonSingularForm ontolex:representation ?dativeFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFirstPersonPluralForm .
    ?dativeFirstPersonPluralForm ontolex:representation ?dativeFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSecondPersonSingularForm .
    ?dativeSecondPersonSingularForm ontolex:representation ?dativeSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSecondPersonPluralForm .
    ?dativeSecondPersonPluralForm ontolex:representation ?dativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q51929049, wd:Q146786 .
  }
}
