# tool: scribe-data
# All Slovak (Q9058) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?instrumentalFeminineSingularComparative
  ?instrumentalFeminineSingularSuperlative
  ?instrumentalFeminineSingularPositive
  ?instrumentalMasculineSingularComparative
  ?instrumentalMasculineSingularSuperlative
  ?instrumentalMasculineSingularPositive

WHERE {
  ?lexeme dct:language wd:Q9058 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularComparativeForm .
    ?instrumentalFeminineSingularComparativeForm ontolex:representation ?instrumentalFeminineSingularComparative ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularSuperlativeForm .
    ?instrumentalFeminineSingularSuperlativeForm ontolex:representation ?instrumentalFeminineSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularPositiveForm .
    ?instrumentalFeminineSingularPositiveForm ontolex:representation ?instrumentalFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineSingularComparativeForm .
    ?instrumentalMasculineSingularComparativeForm ontolex:representation ?instrumentalMasculineSingularComparative ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineSingularSuperlativeForm .
    ?instrumentalMasculineSingularSuperlativeForm ontolex:representation ?instrumentalMasculineSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineSingularPositiveForm .
    ?instrumentalMasculineSingularPositiveForm ontolex:representation ?instrumentalMasculineSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110786, wd:Q3482678 .
  }
}
