# tool: scribe-data
# All Slovak (Q9058) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularInstrumentalFemininePositive
  ?singularInstrumentalMasculinePositive
  ?singularInstrumentalNeuterPositive
  ?singularLocativeFemininePositive
  ?singularLocativeMasculinePositive
  ?singularLocativeNeuterPositive

WHERE {
  ?lexeme dct:language wd:Q9058 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInstrumentalFemininePositiveForm .
    ?singularInstrumentalFemininePositiveForm ontolex:representation ?singularInstrumentalFemininePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192997, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInstrumentalMasculinePositiveForm .
    ?singularInstrumentalMasculinePositiveForm ontolex:representation ?singularInstrumentalMasculinePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192997, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInstrumentalNeuterPositiveForm .
    ?singularInstrumentalNeuterPositiveForm ontolex:representation ?singularInstrumentalNeuterPositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192997, wd:Q1775461, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeFemininePositiveForm .
    ?singularLocativeFemininePositiveForm ontolex:representation ?singularLocativeFemininePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeMasculinePositiveForm .
    ?singularLocativeMasculinePositiveForm ontolex:representation ?singularLocativeMasculinePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeNeuterPositiveForm .
    ?singularLocativeNeuterPositiveForm ontolex:representation ?singularLocativeNeuterPositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775461, wd:Q3482678 .
  }
}
