# tool: scribe-data
# All Slovak (Q9058) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjective
  ?locativePluralPositive
  ?locativeFeminineSingularPositive
  ?locativeMasculineSingularPositive
  ?locativeNeuterSingularPositive

WHERE {
  ?lexeme dct:language wd:Q9058;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective .

  # MARK: Locative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralPositiveForm .
    ?locativePluralPositiveForm ontolex:representation ?locativePluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularPositiveForm .
    ?locativeFeminineSingularPositiveForm ontolex:representation ?locativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineSingularPositiveForm .
    ?locativeMasculineSingularPositiveForm ontolex:representation ?locativeMasculineSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularPositiveForm .
    ?locativeNeuterSingularPositiveForm ontolex:representation ?locativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }
}
