# tool: scribe-data
# All Slovak (Q9058) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?genitivePluralPositive
  ?dativePluralPositive
  ?nominativePluralPositiveMasculinePersonal
  ?nominativePluralPositiveNotMasculinePersonal
  ?accusativePluralPositiveMasculinePersonal
  ?accusativePluralPositiveNotMasculinePersonal

WHERE {
  ?lexeme dct:language wd:Q9058 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralPositiveForm .
    ?genitivePluralPositiveForm ontolex:representation ?genitivePluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralPositiveForm .
    ?dativePluralPositiveForm ontolex:representation ?dativePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralPositiveMasculinePersonalForm .
    ?nominativePluralPositiveMasculinePersonalForm ontolex:representation ?nominativePluralPositiveMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q3482678, wd:Q27918551 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralPositiveNotMasculinePersonalForm .
    ?nominativePluralPositiveNotMasculinePersonalForm ontolex:representation ?nominativePluralPositiveNotMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q3482678, wd:Q54152717 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralPositiveMasculinePersonalForm .
    ?accusativePluralPositiveMasculinePersonalForm ontolex:representation ?accusativePluralPositiveMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q3482678, wd:Q27918551 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralPositiveNotMasculinePersonalForm .
    ?accusativePluralPositiveNotMasculinePersonalForm ontolex:representation ?accusativePluralPositiveNotMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q3482678, wd:Q54152717 .
  }
}
