# tool: scribe-data
# All Spanish (Q1321) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?imperfectFirstPersonSingular
  ?imperfectFirstPersonPlural
  ?imperfectSecondPersonSingular
  ?imperfectSecondPersonPlural
  ?imperfectThirdPersonSingular
  ?imperfectThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q1321;
    wikibase:lexicalCategory wd:Q24905;
    wikibase:lemma ?verb;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impFirPerSinForm.
    ?impFirPerSinForm ontolex:representation ?imperfectFirstPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q21714344, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impFirPerPluForm.
    ?impFirPerPluForm ontolex:representation ?imperfectFirstPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q21714344, wd:Q146786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impSecPerSinForm.
    ?impSecPerSinForm ontolex:representation ?imperfectSecondPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929049, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impSecPerPluForm.
    ?impSecPerPluForm ontolex:representation ?imperfectSecondPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929049, wd:Q146786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impThiPerSinForm.
    ?impThiPerSinForm ontolex:representation ?imperfectThirdPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929074, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?impThiPerPluForm.
    ?impThiPerPluForm ontolex:representation ?imperfectThirdPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929074, wd:Q146786.
  }
}
