# tool: scribe-data
# All Spanish (Q1321) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (replace(str(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?imperfectFirstPersonSingular
  ?imperfectFirstPersonPlural
  ?imperfectSecondPersonSingular
  ?imperfectSecondPersonPlural
  ?imperfectThirdPersonSingular
  ?imperfectThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q1321;
    wikibase:lexicalCategory wd:Q24905;
    wikibase:lemma ?verb;
    schema:dateModified ?lastModified.

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectFirstPersonSingularForm.
    ?imperfectFirstPersonSingularForm ontolex:representation ?imperfectFirstPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q21714344, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectFirstPersonPluralForm.
    ?imperfectFirstPersonPluralForm ontolex:representation ?imperfectFirstPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q21714344, wd:Q146786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectSecondPersonSingularForm.
    ?imperfectSecondPersonSingularForm ontolex:representation ?imperfectSecondPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929049, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectSecondPersonPluralForm.
    ?imperfectSecondPersonPluralForm ontolex:representation ?imperfectSecondPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929049, wd:Q146786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectThirdPersonSingularForm.
    ?imperfectThirdPersonSingularForm ontolex:representation ?imperfectThirdPersonSingular;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929074, wd:Q110786.
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperfectThirdPersonPluralForm.
    ?imperfectThirdPersonPluralForm ontolex:representation ?imperfectThirdPersonPlural;
    wikibase:grammaticalFeature wd:Q108524486, wd:Q51929074, wd:Q146786.
  }
}
