# tool: scribe-data
# All swedish (Q9027) adverbs (Q380057) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?adverbs
    ?singularPositiveMasculineDefinite
  ?singularNeuterPositiveIndefinite
  ?superlative
  ?positive
  ?singularCommonPositiveIndefinite
  ?singularPositiveDefinite
  ?comparative
  ?pluralPositiveDefinite
    WHERE {
    ?lexeme dct:language wd:Q9027 ;
        wikibase:lexicalCategory wd:Q380057 ;
        wikibase:lemma ?adverbs .
        FILTER(lang(?adverbs) = "sv")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPositiveMasculineDefiniteForm .
            ?singularPositiveMasculineDefiniteForm ontolex:representation ?singularPositiveMasculineDefinite ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q3482678, wd:Q499327, wd:Q53997851 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNeuterPositiveIndefiniteForm .
            ?singularNeuterPositiveIndefiniteForm ontolex:representation ?singularNeuterPositiveIndefinite ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q3482678, wd:Q53997857 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?superlativeForm .
            ?superlativeForm ontolex:representation ?superlative ;
                wikibase:grammaticalFeature wd:Q1817208 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?positiveForm .
            ?positiveForm ontolex:representation ?positive ;
                wikibase:grammaticalFeature wd:Q3482678 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularCommonPositiveIndefiniteForm .
            ?singularCommonPositiveIndefiniteForm ontolex:representation ?singularCommonPositiveIndefinite ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1305037, wd:Q3482678, wd:Q53997857 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPositiveDefiniteForm .
            ?singularPositiveDefiniteForm ontolex:representation ?singularPositiveDefinite ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q3482678, wd:Q53997851 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?comparativeForm .
            ?comparativeForm ontolex:representation ?comparative ;
                wikibase:grammaticalFeature wd:Q14169499 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralPositiveDefiniteForm .
            ?pluralPositiveDefiniteForm ontolex:representation ?pluralPositiveDefinite ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q3482678, wd:Q53997851 .
        }
}