# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?nominative
  ?genitive
  ?dative
  ?accusative
  ?instrumental
  ?locative
  ?vocative
  ?nominativeSingular
  ?genitiveSingular
  ?dativeSingular
  ?accusativeSingular
  ?instrumentalSingular
  ?locativeSingular
  ?vocativeSingular
  ?nominativeFeminineSingular
  ?nominativeFemininePlural
  ?nominativeMasculineSingular
  ?nominativeMasculineInanimateSingular
  ?nominativeMasculineInanimatePlural
  ?nominativeMasculineAnimateSingular
  ?nominativeMasculineAnimatePlural
  ?nominativeNeuterSingular
  ?nominativeNeuterPlural
  ?genitiveFeminineSingular
  ?genitiveFemininePlural
  ?genitiveMasculineSingular
  ?genitiveMasculineInanimateSingular
  ?genitiveMasculineInanimatePlural
  ?genitiveMasculineAnimateSingular
  ?genitiveMasculineAnimatePlural
  ?genitiveNeuterSingular
  ?genitiveNeuterPlural
  ?dativeFeminineSingular
  ?dativeFemininePlural
  ?dativeMasculineSingular
  ?dativeMasculineInanimateSingular
  ?dativeMasculineInanimatePlural
  ?dativeMasculineAnimateSingular
  ?dativeMasculineAnimatePlural
  ?dativeNeuterSingular
  ?dativeNeuterPlural
  ?accusativeFeminineSingular
  ?accusativeFemininePlural
  ?accusativeMasculineInanimateSingular
  ?accusativeMasculineInanimatePlural
  ?accusativeMasculineAnimateSingular
  ?accusativeMasculineAnimatePlural
  ?accusativeNeuterSingular
  ?accusativeNeuterPlural
  ?instrumentalFeminineSingular
  ?instrumentalFemininePlural
  ?instrumentalMasculineSingular
  ?instrumentalMasculineInanimateSingular
  ?instrumentalMasculineInanimatePlural
  ?instrumentalMasculineAnimateSingular
  ?instrumentalMasculineAnimatePlural
  ?instrumentalNeuterSingular
  ?instrumentalNeuterPlural
  ?locativeFeminineSingular
  ?locativeFemininePlural
  ?locativeMasculineSingular
  ?locativeMasculineInanimateSingular
  ?locativeMasculineInanimatePlural
  ?locativeMasculineAnimateSingular
  ?locativeMasculineAnimatePlural
  ?locativeNeuterSingular
  ?locativeNeuterPlural
  ?vocativeFeminineSingular
  ?vocativeFemininePlural
  ?vocativeMasculineSingular
  ?vocativeMasculineInanimateSingular
  ?vocativeMasculineInanimatePlural
  ?vocativeMasculineAnimateSingular
  ?vocativeMasculineAnimatePlural
  ?vocativeNeuterSingular
  ?vocativeNeuterPlural
  ?nominativeFeminineSingularPositive
  ?nominativeFemininePluralPositive
  ?nominativeMasculineInanimateSingularPositive
  ?nominativeMasculineInanimatePluralPositive
  ?nominativeMasculineAnimateSingularPositive
  ?nominativeMasculineAnimatePluralPositive
  ?nominativeNeuterSingularPositive
  ?nominativeNeuterPluralPositive
  ?genitiveFeminineSingularPositive
  ?genitiveFemininePluralPositive
  ?genitiveMasculineInanimateSingularPositive
  ?genitiveMasculineInanimatePluralPositive
  ?genitiveMasculineAnimateSingularPositive
  ?genitiveMasculineAnimatePluralPositive
  ?genitiveNeuterSingularPositive
  ?genitiveNeuterPluralPositive
  ?dativeFeminineSingularPositive
  ?dativeFemininePluralPositive
  ?dativeMasculineInanimateSingularPositive
  ?dativeMasculineInanimatePluralPositive
  ?dativeMasculineAnimateSingularPositive
  ?dativeMasculineAnimatePluralPositive
  ?dativeNeuterSingularPositive
  ?dativeNeuterPluralPositive
  ?accusativeFeminineSingularPositive
  ?accusativeFemininePluralPositive
  ?accusativeMasculineInanimateSingularPositive
  ?accusativeMasculineInanimatePluralPositive
  ?accusativeMasculineAnimateSingularPositive
  ?accusativeMasculineAnimatePluralPositive
  ?accusativeNeuterSingularPositive
  ?accusativeNeuterPluralPositive
  ?instrumentalFeminineSingularPositive
  ?instrumentalFemininePluralPositive
  ?instrumentalMasculineInanimateSingularPositive
  ?instrumentalMasculineInanimatePluralPositive
  ?instrumentalMasculineAnimateSingularPositive
  ?instrumentalMasculineAnimatePluralPositive
  ?instrumentalNeuterSingularPositive
  ?instrumentalNeuterPluralPositive
  ?locativeFeminineSingularPositive
  ?locativeFemininePluralPositive
  ?locativeMasculineInanimateSingularPositive
  ?locativeMasculineInanimatePluralPositive
  ?locativeMasculineAnimateSingularPositive
  ?locativeMasculineAnimatePluralPositive
  ?locativeNeuterSingularPositive
  ?locativeNeuterPluralPositive
  ?vocativeFeminineSingularPositive
  ?vocativeFemininePluralPositive
  ?vocativeMasculineInanimateSingularPositive
  ?vocativeMasculineInanimatePluralPositive
  ?vocativeMasculineAnimateSingularPositive
  ?vocativeMasculineAnimatePluralPositive
  ?vocativeNeuterSingularPositive
  ?vocativeNeuterPluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
      wikibase:lexicalCategory wd:Q36224 ;
      wikibase:lemma ?pronoun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalForm .
    ?instrumentalForm ontolex:representation ?instrumental ;
      wikibase:grammaticalFeature wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeForm .
    ?locativeForm ontolex:representation ?locative ;
      wikibase:grammaticalFeature wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalSingularForm .
    ?instrumentalSingularForm ontolex:representation ?instrumentalSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFeminineSingularForm .
    ?nominativeFeminineSingularForm ontolex:representation ?nominativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFemininePluralForm .
    ?nominativeFemininePluralForm ontolex:representation ?nominativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineSingularForm .
    ?nominativeMasculineSingularForm ontolex:representation ?nominativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimateSingularForm .
    ?nominativeMasculineInanimateSingularForm ontolex:representation ?nominativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimatePluralForm .
    ?nominativeMasculineInanimatePluralForm ontolex:representation ?nominativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularForm .
    ?nominativeMasculineAnimateSingularForm ontolex:representation ?nominativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralForm .
    ?nominativeMasculineAnimatePluralForm ontolex:representation ?nominativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularForm .
    ?nominativeNeuterSingularForm ontolex:representation ?nominativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPluralForm .
    ?nominativeNeuterPluralForm ontolex:representation ?nominativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularForm .
    ?genitiveFeminineSingularForm ontolex:representation ?genitiveFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePluralForm .
    ?genitiveFemininePluralForm ontolex:representation ?genitiveFemininePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularForm .
    ?genitiveMasculineSingularForm ontolex:representation ?genitiveMasculineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineInanimateSingularForm .
    ?genitiveMasculineInanimateSingularForm ontolex:representation ?genitiveMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineInanimatePluralForm .
    ?genitiveMasculineInanimatePluralForm ontolex:representation ?genitiveMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineAnimateSingularForm .
    ?genitiveMasculineAnimateSingularForm ontolex:representation ?genitiveMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineAnimatePluralForm .
    ?genitiveMasculineAnimatePluralForm ontolex:representation ?genitiveMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterSingularForm .
    ?genitiveNeuterSingularForm ontolex:representation ?genitiveNeuterSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPluralForm .
    ?genitiveNeuterPluralForm ontolex:representation ?genitiveNeuterPlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularForm .
    ?dativeFeminineSingularForm ontolex:representation ?dativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePluralForm .
    ?dativeFemininePluralForm ontolex:representation ?dativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineSingularForm .
    ?dativeMasculineSingularForm ontolex:representation ?dativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimateSingularForm .
    ?dativeMasculineInanimateSingularForm ontolex:representation ?dativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimatePluralForm .
    ?dativeMasculineInanimatePluralForm ontolex:representation ?dativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineAnimateSingularForm .
    ?dativeMasculineAnimateSingularForm ontolex:representation ?dativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineAnimatePluralForm .
    ?dativeMasculineAnimatePluralForm ontolex:representation ?dativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterSingularForm .
    ?dativeNeuterSingularForm ontolex:representation ?dativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterPluralForm .
    ?dativeNeuterPluralForm ontolex:representation ?dativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineSingularForm .
    ?accusativeFeminineSingularForm ontolex:representation ?accusativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFemininePluralForm .
    ?accusativeFemininePluralForm ontolex:representation ?accusativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineInanimateSingularForm .
    ?accusativeMasculineInanimateSingularForm ontolex:representation ?accusativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineInanimatePluralForm .
    ?accusativeMasculineInanimatePluralForm ontolex:representation ?accusativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineAnimateSingularForm .
    ?accusativeMasculineAnimateSingularForm ontolex:representation ?accusativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineAnimatePluralForm .
    ?accusativeMasculineAnimatePluralForm ontolex:representation ?accusativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterSingularForm .
    ?accusativeNeuterSingularForm ontolex:representation ?accusativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPluralForm .
    ?accusativeNeuterPluralForm ontolex:representation ?accusativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularForm .
    ?instrumentalFeminineSingularForm ontolex:representation ?instrumentalFeminineSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFemininePluralForm .
    ?instrumentalFemininePluralForm ontolex:representation ?instrumentalFemininePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineSingularForm .
    ?instrumentalMasculineSingularForm ontolex:representation ?instrumentalMasculineSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineInanimateSingularForm .
    ?instrumentalMasculineInanimateSingularForm ontolex:representation ?instrumentalMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineInanimatePluralForm .
    ?instrumentalMasculineInanimatePluralForm ontolex:representation ?instrumentalMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineAnimateSingularForm .
    ?instrumentalMasculineAnimateSingularForm ontolex:representation ?instrumentalMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineAnimatePluralForm .
    ?instrumentalMasculineAnimatePluralForm ontolex:representation ?instrumentalMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalNeuterSingularForm .
    ?instrumentalNeuterSingularForm ontolex:representation ?instrumentalNeuterSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalNeuterPluralForm .
    ?instrumentalNeuterPluralForm ontolex:representation ?instrumentalNeuterPlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineSingularForm .
    ?locativeMasculineSingularForm ontolex:representation ?locativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineInanimateSingularForm .
    ?locativeMasculineInanimateSingularForm ontolex:representation ?locativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineInanimatePluralForm .
    ?locativeMasculineInanimatePluralForm ontolex:representation ?locativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineAnimateSingularForm .
    ?locativeMasculineAnimateSingularForm ontolex:representation ?locativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineAnimatePluralForm .
    ?locativeMasculineAnimatePluralForm ontolex:representation ?locativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularForm .
    ?locativeNeuterSingularForm ontolex:representation ?locativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralForm .
    ?locativeNeuterPluralForm ontolex:representation ?locativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFeminineSingularForm .
    ?vocativeFeminineSingularForm ontolex:representation ?vocativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFemininePluralForm .
    ?vocativeFemininePluralForm ontolex:representation ?vocativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineSingularForm .
    ?vocativeMasculineSingularForm ontolex:representation ?vocativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularForm .
    ?vocativeMasculineInanimateSingularForm ontolex:representation ?vocativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralForm .
    ?vocativeMasculineInanimatePluralForm ontolex:representation ?vocativeMasculineInanimatePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularForm .
    ?vocativeMasculineAnimateSingularForm ontolex:representation ?vocativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimatePluralForm .
    ?vocativeMasculineAnimatePluralForm ontolex:representation ?vocativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularForm .
    ?vocativeNeuterSingularForm ontolex:representation ?vocativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterPluralForm .
    ?vocativeNeuterPluralForm ontolex:representation ?vocativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFeminineSingularPositiveForm .
    ?nominativeFeminineSingularPositiveForm ontolex:representation ?nominativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFemininePluralPositiveForm .
    ?nominativeFemininePluralPositiveForm ontolex:representation ?nominativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimateSingularPositiveForm .
    ?nominativeMasculineInanimateSingularPositiveForm ontolex:representation ?nominativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimatePluralPositiveForm .
    ?nominativeMasculineInanimatePluralPositiveForm ontolex:representation ?nominativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularPositiveForm .
    ?nominativeMasculineAnimateSingularPositiveForm ontolex:representation ?nominativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralPositiveForm .
    ?nominativeMasculineAnimatePluralPositiveForm ontolex:representation ?nominativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularPositiveForm .
    ?nominativeNeuterSingularPositiveForm ontolex:representation ?nominativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPluralPositiveForm .
    ?nominativeNeuterPluralPositiveForm ontolex:representation ?nominativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularPositiveForm .
    ?genitiveFeminineSingularPositiveForm ontolex:representation ?genitiveFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePluralPositiveForm .
    ?genitiveFemininePluralPositiveForm ontolex:representation ?genitiveFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineInanimateSingularPositiveForm .
    ?genitiveMasculineInanimateSingularPositiveForm ontolex:representation ?genitiveMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineInanimatePluralPositiveForm .
    ?genitiveMasculineInanimatePluralPositiveForm ontolex:representation ?genitiveMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineAnimateSingularPositiveForm .
    ?genitiveMasculineAnimateSingularPositiveForm ontolex:representation ?genitiveMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineAnimatePluralPositiveForm .
    ?genitiveMasculineAnimatePluralPositiveForm ontolex:representation ?genitiveMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterSingularPositiveForm .
    ?genitiveNeuterSingularPositiveForm ontolex:representation ?genitiveNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPluralPositiveForm .
    ?genitiveNeuterPluralPositiveForm ontolex:representation ?genitiveNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularPositiveForm .
    ?dativeFeminineSingularPositiveForm ontolex:representation ?dativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePluralPositiveForm .
    ?dativeFemininePluralPositiveForm ontolex:representation ?dativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimateSingularPositiveForm .
    ?dativeMasculineInanimateSingularPositiveForm ontolex:representation ?dativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineInanimatePluralPositiveForm .
    ?dativeMasculineInanimatePluralPositiveForm ontolex:representation ?dativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineAnimateSingularPositiveForm .
    ?dativeMasculineAnimateSingularPositiveForm ontolex:representation ?dativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeMasculineAnimatePluralPositiveForm .
    ?dativeMasculineAnimatePluralPositiveForm ontolex:representation ?dativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterSingularPositiveForm .
    ?dativeNeuterSingularPositiveForm ontolex:representation ?dativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeNeuterPluralPositiveForm .
    ?dativeNeuterPluralPositiveForm ontolex:representation ?dativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineSingularPositiveForm .
    ?accusativeFeminineSingularPositiveForm ontolex:representation ?accusativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFemininePluralPositiveForm .
    ?accusativeFemininePluralPositiveForm ontolex:representation ?accusativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineInanimateSingularPositiveForm .
    ?accusativeMasculineInanimateSingularPositiveForm ontolex:representation ?accusativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineInanimatePluralPositiveForm .
    ?accusativeMasculineInanimatePluralPositiveForm ontolex:representation ?accusativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineAnimateSingularPositiveForm .
    ?accusativeMasculineAnimateSingularPositiveForm ontolex:representation ?accusativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineAnimatePluralPositiveForm .
    ?accusativeMasculineAnimatePluralPositiveForm ontolex:representation ?accusativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterSingularPositiveForm .
    ?accusativeNeuterSingularPositiveForm ontolex:representation ?accusativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPluralPositiveForm .
    ?accusativeNeuterPluralPositiveForm ontolex:representation ?accusativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularPositiveForm .
    ?instrumentalFeminineSingularPositiveForm ontolex:representation ?instrumentalFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFemininePluralPositiveForm .
    ?instrumentalFemininePluralPositiveForm ontolex:representation ?instrumentalFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineInanimateSingularPositiveForm .
    ?instrumentalMasculineInanimateSingularPositiveForm ontolex:representation ?instrumentalMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineInanimatePluralPositiveForm .
    ?instrumentalMasculineInanimatePluralPositiveForm ontolex:representation ?instrumentalMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineAnimateSingularPositiveForm .
    ?instrumentalMasculineAnimateSingularPositiveForm ontolex:representation ?instrumentalMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineAnimatePluralPositiveForm .
    ?instrumentalMasculineAnimatePluralPositiveForm ontolex:representation ?instrumentalMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalNeuterSingularPositiveForm .
    ?instrumentalNeuterSingularPositiveForm ontolex:representation ?instrumentalNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalNeuterPluralPositiveForm .
    ?instrumentalNeuterPluralPositiveForm ontolex:representation ?instrumentalNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularPositiveForm .
    ?locativeFeminineSingularPositiveForm ontolex:representation ?locativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralPositiveForm .
    ?locativeFemininePluralPositiveForm ontolex:representation ?locativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineInanimateSingularPositiveForm .
    ?locativeMasculineInanimateSingularPositiveForm ontolex:representation ?locativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineInanimatePluralPositiveForm .
    ?locativeMasculineInanimatePluralPositiveForm ontolex:representation ?locativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineAnimateSingularPositiveForm .
    ?locativeMasculineAnimateSingularPositiveForm ontolex:representation ?locativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineAnimatePluralPositiveForm .
    ?locativeMasculineAnimatePluralPositiveForm ontolex:representation ?locativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularPositiveForm .
    ?locativeNeuterSingularPositiveForm ontolex:representation ?locativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralPositiveForm .
    ?locativeNeuterPluralPositiveForm ontolex:representation ?locativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFeminineSingularPositiveForm .
    ?vocativeFeminineSingularPositiveForm ontolex:representation ?vocativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFemininePluralPositiveForm .
    ?vocativeFemininePluralPositiveForm ontolex:representation ?vocativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimateSingularPositiveForm .
    ?vocativeMasculineInanimateSingularPositiveForm ontolex:representation ?vocativeMasculineInanimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineInanimatePluralPositiveForm .
    ?vocativeMasculineInanimatePluralPositiveForm ontolex:representation ?vocativeMasculineInanimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q52943434, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularPositiveForm .
    ?vocativeMasculineAnimateSingularPositiveForm ontolex:representation ?vocativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimatePluralPositiveForm .
    ?vocativeMasculineAnimatePluralPositiveForm ontolex:representation ?vocativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularPositiveForm .
    ?vocativeNeuterSingularPositiveForm ontolex:representation ?vocativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterPluralPositiveForm .
    ?vocativeNeuterPluralPositiveForm ontolex:representation ?vocativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }
}
