# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?dative
  ?dativePluralFeminine
  ?dativePluralMasculineInanimate
  ?dativePluralMasculineAnimate
  ?dativePluralNeuter
  ?dativePluralPositiveMasculineAnimate

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeForm .
    ?dativeForm ontolex:representation ?dative ;
      wikibase:grammaticalFeature wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralFeminineForm .
    ?dativePluralFeminineForm ontolex:representation ?dativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralMasculineInanimateForm .
    ?dativePluralMasculineInanimateForm ontolex:representation ?dativePluralMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralMasculineAnimateForm .
    ?dativePluralMasculineAnimateForm ontolex:representation ?dativePluralMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralNeuterForm .
    ?dativePluralNeuterForm ontolex:representation ?dativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralPositiveMasculineAnimateForm .
    ?dativePluralPositiveMasculineAnimateForm ontolex:representation ?dativePluralPositiveMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q3482678, wd:Q54020116 .
  }
}
