# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?dativeFeminineSingular
  ?dativeFemininePlural
  ?dativeFeminineSingularPositive
  ?dativeFemininePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularForm .
    ?dativeFeminineSingularForm ontolex:representation ?dativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePluralForm .
    ?dativeFemininePluralForm ontolex:representation ?dativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineSingularPositiveForm .
    ?dativeFeminineSingularPositiveForm ontolex:representation ?dativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePluralPositiveForm .
    ?dativeFemininePluralPositiveForm ontolex:representation ?dativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }
}
