# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?accusative
  ?accusativePluralFeminine
  ?accusativePluralMasculineInanimate
  ?accusativePluralMasculineAnimate
  ?accusativePluralNeuter

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralFeminineForm .
    ?accusativePluralFeminineForm ontolex:representation ?accusativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineInanimateForm .
    ?accusativePluralMasculineInanimateForm ontolex:representation ?accusativePluralMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineAnimateForm .
    ?accusativePluralMasculineAnimateForm ontolex:representation ?accusativePluralMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralNeuterForm .
    ?accusativePluralNeuterForm ontolex:representation ?accusativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775461 .
  }
}
