# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?locativeFeminineSingular
  ?locativeFemininePlural
  ?locativeFeminineSingularPositive
  ?locativeFemininePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularPositiveForm .
    ?locativeFeminineSingularPositiveForm ontolex:representation ?locativeFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralPositiveForm .
    ?locativeFemininePluralPositiveForm ontolex:representation ?locativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }
}
