# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?instrumental
  ?locative
  ?singularVocativeFeminine
  ?singularVocativeNeuter

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalForm .
    ?instrumentalForm ontolex:representation ?instrumental ;
      wikibase:grammaticalFeature wd:Q192997 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeForm .
    ?locativeForm ontolex:representation ?locative ;
      wikibase:grammaticalFeature wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeFeminineForm .
    ?singularVocativeFeminineForm ontolex:representation ?singularVocativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeNeuterForm .
    ?singularVocativeNeuterForm ontolex:representation ?singularVocativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q1775461 .
  }
}
