# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?singularLocative
  ?singularLocativeFeminine
  ?singularLocativeMasculineInanimate
  ?singularLocativeMasculineAnimate
  ?singularLocativeNeuter

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeForm .
    ?singularLocativeForm ontolex:representation ?singularLocative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeFeminineForm .
    ?singularLocativeFeminineForm ontolex:representation ?singularLocativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeMasculineInanimateForm .
    ?singularLocativeMasculineInanimateForm ontolex:representation ?singularLocativeMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeMasculineAnimateForm .
    ?singularLocativeMasculineAnimateForm ontolex:representation ?singularLocativeMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeNeuterForm .
    ?singularLocativeNeuterForm ontolex:representation ?singularLocativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775461 .
  }
}
