# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?singularDative
  ?singularDativeFeminine
  ?singularDativeMasculineInanimate
  ?singularDativeMasculineAnimate
  ?singularDativeNeuter

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeForm .
    ?singularDativeForm ontolex:representation ?singularDative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeFeminineForm .
    ?singularDativeFeminineForm ontolex:representation ?singularDativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeMasculineInanimateForm .
    ?singularDativeMasculineInanimateForm ontolex:representation ?singularDativeMasculineInanimate ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q52943434 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeMasculineAnimateForm .
    ?singularDativeMasculineAnimateForm ontolex:representation ?singularDativeMasculineAnimate ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q54020116 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeNeuterForm .
    ?singularDativeNeuterForm ontolex:representation ?singularDativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775461 .
  }
}
