# tool: scribe-data
# All Estonian (Q9072) adjectives in the given cases.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adeSingular
  ?adePlural
  ?ablSingular
  ?ablPlural
  ?transSingular
  ?transPlural
  ?termSingular
  ?termPlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective .

  # MARK: Adessive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adeSingularForm .
    ?adeSingularForm ontolex:representation ?adeSingular ;
      wikibase:grammaticalFeature wd:Q281954 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adePluralForm .
    ?adePluralForm ontolex:representation ?adePlural ;
      wikibase:grammaticalFeature wd:Q281954 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Ablative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablSingularForm .
    ?ablSingularForm ontolex:representation ?ablSingular ;
      wikibase:grammaticalFeature wd:Q156986 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablPluralForm .
    ?ablPluralForm ontolex:representation ?ablPlural ;
      wikibase:grammaticalFeature wd:Q156986 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Translative


  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?transSingularForm .
    ?transSingularForm ontolex:representation ?transSingular ;
      wikibase:grammaticalFeature wd:Q950170 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?transPluralForm .
    ?transPluralForm ontolex:representation ?transPlural ;
      wikibase:grammaticalFeature wd:Q950170 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Terminative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?termSingularForm .
    ?termSingularForm ontolex:representation ?termSingular ;
      wikibase:grammaticalFeature wd:Q747019 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?termPluralForm .
    ?termPluralForm ontolex:representation ?termPlural ;
      wikibase:grammaticalFeature wd:Q747019 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .
}
