# tool: scribe-data
# All Estonian (Q9072) adjectives in the given cases.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjective
  ?illSingular
  ?illPlural
  ?ineSingular
  ?inePlural
  ?eleSingular
  ?elePlural
  ?allSingular
  ?allPlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective .

  # MARK: Illative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illSingularForm .
    ?illSingularForm ontolex:representation ?illSingular ;
      wikibase:grammaticalFeature wd:Q474668 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illPluralForm .
    ?illPluralForm ontolex:representation ?illPlural ;
      wikibase:grammaticalFeature wd:Q474668 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Inessive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ineSingularForm .
    ?ineSingularForm ontolex:representation ?ineSingular ;
      wikibase:grammaticalFeature wd:Q282031 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inePluralForm .
    ?inePluralForm ontolex:representation ?inePlural ;
      wikibase:grammaticalFeature wd:Q282031 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Elative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elaSingularForm .
    ?elaSingularForm ontolex:representation ?elaSingular ;
      wikibase:grammaticalFeature wd:Q394253 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elaPluralForm .
    ?elaPluralForm ontolex:representation ?elaPlural ;
      wikibase:grammaticalFeature wd:Q394253 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .

  # MARK: Allative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allSingularForm .
    ?allSingularForm ontolex:representation ?allSingular ;
      wikibase:grammaticalFeature wd:Q655020 ;
      wikibase:grammaticalFeature wd:Q110786 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allPluralForm .
    ?allPluralForm ontolex:representation ?allPlural ;
      wikibase:grammaticalFeature wd:Q655020 ;
      wikibase:grammaticalFeature wd:Q146786 .
  } .
}
