# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularGenitiveFemininePositive
  ?singularGenitiveMasculinePositive
  ?singularGenitiveNeuterPositive
  ?singularDativeFemininePositive
  ?singularDativeMasculinePositive
  ?singularDativeNeuterPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveFemininePositiveForm .
    ?singularGenitiveFemininePositiveForm ontolex:representation ?singularGenitiveFemininePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveMasculinePositiveForm .
    ?singularGenitiveMasculinePositiveForm ontolex:representation ?singularGenitiveMasculinePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveNeuterPositiveForm .
    ?singularGenitiveNeuterPositiveForm ontolex:representation ?singularGenitiveNeuterPositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775461, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeFemininePositiveForm .
    ?singularDativeFemininePositiveForm ontolex:representation ?singularDativeFemininePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeMasculinePositiveForm .
    ?singularDativeMasculinePositiveForm ontolex:representation ?singularDativeMasculinePositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeNeuterPositiveForm .
    ?singularDativeNeuterPositiveForm ontolex:representation ?singularDativeNeuterPositive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775461, wd:Q3482678 .
  }
}
