# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?genitiveMasculineSingular
  ?genitiveMasculinePlural
  ?genitiveMasculineSingularSuperlative
  ?genitiveMasculineSingularPositive
  ?genitiveMasculinePluralSuperlative
  ?genitiveMasculinePluralPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularForm .
    ?genitiveMasculineSingularForm ontolex:representation ?genitiveMasculineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculinePluralForm .
    ?genitiveMasculinePluralForm ontolex:representation ?genitiveMasculinePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularSuperlativeForm .
    ?genitiveMasculineSingularSuperlativeForm ontolex:representation ?genitiveMasculineSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculineSingularPositiveForm .
    ?genitiveMasculineSingularPositiveForm ontolex:representation ?genitiveMasculineSingularPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculinePluralSuperlativeForm .
    ?genitiveMasculinePluralSuperlativeForm ontolex:representation ?genitiveMasculinePluralSuperlative ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q146786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculinePluralPositiveForm .
    ?genitiveMasculinePluralPositiveForm ontolex:representation ?genitiveMasculinePluralPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q146786, wd:Q3482678 .
  }
}
