# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?pluralAblativePositive
  ?pluralVocativeFemininePositive
  ?pluralVocativeMasculinePositive
  ?pluralVocativeNeuterPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativePositiveForm .
    ?pluralAblativePositiveForm ontolex:representation ?pluralAblativePositive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralVocativeFemininePositiveForm .
    ?pluralVocativeFemininePositiveForm ontolex:representation ?pluralVocativeFemininePositive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q185077, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralVocativeMasculinePositiveForm .
    ?pluralVocativeMasculinePositiveForm ontolex:representation ?pluralVocativeMasculinePositive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q185077, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralVocativeNeuterPositiveForm .
    ?pluralVocativeNeuterPositiveForm ontolex:representation ?pluralVocativeNeuterPositive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q185077, wd:Q1775461, wd:Q3482678 .
  }
}
