# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativeNeuterSingular
  ?nominativeNeuterSingularComparative
  ?nominativeNeuterSingularSuperlative
  ?nominativeNeuterSingularPositive
  ?nominativeNeuterPluralComparative
  ?nominativeNeuterPluralPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularForm .
    ?nominativeNeuterSingularForm ontolex:representation ?nominativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularComparativeForm .
    ?nominativeNeuterSingularComparativeForm ontolex:representation ?nominativeNeuterSingularComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularSuperlativeForm .
    ?nominativeNeuterSingularSuperlativeForm ontolex:representation ?nominativeNeuterSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterSingularPositiveForm .
    ?nominativeNeuterSingularPositiveForm ontolex:representation ?nominativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPluralComparativeForm .
    ?nominativeNeuterPluralComparativeForm ontolex:representation ?nominativeNeuterPluralComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q146786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPluralPositiveForm .
    ?nominativeNeuterPluralPositiveForm ontolex:representation ?nominativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }
}
