# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?dativePlural
  ?dativePluralComparative
  ?dativePluralSuperlative
  ?dativePluralPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralComparativeForm .
    ?dativePluralComparativeForm ontolex:representation ?dativePluralComparative ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralSuperlativeForm .
    ?dativePluralSuperlativeForm ontolex:representation ?dativePluralSuperlative ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralPositiveForm .
    ?dativePluralPositiveForm ontolex:representation ?dativePluralPositive ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786, wd:Q3482678 .
  }
}
