# tool: scribe-data
# All Latin (Q397) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativePluralFemininePositive
  ?nominativePluralMasculinePositive
  ?nominativePluralNeuterPositive
  ?genitivePluralFemininePositive
  ?genitivePluralMasculinePositive
  ?genitivePluralNeuterPositive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralFemininePositiveForm .
    ?nominativePluralFemininePositiveForm ontolex:representation ?nominativePluralFemininePositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralMasculinePositiveForm .
    ?nominativePluralMasculinePositiveForm ontolex:representation ?nominativePluralMasculinePositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralNeuterPositiveForm .
    ?nominativePluralNeuterPositiveForm ontolex:representation ?nominativePluralNeuterPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775461, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralFemininePositiveForm .
    ?genitivePluralFemininePositiveForm ontolex:representation ?genitivePluralFemininePositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775415, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralMasculinePositiveForm .
    ?genitivePluralMasculinePositiveForm ontolex:representation ?genitivePluralMasculinePositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q499327, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralNeuterPositiveForm .
    ?genitivePluralNeuterPositiveForm ontolex:representation ?genitivePluralNeuterPositive ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775461, wd:Q3482678 .
  }
}
