# tool: scribe-data
# All Italian (Q652) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineSingularCombinedPastParticiple
  ?masculinePluralCombinedPastParticiple
  ?masculineSingularParticipleCombinedPastParticiple
  ?masculinePluralParticipleCombinedPastParticiple

WHERE {
  ?lexeme dct:language wd:Q652 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularCombinedPastParticipleForm .
    ?masculineSingularCombinedPastParticipleForm ontolex:representation ?masculineSingularCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralCombinedPastParticipleForm .
    ?masculinePluralCombinedPastParticipleForm ontolex:representation ?masculinePluralCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularParticipleCombinedPastParticipleForm .
    ?masculineSingularParticipleCombinedPastParticipleForm ontolex:representation ?masculineSingularParticipleCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786, wd:Q814722, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralParticipleCombinedPastParticipleForm .
    ?masculinePluralParticipleCombinedPastParticipleForm ontolex:representation ?masculinePluralParticipleCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q814722, wd:Q12717679 .
  }
}
