# tool: scribe-data
# All Italian (Q652) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?infinitive
  ?infinitivePresent
  ?infinitivePresentInfinitive

WHERE {
  ?lexeme dct:language wd:Q652 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveForm .
    ?infinitiveForm ontolex:representation ?infinitive ;
      wikibase:grammaticalFeature wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePresentForm .
    ?infinitivePresentForm ontolex:representation ?infinitivePresent ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePresentInfinitiveForm .
    ?infinitivePresentInfinitiveForm ontolex:representation ?infinitivePresentInfinitive ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q52434245 .
  }
}
