# tool: scribe-data
# All Hebrew (Q9288) adjectives.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lemma
WHERE {
  ?lexeme dct:language wd:Q9288 ;  # Hebrew language
          wikibase:lexicalCategory wd:Q34698 ;  # Adjective
          wikibase:lemma ?lemma .

}
