# tool: scribe-data
# All Punjabi (Q58635) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?direct
  ?directFirstPersonSingular
  ?directSecondPersonPlural

WHERE {
  ?lexeme dct:language wd:Q58635 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .

  # Note: We need to filter for pa to remove gurmukhi (pa) words.
  FILTER(lang(?personalpronoun) = "pa")

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directForm .
    ?directForm ontolex:representation ?direct ;
      wikibase:grammaticalFeature wd:Q1751855 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directFirstPersonSingularForm .
    ?directFirstPersonSingularForm ontolex:representation ?directFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directSecondPersonPluralForm .
    ?directSecondPersonPluralForm ontolex:representation ?directSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q51929049, wd:Q146786 .
  }
}
