# tool: scribe-data
# All Latin (Q397) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?locativeSingular
  ?locativeFeminineSingular
  ?locativeFemininePlural
  ?locativeMasculineSingular
  ?locativeMasculinePlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFeminineSingularForm .
    ?locativeFeminineSingularForm ontolex:representation ?locativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeFemininePluralForm .
    ?locativeFemininePluralForm ontolex:representation ?locativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineSingularForm .
    ?locativeMasculineSingularForm ontolex:representation ?locativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculinePluralForm .
    ?locativeMasculinePluralForm ontolex:representation ?locativeMasculinePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q146786 .
  }
}
