# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?vocativeNeuterSingular
  ?vocativeNeuterPlural
  ?vocativeNeuterSingularComparative
  ?vocativeNeuterSingularSuperlative
  ?vocativeNeuterSingularPositive
  ?vocativeNeuterPluralComparative

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularForm .
    ?vocativeNeuterSingularForm ontolex:representation ?vocativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterPluralForm .
    ?vocativeNeuterPluralForm ontolex:representation ?vocativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularComparativeForm .
    ?vocativeNeuterSingularComparativeForm ontolex:representation ?vocativeNeuterSingularComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularSuperlativeForm .
    ?vocativeNeuterSingularSuperlativeForm ontolex:representation ?vocativeNeuterSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterSingularPositiveForm .
    ?vocativeNeuterSingularPositiveForm ontolex:representation ?vocativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeNeuterPluralComparativeForm .
    ?vocativeNeuterPluralComparativeForm ontolex:representation ?vocativeNeuterPluralComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775461, wd:Q146786, wd:Q14169499 .
  }
}
