# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativeMasculineAnimateSingular
  ?nominativeMasculineAnimatePlural
  ?nominativeMasculineAnimateSingularSuperlative
  ?nominativeMasculineAnimateSingularPositive
  ?nominativeMasculineAnimatePluralComparative
  ?nominativeMasculineAnimatePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularForm .
    ?nominativeMasculineAnimateSingularForm ontolex:representation ?nominativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralForm .
    ?nominativeMasculineAnimatePluralForm ontolex:representation ?nominativeMasculineAnimatePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularSuperlativeForm .
    ?nominativeMasculineAnimateSingularSuperlativeForm ontolex:representation ?nominativeMasculineAnimateSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularPositiveForm .
    ?nominativeMasculineAnimateSingularPositiveForm ontolex:representation ?nominativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralComparativeForm .
    ?nominativeMasculineAnimatePluralComparativeForm ontolex:representation ?nominativeMasculineAnimatePluralComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralPositiveForm .
    ?nominativeMasculineAnimatePluralPositiveForm ontolex:representation ?nominativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }
}
