# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativeMasculineInanimateSingular
  ?nominativeFeminineSingularComparative
  ?nominativeFemininePluralPositive
  ?nominativeMasculineInanimateSingularComparative
  ?nominativeMasculineAnimateSingularComparative
  ?nominativeMasculineAnimatePluralSuperlative

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimateSingularForm .
    ?nominativeMasculineInanimateSingularForm ontolex:representation ?nominativeMasculineInanimateSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFeminineSingularComparativeForm .
    ?nominativeFeminineSingularComparativeForm ontolex:representation ?nominativeFeminineSingularComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFemininePluralPositiveForm .
    ?nominativeFemininePluralPositiveForm ontolex:representation ?nominativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineInanimateSingularComparativeForm .
    ?nominativeMasculineInanimateSingularComparativeForm ontolex:representation ?nominativeMasculineInanimateSingularComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q52943434, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimateSingularComparativeForm .
    ?nominativeMasculineAnimateSingularComparativeForm ontolex:representation ?nominativeMasculineAnimateSingularComparative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineAnimatePluralSuperlativeForm .
    ?nominativeMasculineAnimatePluralSuperlativeForm ontolex:representation ?nominativeMasculineAnimatePluralSuperlative ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q54020116, wd:Q146786, wd:Q1817208 .
  }
}
