# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?instrumentalMasculineSingular
  ?instrumentalMasculinePlural
  ?vocativeFeminineSingular
  ?vocativeFemininePluralPositive
  ?vocativeMasculineAnimateSingularComparative
  ?vocativeMasculineAnimatePluralComparative

WHERE {
  ?lexeme dct:language wd:Q9056 ;
      wikibase:lexicalCategory wd:Q34698 ;
      wikibase:lemma ?adjective ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineSingularForm .
    ?instrumentalMasculineSingularForm ontolex:representation ?instrumentalMasculineSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculinePluralForm .
    ?instrumentalMasculinePluralForm ontolex:representation ?instrumentalMasculinePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFeminineSingularForm .
    ?vocativeFeminineSingularForm ontolex:representation ?vocativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeFemininePluralPositiveForm .
    ?vocativeFemininePluralPositiveForm ontolex:representation ?vocativeFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularComparativeForm .
    ?vocativeMasculineAnimateSingularComparativeForm ontolex:representation ?vocativeMasculineAnimateSingularComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimatePluralComparativeForm .
    ?vocativeMasculineAnimatePluralComparativeForm ontolex:representation ?vocativeMasculineAnimatePluralComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q146786, wd:Q14169499 .
  }
}
