# tool: scribe-data
# All Arabic (Q13955) adjectives, their plurals and their dual forms.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjective
  ?plural
  ?dual

WHERE {
  ?lexeme dct:language wd:Q13955 ;            # Arabic language
    wikibase:lexicalCategory wd:Q34698;        # Adjectives
    wikibase:lemma ?lemma .

  # Indefinite Dual Form
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dualForm .
    ?dualForm ontolex:representation ?dual ;
      wikibase:grammaticalFeature wd:Q110022 ;
  }

  # Indefinite Plural Form
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 ;
  }

  # Retrieve labels for display
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]" .
    ?lemma rdfs:label ?adjective .
  }
}
