# tool: scribe-data
# All Hebrew (Q9288) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?futureFirstPersonSingular
  ?futureFirstPersonPlural

  ?feminineFutureSecondPersonSingular
  ?feminineFutureSecondPersonPlural
  ?feminineFutureThirdPersonSingular
  ?feminineFutureThirdPersonPlural

  ?masculineFutureSecondPersonSingular
  ?masculineFutureSecondPersonPlural
  ?masculineFutureThirdPersonSingular
  ?masculineFutureThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q9288 ;
    wikibase:lexicalCategory wd:Q24905 .

  # MARK: Future

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonSingularForm .
    ?futureFirstPersonSingularForm ontolex:representation ?futureFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q110786 .
    FILTER(lang(?futureFirstPersonSingular) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?futureFirstPersonPluralForm .
    ?futureFirstPersonPluralForm ontolex:representation ?futureFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q501405, wd:Q21714344, wd:Q146786 .
      FILTER(lang(?futureFirstPersonPlural) = "he") .
  }

  # Feminine

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureSecondPersonSingularForm .
    ?feminineFutureSecondPersonSingularForm ontolex:representation ?feminineFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929049, wd:Q110786 .
      FILTER(lang(?feminineFutureSecondPersonSingular) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureSecondPersonPluralForm .
    ?feminineFutureSecondPersonPluralForm ontolex:representation ?feminineFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929049, wd:Q146786 .
      FILTER(lang(?feminineFutureSecondPersonPlural) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureThirdPersonSingularForm .
    ?feminineFutureThirdPersonSingularForm ontolex:representation ?feminineFutureThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929074, wd:Q110786 .
      FILTER(lang(?feminineFutureThirdPersonSingular) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineFutureThirdPersonPluralForm .
    ?feminineFutureThirdPersonPluralForm ontolex:representation ?feminineFutureThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q501405, wd:Q51929074, wd:Q146786 .
      FILTER(lang(?feminineFutureThirdPersonPlural) = "he") .
  }

  # Masculine

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureSecondPersonSingularForm .
    ?masculineFutureSecondPersonSingularForm ontolex:representation ?masculineFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929049, wd:Q110786 .
      FILTER(lang(?masculineFutureSecondPersonSingular) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureSecondPersonPluralForm .
    ?masculineFutureSecondPersonPluralForm ontolex:representation ?masculineFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929049, wd:Q146786 .
      FILTER(lang(?masculineFutureSecondPersonPlural) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureThirdPersonSingularForm .
    ?masculineFutureThirdPersonSingularForm ontolex:representation ?masculineFutureThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929074, wd:Q110786 .
      FILTER(lang(?masculineFutureThirdPersonSingular) = "he") .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureThirdPersonPluralForm .
    ?masculineFutureThirdPersonPluralForm ontolex:representation ?masculineFutureThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929074, wd:Q146786 .
      FILTER(lang(?masculineFutureThirdPersonPlural) = "he") .
  }
}
