# tool: scribe-data
# All Norwegian (Q25164) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?infinitivePassive
  ?infinitiveActiveAInfinitive
  ?infinitiveActiveEInfinitive

WHERE {
  ?lexeme dct:language wd:Q25164 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for nn to remove nynorsk (nn) words.
  FILTER(lang(?verb) = "nn")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitivePassiveForm .
    ?infinitivePassiveForm ontolex:representation ?infinitivePassive ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1194697 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveActiveAInfinitiveForm .
    ?infinitiveActiveAInfinitiveForm ontolex:representation ?infinitiveActiveAInfinitive ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1317831, wd:Q115223950 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveActiveEInfinitiveForm .
    ?infinitiveActiveEInfinitiveForm ontolex:representation ?infinitiveActiveEInfinitive ;
      wikibase:grammaticalFeature wd:Q179230, wd:Q1317831, wd:Q115223951 .
  }
}
