# ATTN: WIP
engine: ast_trans_top
lang_header_pattern: \(\{\{lengua\|es\}\}\)
translations_header: Traducciones
prefilters:
- trad-arriba
- '{{t'
- '{{T'
ignored_prefixes:
- 'ver:'
ignored_strings:
- please add this translation if you can
- script needed
- '[script needed]'
- literally
- lit.
- e.g.
- cf.
- different structure used
- no equivalent
- not used
- not attested
pos_map:
  adj: adjective
  adv: adverb
  prep: preposition
  conj: conjunction
  intj: interjection
  pron: pronoun
  det: determiner
  num: numeral
  proper noun: proper_noun
  proper name: proper_noun
  name: proper_noun
  sustantivo masculino: noun
  sustantivo feminino: noun
template_top:
- trad-arriba
template_bottom: trad-abajo
template_translation:
- t
- t+
- t-check
- tt
- tt+
