engine: ast_trans_top
# idwiktionary uses "=={{bahasa|id}}==" headers
lang_header_pattern: \{\{bahasa\|id\}\}
translations_header: terjemahan
prefilters:
- t-atas
- trans-top
- '{{t|'
- '{{t+'
ignored_prefixes:
- 'lihat '
- 'lihat:'
ignored_strings:
- perlu ditambahkan
- belum ada
pos_map:
  adj: adjective
  adv: adverb
  prep: preposition
  conj: conjunction
  interj: interjection
  pron: pronoun
  num: numeral
  nomina: noun
  verba: verb
  -n-: noun
  -v-: verb
  -adj-: adjective
  -adv-: adverb
template_top:
- t-atas
- trans-top
- checktrans-top
template_bottom: t-bawah
template_translation:
- t
- t+
- t-check
