# tool: scribe-data
# All Danish (Q9035) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nonGenitiveIndefinitePlural

WHERE {
  ?lexeme dct:language wd:Q9035 ;
    wikibase:lexicalCategory wd:Q1084 .

  # MARK: Plural

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveIndefinitePluralForm .
    ?nonGenitiveIndefinitePluralForm ontolex:representation ?nonGenitiveIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q53997857, wd:Q146786 .
  }
}
