# tool: scribe-data
# All Danish (Q9035) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nonGenitiveDefiniteSingular

# MARK: Singular

WHERE {
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveDefiniteSingularForm .
    ?nonGenitiveDefiniteSingularForm ontolex:representation ?nonGenitiveDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q53997851, wd:Q110786 .
  }
}
