# tool: scribe-data
# All Danish (Q9035) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nonGenitiveIndefiniteSingular

WHERE {

  # MARK: Singular

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nonGenitiveIndefiniteSingularForm .
    ?nonGenitiveIndefiniteSingularForm ontolex:representation ?nonGenitiveIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q98946930, wd:Q53997857, wd:Q110786 .
  }
}
