# tool: scribe-data
# All Swedish (Q9027) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?singularNominativeIndefinite
  ?singularNominativeDefinite
  ?singularGenitiveIndefinite
  ?singularGenitiveDefinite

WHERE {
  ?lexeme dct:language wd:Q9027 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeIndefiniteForm .
    ?singularNominativeIndefiniteForm ontolex:representation ?singularNominativeIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeDefiniteForm .
    ?singularNominativeDefiniteForm ontolex:representation ?singularNominativeDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveIndefiniteForm .
    ?singularGenitiveIndefiniteForm ontolex:representation ?singularGenitiveIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveDefiniteForm .
    ?singularGenitiveDefiniteForm ontolex:representation ?singularGenitiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q53997851 .
  }
}
