# tool: scribe-data
# All Czech (Q9056) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineInanimatePastTransgressiveSingular
  ?masculineInanimatePastTransgressivePlural
  ?masculineAnimatePastTransgressiveSingular
  ?masculineAnimatePastTransgressivePlural
  ?neuterPastTransgressiveSingular
  ?neuterPastTransgressivePlural

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineInanimatePastTransgressiveSingularForm .
    ?masculineInanimatePastTransgressiveSingularForm ontolex:representation ?masculineInanimatePastTransgressiveSingular ;
      wikibase:grammaticalFeature wd:Q52943434, wd:Q12750232, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineInanimatePastTransgressivePluralForm .
    ?masculineInanimatePastTransgressivePluralForm ontolex:representation ?masculineInanimatePastTransgressivePlural ;
      wikibase:grammaticalFeature wd:Q52943434, wd:Q12750232, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimatePastTransgressiveSingularForm .
    ?masculineAnimatePastTransgressiveSingularForm ontolex:representation ?masculineAnimatePastTransgressiveSingular ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q12750232, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAnimatePastTransgressivePluralForm .
    ?masculineAnimatePastTransgressivePluralForm ontolex:representation ?masculineAnimatePastTransgressivePlural ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q12750232, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPastTransgressiveSingularForm .
    ?neuterPastTransgressiveSingularForm ontolex:representation ?neuterPastTransgressiveSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q12750232, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterPastTransgressivePluralForm .
    ?neuterPastTransgressivePluralForm ontolex:representation ?neuterPastTransgressivePlural ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q12750232, wd:Q146786 .
  }
}
