# tool: scribe-data
# All Czech (Q9056) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?femininePluralCombinedPastParticiple
  ?femininePluralPassiveParticiple
  ?femininePluralActiveParticiple
  ?imperativeFirstPersonPlural
  ?imperativeSecondPersonSingular
  ?imperativeSecondPersonPlural

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralCombinedPastParticipleForm .
    ?femininePluralCombinedPastParticipleForm ontolex:representation ?femininePluralCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralPassiveParticipleForm .
    ?femininePluralPassiveParticipleForm ontolex:representation ?femininePluralPassiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q72249544 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralActiveParticipleForm .
    ?femininePluralActiveParticipleForm ontolex:representation ?femininePluralActiveParticiple ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786, wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeFirstPersonPluralForm .
    ?imperativeFirstPersonPluralForm ontolex:representation ?imperativeFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeSecondPersonSingularForm .
    ?imperativeSecondPersonSingularForm ontolex:representation ?imperativeSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeSecondPersonPluralForm .
    ?imperativeSecondPersonPluralForm ontolex:representation ?imperativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q22716, wd:Q51929049, wd:Q146786 .
  }
}
