# tool: scribe-data
# All Malay (Q9237) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?activeParticiple
  ?adverbial
  ?phrase
  ?comparative
  ?superlative
  ?positive

WHERE {
  ?lexeme dct:language wd:Q9237 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeParticipleForm .
    ?activeParticipleForm ontolex:representation ?activeParticiple ;
      wikibase:grammaticalFeature wd:Q72249355 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbialForm .
    ?adverbialForm ontolex:representation ?adverbial ;
      wikibase:grammaticalFeature wd:Q380012 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?phraseForm .
    ?phraseForm ontolex:representation ?phrase ;
      wikibase:grammaticalFeature wd:Q187931 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comparativeForm .
    ?comparativeForm ontolex:representation ?comparative ;
      wikibase:grammaticalFeature wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeForm .
    ?superlativeForm ontolex:representation ?superlative ;
      wikibase:grammaticalFeature wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?positiveForm .
    ?positiveForm ontolex:representation ?positive ;
      wikibase:grammaticalFeature wd:Q3482678 .
  }
}
