# tool: scribe-data
# All Punjabi (Q58635) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?singularLocativeMasculine
  ?singularVocativeMasculine
  ?singularDirectFeminine
  ?singularObliqueFeminine
  ?singularAblativeMasculine

WHERE {
  ?lexeme dct:language wd:Q58635 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for pnb to remove shahmukhi (pnb) words.
  FILTER(lang(?propernoun) = "pnb")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeMasculineForm .
    ?singularLocativeMasculineForm ontolex:representation ?singularLocativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeMasculineForm .
    ?singularVocativeMasculineForm ontolex:representation ?singularVocativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDirectFeminineForm .
    ?singularDirectFeminineForm ontolex:representation ?singularDirectFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1751855, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueFeminineForm .
    ?singularObliqueFeminineForm ontolex:representation ?singularObliqueFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeMasculineForm .
    ?singularAblativeMasculineForm ontolex:representation ?singularAblativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986, wd:Q499327 .
  }
}
