# tool: scribe-data
# All Punjabi (Q58635) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularVocativeFeminine
  ?singularVocativeMasculine
  ?singularDirectFeminine
  ?singularMasculineDirect
  ?singularObliqueFeminine
  ?singularMasculineOblique

WHERE {
  ?lexeme dct:language wd:Q58635 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for pnb to remove shahmukhi (pnb) words.
  FILTER(lang(?adjective) = "pnb")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeFeminineForm .
    ?singularVocativeFeminineForm ontolex:representation ?singularVocativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeMasculineForm .
    ?singularVocativeMasculineForm ontolex:representation ?singularVocativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDirectFeminineForm .
    ?singularDirectFeminineForm ontolex:representation ?singularDirectFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1751855, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineDirectForm .
    ?singularMasculineDirectForm ontolex:representation ?singularMasculineDirect ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q1751855 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueFeminineForm .
    ?singularObliqueFeminineForm ontolex:representation ?singularObliqueFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineObliqueForm .
    ?singularMasculineObliqueForm ontolex:representation ?singularMasculineOblique ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q1233197 .
  }
}
