# tool: scribe-data
# All Punjabi (Q58635) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?superlative
  ?positive
  ?vocativeSingular
  ?instrumentalMasculineDualPositive

WHERE {
  ?lexeme dct:language wd:Q58635 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  # Note: We need to filter for pnb to remove shahmukhi (pnb) words.
  FILTER(lang(?adjective) = "pnb")

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?superlativeForm .
    ?superlativeForm ontolex:representation ?superlative ;
      wikibase:grammaticalFeature wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?positiveForm .
    ?positiveForm ontolex:representation ?positive ;
      wikibase:grammaticalFeature wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalMasculineDualPositiveForm .
    ?instrumentalMasculineDualPositiveForm ontolex:representation ?instrumentalMasculineDualPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q499327, wd:Q110022, wd:Q3482678 .
  }
}
