# tool: scribe-data
# All Finnish (Q1412) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?partitive
  ?comitative
  ?nominativeSingular
  ?genitiveSingular
  ?genitivePlural
  ?accusativeSingular
  ?accusativePlural
  ?ablativeSingular
  ?ablativePlural
  ?partitiveSingular
  ?partitivePlural
  ?illativeSingular
  ?illativePlural
  ?inessiveSingular
  ?inessivePlural
  ?elativeSingular
  ?elativePlural
  ?allativeSingular
  ?allativePlural
  ?adessiveSingular
  ?adessivePlural
  ?translativeSingular
  ?translativePlural
  ?essiveSingular
  ?essivePlural
  ?abessiveSingular
  ?abessivePlural
  ?comitativePlural

WHERE {
  ?lexeme dct:language wd:Q1412 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveForm .
    ?partitiveForm ontolex:representation ?partitive ;
      wikibase:grammaticalFeature wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeForm .
    ?comitativeForm ontolex:representation ?comitative ;
      wikibase:grammaticalFeature wd:Q838581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralForm .
    ?accusativePluralForm ontolex:representation ?accusativePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeSingularForm .
    ?ablativeSingularForm ontolex:representation ?ablativeSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativePluralForm .
    ?ablativePluralForm ontolex:representation ?ablativePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitivePluralForm .
    ?partitivePluralForm ontolex:representation ?partitivePlural ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativeSingularForm .
    ?illativeSingularForm ontolex:representation ?illativeSingular ;
      wikibase:grammaticalFeature wd:Q474668, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativePluralForm .
    ?illativePluralForm ontolex:representation ?illativePlural ;
      wikibase:grammaticalFeature wd:Q474668, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSingularForm .
    ?inessiveSingularForm ontolex:representation ?inessiveSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessivePluralForm .
    ?inessivePluralForm ontolex:representation ?inessivePlural ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSingularForm .
    ?elativeSingularForm ontolex:representation ?elativeSingular ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativePluralForm .
    ?elativePluralForm ontolex:representation ?elativePlural ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeSingularForm .
    ?allativeSingularForm ontolex:representation ?allativeSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativePluralForm .
    ?allativePluralForm ontolex:representation ?allativePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adessiveSingularForm .
    ?adessiveSingularForm ontolex:representation ?adessiveSingular ;
      wikibase:grammaticalFeature wd:Q281954, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adessivePluralForm .
    ?adessivePluralForm ontolex:representation ?adessivePlural ;
      wikibase:grammaticalFeature wd:Q281954, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativeSingularForm .
    ?translativeSingularForm ontolex:representation ?translativeSingular ;
      wikibase:grammaticalFeature wd:Q950170, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativePluralForm .
    ?translativePluralForm ontolex:representation ?translativePlural ;
      wikibase:grammaticalFeature wd:Q950170, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?essiveSingularForm .
    ?essiveSingularForm ontolex:representation ?essiveSingular ;
      wikibase:grammaticalFeature wd:Q148465, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?essivePluralForm .
    ?essivePluralForm ontolex:representation ?essivePlural ;
      wikibase:grammaticalFeature wd:Q148465, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessiveSingularForm .
    ?abessiveSingularForm ontolex:representation ?abessiveSingular ;
      wikibase:grammaticalFeature wd:Q319822, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessivePluralForm .
    ?abessivePluralForm ontolex:representation ?abessivePlural ;
      wikibase:grammaticalFeature wd:Q319822, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativePluralForm .
    ?comitativePluralForm ontolex:representation ?comitativePlural ;
      wikibase:grammaticalFeature wd:Q838581, wd:Q146786 .
  }
}
