# tool: scribe-data
# All esperanto (Q143) proper_nouns (Q147276) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?proper_nouns
    ?plural
  ?singularNominative
  ?singularAccusative
  ?accusativeSingular
    WHERE {
    ?lexeme dct:language wd:Q143 ;
        wikibase:lexicalCategory wd:Q147276 ;
        wikibase:lemma ?proper_nouns .
        FILTER(lang(?proper_nouns) = "eo")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNominativeForm .
            ?singularNominativeForm ontolex:representation ?singularNominative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAccusativeForm .
            ?singularAccusativeForm ontolex:representation ?singularAccusative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146078 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
            ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
                wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
        }
}