# tool: scribe-data
# All Arabic (Q13955) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?singularNominativeDefinite
  ?singularGenitiveDefinite
  ?singularAccusativeDefinite
  ?singularFemininePausal
  ?singularMasculinePausal
  ?singularDefinitePausal

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeDefiniteForm .
    ?singularNominativeDefiniteForm ontolex:representation ?singularNominativeDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveDefiniteForm .
    ?singularGenitiveDefiniteForm ontolex:representation ?singularGenitiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAccusativeDefiniteForm .
    ?singularAccusativeDefiniteForm ontolex:representation ?singularAccusativeDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146078, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFemininePausalForm .
    ?singularFemininePausalForm ontolex:representation ?singularFemininePausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculinePausalForm .
    ?singularMasculinePausalForm ontolex:representation ?singularMasculinePausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q117262361 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDefinitePausalForm .
    ?singularDefinitePausalForm ontolex:representation ?singularDefinitePausal ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q53997851, wd:Q117262361 .
  }
}
