# tool: scribe-data
# All Czech (Q9056) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?instrumentalFeminineSingular
  ?instrumentalFemininePlural
  ?instrumentalFeminineSingularPositive
  ?instrumentalFemininePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularForm .
    ?instrumentalFeminineSingularForm ontolex:representation ?instrumentalFeminineSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFemininePluralForm .
    ?instrumentalFemininePluralForm ontolex:representation ?instrumentalFemininePlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFeminineSingularPositiveForm .
    ?instrumentalFeminineSingularPositiveForm ontolex:representation ?instrumentalFeminineSingularPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalFemininePluralPositiveForm .
    ?instrumentalFemininePluralPositiveForm ontolex:representation ?instrumentalFemininePluralPositive ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q1775415, wd:Q146786, wd:Q3482678 .
  }
}
