# tool: scribe-data
# All Indonesian (Q9240) nouns.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?noun

WHERE {
  VALUES ?nounTypes {wd:Q1084 wd:Q147276} # Nouns and pronouns
  ?lexeme a ontolex:LexicalEntry ;
    dct:language wd:Q9240 ;
    wikibase:lexicalCategory ?nounType ;
    wikibase:lemma ?noun .

  FILTER(?nounType = ?nounTypes)
}
