# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?activePerformativeFirstPersonSingular
  ?activePerformativeFirstPersonPlural
  ?activePerformativeSecondPersonDual
  ?activeSecondPersonDualSubjunctive
  ?activeSecondPersonPluralFiilMudariSubjunctive
  ?activeSecondPersonDualFiilMudariSubjunctive

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePerformativeFirstPersonSingularForm .
    ?activePerformativeFirstPersonSingularForm ontolex:representation ?activePerformativeFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePerformativeFirstPersonPluralForm .
    ?activePerformativeFirstPersonPluralForm ontolex:representation ?activePerformativeFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePerformativeSecondPersonDualForm .
    ?activePerformativeSecondPersonDualForm ontolex:representation ?activePerformativeSecondPersonDual ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeSecondPersonDualSubjunctiveForm .
    ?activeSecondPersonDualSubjunctiveForm ontolex:representation ?activeSecondPersonDualSubjunctive ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q51929049, wd:Q110022, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeSecondPersonPluralFiilMudariSubjunctiveForm .
    ?activeSecondPersonPluralFiilMudariSubjunctiveForm ontolex:representation ?activeSecondPersonPluralFiilMudariSubjunctive ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q51929049, wd:Q146786, wd:Q12230930, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeSecondPersonDualFiilMudariSubjunctiveForm .
    ?activeSecondPersonDualFiilMudariSubjunctiveForm ontolex:representation ?activeSecondPersonDualFiilMudariSubjunctive ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q51929049, wd:Q110022, wd:Q12230930, wd:Q473746 .
  }
}
