# tool: scribe-data
# All arabic (Q13955) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?verbs
    ?dualPerformativeActiveSecondPerson
  ?singularPerformativeActiveFeminineThirdPerson
  ?singular
  ?dualFiilMudariActiveSubjunctiveMasculineThirdPerson
  ?singularPassivePerformativeMasculineSecondPerson
  ?singularPerformativeMasculineThirdPerson
  ?pluralFeminine
  ?singularActiveFemininePastThirdPerson
  ?singularPerformativeActiveMasculineThirdPerson
  ?fiilMudariActivePluralFeminineSecondPersonIndicative
  ?performativeActivePluralFeminineSecondPerson
  ?singularFiilMudariActiveFeminineSubjunctiveThirdPerson
  ?activePluralPastMasculineThirdPerson
  ?past
  ?singularPastMasculineThirdPersonIndefinite
  ?singularFiilMudariActiveMasculineThirdPersonIndicative
  ?singularFiilMudariActiveMasculineSecondPersonIndicative
  ?dualPerformativeActiveFeminineThirdPerson
  ?singularPerformativeActiveFeminineSecondPerson
  ?pluralMasculine
  ?singularPerformativeActiveMasculineSecondPerson
  ?singularFiilMudariActiveFeminineSubjunctiveSecondPerson
  ?activePluralPastMasculineSecondPerson
  ?dualPerformativeActiveMasculineThirdPerson
  ?singularPassivePerformativeFeminineSecondPerson
  ?performativeActivePluralFeminineThirdPerson
  ?dualFiilMudariActiveFeminineThirdPersonIndicative
  ?singularActivePastMasculineSecondPerson
  ?dualCommonActivePastSecondPerson
  ?fiilMudariActivePluralFeminineSubjunctiveThirdPerson
  ?dualActiveFemininePastThirdPerson
  ?activePluralFemininePastThirdPerson
  ?dualFiilMudariActiveMasculineThirdPersonIndicative
  ?singularPassivePerformativeFirstPerson
  ?singularFiilMudariActiveSubjunctiveMasculineThirdPerson
  ?dualFiilMudariActiveSubjunctiveSecondPerson
  ?fiilMudariActivePluralSubjunctiveMasculineSecondPerson
  ?performativeActivePluralMasculineSecondPerson
  ?activePluralImperativeMasculineSecondPerson
  ?dualActivePastMasculineThirdPerson
  ?singularPastMasculineThirdPerson
  ?fiilMudariActivePluralSubjunctiveSecondPerson
  ?singularFiilMudariActiveMasculineThirdPerson
  ?fiilMudariActivePluralFirstPersonSubjunctive
  ?singularFiilMudariActiveFirstPersonSubjunctive
  ?fiilMudariActivePluralFeminineSubjunctiveSecondPerson
  ?singularPerformativeActiveFirstPerson
  ?singularActivePastFirstPerson
  ?dualActiveImperativeSecondPerson
  ?singularFiilMudariFirstPerson
  ?activePluralFemininePastSecondPerson
  ?fiilMudariActivePluralMasculineSecondPersonIndicative
  ?singularActiveImperativeMasculineSecondPerson
  ?singularFemininePastThirdPerson
  ?singularActiveFemininePastSecondPerson
  ?singularFiilMudariActiveFeminineSecondPersonIndicative
  ?dualFiilMudariActiveFeminineSubjunctiveThirdPerson
  ?singularFiilMudariActiveFirstPerson
  ?singularFiilMudariFirstPersonIndicative
  ?singularPerformativeMasculineThirdPersonIndicative
  ?fiilMudariActivePluralFirstPersonIndicative
  ?singularFiilMudariActiveFirstPersonIndicative
  ?singularPerformativeFirstPerson
  ?fiilMudariActivePluralSubjunctiveMasculineThirdPerson
  ?passiveParticiple
  ?singularFiilMudariActiveFeminineThirdPersonIndicative
  ?singularActiveFeminineSecondPersonPerfect
  ?dualActivePastMasculine
  ?activePluralPastFirstPerson
  ?singularActiveThirdPersonPluperfectIndicative
  ?activePluralFeminineImperativeSecondPerson
  ?performativeActivePluralFirstPerson
  ?singularActiveFirstPersonPerfect
  ?performativeActivePluralMasculineThirdPerson
  ?singularActiveFeminineImperativeSecondPerson
  ?singularMasculineThirdPerson
  ?singularActiveMasculineSecondPersonPerfect
  ?dualFiilMudariActiveSecondPersonIndicative
  ?indicativeSecondPersonDualFiilMudari
  ?masculineIndicativeThirdPersonSingularFiilMudari
  ?masculineActivePerformativeSecondPersonPlural
  ?masculineIndicativeThirdPersonDualFiilMudari
  ?feminineActivePerformativeSecondPersonPlural
  ?feminineIndicativeThirdPersonDualFiilMudari
  ?masculineActivePerformativeThirdPersonDual
  ?feminineActivePerformativeThirdPersonDual
  ?activePerformativeFirstPersonSingular
  ?masculineIndicativeSecondPersonSingularFiilMudari
  ?activePerformativeSecondPersonDual
  ?feminineIndicativeThirdPersonSingularFiilMudari
  ?indicativeFirstPersonSingularFiilMudari
  ?masculineActivePerformativeSecondPersonSingular
  ?feminineIndicativeSecondPersonSingularFiilMudari
  ?feminineActivePerformativeSecondPersonSingular
  ?masculineActivePerformativeThirdPersonSingular
  ?feminineActivePerformativeThirdPersonSingular
  ?masculineIndicativeSecondPersonPluralFiilMudari
  ?indicativeFirstPersonPluralFiilMudari
  ?feminineIndicativeSecondPersonPluralFiilMudari
  ?activePerformativeFirstPersonPlural
    WHERE {
    ?lexeme dct:language wd:Q13955 ;
        wikibase:lexicalCategory wd:Q24905 ;
        wikibase:lemma ?verbs .
        FILTER(lang(?verbs) = "ar")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualPerformativeActiveSecondPersonForm .
            ?dualPerformativeActiveSecondPersonForm ontolex:representation ?dualPerformativeActiveSecondPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q124351233, wd:Q1317831, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeActiveFeminineThirdPersonForm .
            ?singularPerformativeActiveFeminineThirdPersonForm ontolex:representation ?singularPerformativeActiveFeminineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q1317831, wd:Q1775415, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularForm .
            ?singularForm ontolex:representation ?singular ;
                wikibase:grammaticalFeature wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveSubjunctiveMasculineThirdPersonForm .
            ?dualFiilMudariActiveSubjunctiveMasculineThirdPersonForm ontolex:representation ?dualFiilMudariActiveSubjunctiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q473746, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPassivePerformativeMasculineSecondPersonForm .
            ?singularPassivePerformativeMasculineSecondPersonForm ontolex:representation ?singularPassivePerformativeMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1194697, wd:Q124351233, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeMasculineThirdPersonForm .
            ?singularPerformativeMasculineThirdPersonForm ontolex:representation ?singularPerformativeMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralFeminineForm .
            ?pluralFeminineForm ontolex:representation ?pluralFeminine ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q1775415 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveFemininePastThirdPersonForm .
            ?singularActiveFemininePastThirdPersonForm ontolex:representation ?singularActiveFemininePastThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1775415, wd:Q1994301, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeActiveMasculineThirdPersonForm .
            ?singularPerformativeActiveMasculineThirdPersonForm ontolex:representation ?singularPerformativeActiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q1317831, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralFeminineSecondPersonIndicativeForm .
            ?fiilMudariActivePluralFeminineSecondPersonIndicativeForm ontolex:representation ?fiilMudariActivePluralFeminineSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?performativeActivePluralFeminineSecondPersonForm .
            ?performativeActivePluralFeminineSecondPersonForm ontolex:representation ?performativeActivePluralFeminineSecondPerson ;
                wikibase:grammaticalFeature wd:Q124351233, wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFeminineSubjunctiveThirdPersonForm .
            ?singularFiilMudariActiveFeminineSubjunctiveThirdPersonForm ontolex:representation ?singularFiilMudariActiveFeminineSubjunctiveThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q473746, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralPastMasculineThirdPersonForm .
            ?activePluralPastMasculineThirdPersonForm ontolex:representation ?activePluralPastMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1994301, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pastForm .
            ?pastForm ontolex:representation ?past ;
                wikibase:grammaticalFeature wd:Q1994301 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPastMasculineThirdPersonIndefiniteForm .
            ?singularPastMasculineThirdPersonIndefiniteForm ontolex:representation ?singularPastMasculineThirdPersonIndefinite ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q499327, wd:Q51929074, wd:Q53997857 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveMasculineThirdPersonIndicativeForm .
            ?singularFiilMudariActiveMasculineThirdPersonIndicativeForm ontolex:representation ?singularFiilMudariActiveMasculineThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q499327, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveMasculineSecondPersonIndicativeForm .
            ?singularFiilMudariActiveMasculineSecondPersonIndicativeForm ontolex:representation ?singularFiilMudariActiveMasculineSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q499327, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualPerformativeActiveFeminineThirdPersonForm .
            ?dualPerformativeActiveFeminineThirdPersonForm ontolex:representation ?dualPerformativeActiveFeminineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q124351233, wd:Q1317831, wd:Q1775415, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeActiveFeminineSecondPersonForm .
            ?singularPerformativeActiveFeminineSecondPersonForm ontolex:representation ?singularPerformativeActiveFeminineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q1317831, wd:Q1775415, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralMasculineForm .
            ?pluralMasculineForm ontolex:representation ?pluralMasculine ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeActiveMasculineSecondPersonForm .
            ?singularPerformativeActiveMasculineSecondPersonForm ontolex:representation ?singularPerformativeActiveMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q1317831, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFeminineSubjunctiveSecondPersonForm .
            ?singularFiilMudariActiveFeminineSubjunctiveSecondPersonForm ontolex:representation ?singularFiilMudariActiveFeminineSubjunctiveSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q473746, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralPastMasculineSecondPersonForm .
            ?activePluralPastMasculineSecondPersonForm ontolex:representation ?activePluralPastMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1994301, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualPerformativeActiveMasculineThirdPersonForm .
            ?dualPerformativeActiveMasculineThirdPersonForm ontolex:representation ?dualPerformativeActiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q124351233, wd:Q1317831, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPassivePerformativeFeminineSecondPersonForm .
            ?singularPassivePerformativeFeminineSecondPersonForm ontolex:representation ?singularPassivePerformativeFeminineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1194697, wd:Q124351233, wd:Q1775415, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?performativeActivePluralFeminineThirdPersonForm .
            ?performativeActivePluralFeminineThirdPersonForm ontolex:representation ?performativeActivePluralFeminineThirdPerson ;
                wikibase:grammaticalFeature wd:Q124351233, wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveFeminineThirdPersonIndicativeForm .
            ?dualFiilMudariActiveFeminineThirdPersonIndicativeForm ontolex:representation ?dualFiilMudariActiveFeminineThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActivePastMasculineSecondPersonForm .
            ?singularActivePastMasculineSecondPersonForm ontolex:representation ?singularActivePastMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1994301, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualCommonActivePastSecondPersonForm .
            ?dualCommonActivePastSecondPersonForm ontolex:representation ?dualCommonActivePastSecondPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q1305037, wd:Q1317831, wd:Q1994301, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralFeminineSubjunctiveThirdPersonForm .
            ?fiilMudariActivePluralFeminineSubjunctiveThirdPersonForm ontolex:representation ?fiilMudariActivePluralFeminineSubjunctiveThirdPerson ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q473746, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualActiveFemininePastThirdPersonForm .
            ?dualActiveFemininePastThirdPersonForm ontolex:representation ?dualActiveFemininePastThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q1317831, wd:Q1775415, wd:Q1994301, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralFemininePastThirdPersonForm .
            ?activePluralFemininePastThirdPersonForm ontolex:representation ?activePluralFemininePastThirdPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q1994301, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveMasculineThirdPersonIndicativeForm .
            ?dualFiilMudariActiveMasculineThirdPersonIndicativeForm ontolex:representation ?dualFiilMudariActiveMasculineThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q499327, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPassivePerformativeFirstPersonForm .
            ?singularPassivePerformativeFirstPersonForm ontolex:representation ?singularPassivePerformativeFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1194697, wd:Q124351233, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveSubjunctiveMasculineThirdPersonForm .
            ?singularFiilMudariActiveSubjunctiveMasculineThirdPersonForm ontolex:representation ?singularFiilMudariActiveSubjunctiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q473746, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveSubjunctiveSecondPersonForm .
            ?dualFiilMudariActiveSubjunctiveSecondPersonForm ontolex:representation ?dualFiilMudariActiveSubjunctiveSecondPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q473746, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralSubjunctiveMasculineSecondPersonForm .
            ?fiilMudariActivePluralSubjunctiveMasculineSecondPersonForm ontolex:representation ?fiilMudariActivePluralSubjunctiveMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q473746, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?performativeActivePluralMasculineSecondPersonForm .
            ?performativeActivePluralMasculineSecondPersonForm ontolex:representation ?performativeActivePluralMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q124351233, wd:Q1317831, wd:Q146786, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralImperativeMasculineSecondPersonForm .
            ?activePluralImperativeMasculineSecondPersonForm ontolex:representation ?activePluralImperativeMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q22716, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualActivePastMasculineThirdPersonForm .
            ?dualActivePastMasculineThirdPersonForm ontolex:representation ?dualActivePastMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q1317831, wd:Q1994301, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPastMasculineThirdPersonForm .
            ?singularPastMasculineThirdPersonForm ontolex:representation ?singularPastMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralSubjunctiveSecondPersonForm .
            ?fiilMudariActivePluralSubjunctiveSecondPersonForm ontolex:representation ?fiilMudariActivePluralSubjunctiveSecondPerson ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q473746, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveMasculineThirdPersonForm .
            ?singularFiilMudariActiveMasculineThirdPersonForm ontolex:representation ?singularFiilMudariActiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralFirstPersonSubjunctiveForm .
            ?fiilMudariActivePluralFirstPersonSubjunctiveForm ontolex:representation ?fiilMudariActivePluralFirstPersonSubjunctive ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q473746 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFirstPersonSubjunctiveForm .
            ?singularFiilMudariActiveFirstPersonSubjunctiveForm ontolex:representation ?singularFiilMudariActiveFirstPersonSubjunctive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q21714344, wd:Q473746 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralFeminineSubjunctiveSecondPersonForm .
            ?fiilMudariActivePluralFeminineSubjunctiveSecondPersonForm ontolex:representation ?fiilMudariActivePluralFeminineSubjunctiveSecondPerson ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q473746, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeActiveFirstPersonForm .
            ?singularPerformativeActiveFirstPersonForm ontolex:representation ?singularPerformativeActiveFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q1317831, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActivePastFirstPersonForm .
            ?singularActivePastFirstPersonForm ontolex:representation ?singularActivePastFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1994301, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualActiveImperativeSecondPersonForm .
            ?dualActiveImperativeSecondPersonForm ontolex:representation ?dualActiveImperativeSecondPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q1317831, wd:Q22716, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariFirstPersonForm .
            ?singularFiilMudariFirstPersonForm ontolex:representation ?singularFiilMudariFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralFemininePastSecondPersonForm .
            ?activePluralFemininePastSecondPersonForm ontolex:representation ?activePluralFemininePastSecondPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q1994301, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralMasculineSecondPersonIndicativeForm .
            ?fiilMudariActivePluralMasculineSecondPersonIndicativeForm ontolex:representation ?fiilMudariActivePluralMasculineSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q499327, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveImperativeMasculineSecondPersonForm .
            ?singularActiveImperativeMasculineSecondPersonForm ontolex:representation ?singularActiveImperativeMasculineSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q22716, wd:Q499327, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFemininePastThirdPersonForm .
            ?singularFemininePastThirdPersonForm ontolex:representation ?singularFemininePastThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q1994301, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveFemininePastSecondPersonForm .
            ?singularActiveFemininePastSecondPersonForm ontolex:representation ?singularActiveFemininePastSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1775415, wd:Q1994301, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFeminineSecondPersonIndicativeForm .
            ?singularFiilMudariActiveFeminineSecondPersonIndicativeForm ontolex:representation ?singularFiilMudariActiveFeminineSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveFeminineSubjunctiveThirdPersonForm .
            ?dualFiilMudariActiveFeminineSubjunctiveThirdPersonForm ontolex:representation ?dualFiilMudariActiveFeminineSubjunctiveThirdPerson ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q473746, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFirstPersonForm .
            ?singularFiilMudariActiveFirstPersonForm ontolex:representation ?singularFiilMudariActiveFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariFirstPersonIndicativeForm .
            ?singularFiilMudariFirstPersonIndicativeForm ontolex:representation ?singularFiilMudariFirstPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q21714344, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeMasculineThirdPersonIndicativeForm .
            ?singularPerformativeMasculineThirdPersonIndicativeForm ontolex:representation ?singularPerformativeMasculineThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q499327, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralFirstPersonIndicativeForm .
            ?fiilMudariActivePluralFirstPersonIndicativeForm ontolex:representation ?fiilMudariActivePluralFirstPersonIndicative ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q21714344, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFirstPersonIndicativeForm .
            ?singularFiilMudariActiveFirstPersonIndicativeForm ontolex:representation ?singularFiilMudariActiveFirstPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q21714344, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPerformativeFirstPersonForm .
            ?singularPerformativeFirstPersonForm ontolex:representation ?singularPerformativeFirstPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q124351233, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?fiilMudariActivePluralSubjunctiveMasculineThirdPersonForm .
            ?fiilMudariActivePluralSubjunctiveMasculineThirdPersonForm ontolex:representation ?fiilMudariActivePluralSubjunctiveMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q12230930, wd:Q1317831, wd:Q146786, wd:Q473746, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?passiveParticipleForm .
            ?passiveParticipleForm ontolex:representation ?passiveParticiple ;
                wikibase:grammaticalFeature wd:Q72249544 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularFiilMudariActiveFeminineThirdPersonIndicativeForm .
            ?singularFiilMudariActiveFeminineThirdPersonIndicativeForm ontolex:representation ?singularFiilMudariActiveFeminineThirdPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q12230930, wd:Q1317831, wd:Q1775415, wd:Q51929074, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveFeminineSecondPersonPerfectForm .
            ?singularActiveFeminineSecondPersonPerfectForm ontolex:representation ?singularActiveFeminineSecondPersonPerfect ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1775415, wd:Q51929049, wd:Q625420 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualActivePastMasculineForm .
            ?dualActivePastMasculineForm ontolex:representation ?dualActivePastMasculine ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q1317831, wd:Q1994301, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralPastFirstPersonForm .
            ?activePluralPastFirstPersonForm ontolex:representation ?activePluralPastFirstPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1994301, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveThirdPersonPluperfectIndicativeForm .
            ?singularActiveThirdPersonPluperfectIndicativeForm ontolex:representation ?singularActiveThirdPersonPluperfectIndicative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q51929074, wd:Q623742, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePluralFeminineImperativeSecondPersonForm .
            ?activePluralFeminineImperativeSecondPersonForm ontolex:representation ?activePluralFeminineImperativeSecondPerson ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q146786, wd:Q1775415, wd:Q22716, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?performativeActivePluralFirstPersonForm .
            ?performativeActivePluralFirstPersonForm ontolex:representation ?performativeActivePluralFirstPerson ;
                wikibase:grammaticalFeature wd:Q124351233, wd:Q1317831, wd:Q146786, wd:Q21714344 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveFirstPersonPerfectForm .
            ?singularActiveFirstPersonPerfectForm ontolex:representation ?singularActiveFirstPersonPerfect ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q21714344, wd:Q625420 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?performativeActivePluralMasculineThirdPersonForm .
            ?performativeActivePluralMasculineThirdPersonForm ontolex:representation ?performativeActivePluralMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q124351233, wd:Q1317831, wd:Q146786, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveFeminineImperativeSecondPersonForm .
            ?singularActiveFeminineImperativeSecondPersonForm ontolex:representation ?singularActiveFeminineImperativeSecondPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q1775415, wd:Q22716, wd:Q51929049 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularMasculineThirdPersonForm .
            ?singularMasculineThirdPersonForm ontolex:representation ?singularMasculineThirdPerson ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q51929074 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularActiveMasculineSecondPersonPerfectForm .
            ?singularActiveMasculineSecondPersonPerfectForm ontolex:representation ?singularActiveMasculineSecondPersonPerfect ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1317831, wd:Q499327, wd:Q51929049, wd:Q625420 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?dualFiilMudariActiveSecondPersonIndicativeForm .
            ?dualFiilMudariActiveSecondPersonIndicativeForm ontolex:representation ?dualFiilMudariActiveSecondPersonIndicative ;
                wikibase:grammaticalFeature wd:Q110022, wd:Q12230930, wd:Q1317831, wd:Q51929049, wd:Q682111 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeSecondPersonDualFiilMudariForm .
            ?indicativeSecondPersonDualFiilMudariForm ontolex:representation ?indicativeSecondPersonDualFiilMudari ;
                wikibase:grammaticalFeature wd:Q682111, wd:Q51929049, wd:Q110022, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineIndicativeThirdPersonSingularFiilMudariForm .
            ?masculineIndicativeThirdPersonSingularFiilMudariForm ontolex:representation ?masculineIndicativeThirdPersonSingularFiilMudari ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q682111, wd:Q51929074, wd:Q110786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineActivePerformativeSecondPersonPluralForm .
            ?masculineActivePerformativeSecondPersonPluralForm ontolex:representation ?masculineActivePerformativeSecondPersonPlural ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineIndicativeThirdPersonDualFiilMudariForm .
            ?masculineIndicativeThirdPersonDualFiilMudariForm ontolex:representation ?masculineIndicativeThirdPersonDualFiilMudari ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q682111, wd:Q51929074, wd:Q110022, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineActivePerformativeSecondPersonPluralForm .
            ?feminineActivePerformativeSecondPersonPluralForm ontolex:representation ?feminineActivePerformativeSecondPersonPlural ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineIndicativeThirdPersonDualFiilMudariForm .
            ?feminineIndicativeThirdPersonDualFiilMudariForm ontolex:representation ?feminineIndicativeThirdPersonDualFiilMudari ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q682111, wd:Q51929074, wd:Q110022, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineActivePerformativeThirdPersonDualForm .
            ?masculineActivePerformativeThirdPersonDualForm ontolex:representation ?masculineActivePerformativeThirdPersonDual ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110022 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineActivePerformativeThirdPersonDualForm .
            ?feminineActivePerformativeThirdPersonDualForm ontolex:representation ?feminineActivePerformativeThirdPersonDual ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110022 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePerformativeFirstPersonSingularForm .
            ?activePerformativeFirstPersonSingularForm ontolex:representation ?activePerformativeFirstPersonSingular ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q21714344, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineIndicativeSecondPersonSingularFiilMudariForm .
            ?masculineIndicativeSecondPersonSingularFiilMudariForm ontolex:representation ?masculineIndicativeSecondPersonSingularFiilMudari ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q682111, wd:Q51929049, wd:Q110786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePerformativeSecondPersonDualForm .
            ?activePerformativeSecondPersonDualForm ontolex:representation ?activePerformativeSecondPersonDual ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q110022 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineIndicativeThirdPersonSingularFiilMudariForm .
            ?feminineIndicativeThirdPersonSingularFiilMudariForm ontolex:representation ?feminineIndicativeThirdPersonSingularFiilMudari ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q682111, wd:Q51929074, wd:Q110786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeFirstPersonSingularFiilMudariForm .
            ?indicativeFirstPersonSingularFiilMudariForm ontolex:representation ?indicativeFirstPersonSingularFiilMudari ;
                wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q110786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineActivePerformativeSecondPersonSingularForm .
            ?masculineActivePerformativeSecondPersonSingularForm ontolex:representation ?masculineActivePerformativeSecondPersonSingular ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineIndicativeSecondPersonSingularFiilMudariForm .
            ?feminineIndicativeSecondPersonSingularFiilMudariForm ontolex:representation ?feminineIndicativeSecondPersonSingularFiilMudari ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q682111, wd:Q51929049, wd:Q110786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineActivePerformativeSecondPersonSingularForm .
            ?feminineActivePerformativeSecondPersonSingularForm ontolex:representation ?feminineActivePerformativeSecondPersonSingular ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineActivePerformativeThirdPersonSingularForm .
            ?masculineActivePerformativeThirdPersonSingularForm ontolex:representation ?masculineActivePerformativeThirdPersonSingular ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineActivePerformativeThirdPersonSingularForm .
            ?feminineActivePerformativeThirdPersonSingularForm ontolex:representation ?feminineActivePerformativeThirdPersonSingular ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?masculineIndicativeSecondPersonPluralFiilMudariForm .
            ?masculineIndicativeSecondPersonPluralFiilMudariForm ontolex:representation ?masculineIndicativeSecondPersonPluralFiilMudari ;
                wikibase:grammaticalFeature wd:Q499327, wd:Q682111, wd:Q51929049, wd:Q146786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?indicativeFirstPersonPluralFiilMudariForm .
            ?indicativeFirstPersonPluralFiilMudariForm ontolex:representation ?indicativeFirstPersonPluralFiilMudari ;
                wikibase:grammaticalFeature wd:Q682111, wd:Q21714344, wd:Q146786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?feminineIndicativeSecondPersonPluralFiilMudariForm .
            ?feminineIndicativeSecondPersonPluralFiilMudariForm ontolex:representation ?feminineIndicativeSecondPersonPluralFiilMudari ;
                wikibase:grammaticalFeature wd:Q1775415, wd:Q682111, wd:Q51929049, wd:Q146786, wd:Q12230930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?activePerformativeFirstPersonPluralForm .
            ?activePerformativeFirstPersonPluralForm ontolex:representation ?activePerformativeFirstPersonPlural ;
                wikibase:grammaticalFeature wd:Q1317831, wd:Q124351233, wd:Q21714344, wd:Q146786 .
        }
}