# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?feminineThirdPersonSingular
  ?feminineActivePastPerfectSecondPersonSingular
  ?feminineActivePastPerfectSecondPersonPlural

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineThirdPersonSingularForm .
    ?feminineThirdPersonSingularForm ontolex:representation ?feminineThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePastPerfectSecondPersonSingularForm .
    ?feminineActivePastPerfectSecondPersonSingularForm ontolex:representation ?feminineActivePastPerfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q64005357, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePastPerfectSecondPersonPluralForm .
    ?feminineActivePastPerfectSecondPersonPluralForm ontolex:representation ?feminineActivePastPerfectSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q64005357, wd:Q51929049, wd:Q146786 .
  }
}
