# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculinePastThirdPersonSingular
  ?activePastFirstPersonSingular
  ?activePastFirstPersonPlural
  ?masculineActiveImperativeSecondPersonPlural
  ?masculineActivePerfectSecondPersonSingular
  ?masculinePastThirdPersonIndefiniteSingular

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastThirdPersonSingularForm .
    ?masculinePastThirdPersonSingularForm ontolex:representation ?masculinePastThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePastFirstPersonSingularForm .
    ?activePastFirstPersonSingularForm ontolex:representation ?activePastFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q1994301, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePastFirstPersonPluralForm .
    ?activePastFirstPersonPluralForm ontolex:representation ?activePastFirstPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q1994301, wd:Q21714344, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineActiveImperativeSecondPersonPluralForm .
    ?masculineActiveImperativeSecondPersonPluralForm ontolex:representation ?masculineActiveImperativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q22716, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineActivePerfectSecondPersonSingularForm .
    ?masculineActivePerfectSecondPersonSingularForm ontolex:representation ?masculineActivePerfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1317831, wd:Q625420, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastThirdPersonIndefiniteSingularForm .
    ?masculinePastThirdPersonIndefiniteSingularForm ontolex:representation ?masculinePastThirdPersonIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q51929074, wd:Q53997857, wd:Q110786 .
  }
}
