# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?feminineActivePerformativeSecondPersonPlural
  ?feminineActivePerformativeThirdPersonSingular
  ?feminineActivePerformativeThirdPersonDual
  ?feminineActivePastThirdPersonDual
  ?feminineActivePastPerfectSecondPersonSingular
  ?feminineActiveSecondPersonSingularFiilMudariSubjunctive

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePerformativeSecondPersonPluralForm .
    ?feminineActivePerformativeSecondPersonPluralForm ontolex:representation ?feminineActivePerformativeSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePerformativeThirdPersonSingularForm .
    ?feminineActivePerformativeThirdPersonSingularForm ontolex:representation ?feminineActivePerformativeThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePerformativeThirdPersonDualForm .
    ?feminineActivePerformativeThirdPersonDualForm ontolex:representation ?feminineActivePerformativeThirdPersonDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q124351233, wd:Q51929074, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePastThirdPersonDualForm .
    ?feminineActivePastThirdPersonDualForm ontolex:representation ?feminineActivePastThirdPersonDual ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q1994301, wd:Q51929074, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActivePastPerfectSecondPersonSingularForm .
    ?feminineActivePastPerfectSecondPersonSingularForm ontolex:representation ?feminineActivePastPerfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q64005357, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineActiveSecondPersonSingularFiilMudariSubjunctiveForm .
    ?feminineActiveSecondPersonSingularFiilMudariSubjunctiveForm ontolex:representation ?feminineActiveSecondPersonSingularFiilMudariSubjunctive ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q1317831, wd:Q51929049, wd:Q110786, wd:Q12230930, wd:Q473746 .
  }
}
