# tool: scribe-data
# All Arabic (Q13955) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?indicativeSecondPersonDualFiilMudari
  ?feminineIndicativeSecondPersonSingularFiilMudari
  ?feminineIndicativeSecondPersonPluralFiilMudari
  ?masculineIndicativeSecondPersonSingularFiilMudari
  ?masculineIndicativeSecondPersonPluralFiilMudari


WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeSecondPersonDualFiilMudariForm .
    ?indicativeSecondPersonDualFiilMudariForm ontolex:representation ?indicativeSecondPersonDualFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110022, wd:Q682111, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineIndicativeSecondPersonSingularFiilMudariForm .
    ?feminineIndicativeSecondPersonSingularFiilMudariForm ontolex:representation ?feminineIndicativeSecondPersonSingularFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q1775415, wd:Q682111, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineIndicativeSecondPersonPluralFiilMudariForm .
    ?feminineIndicativeSecondPersonPluralFiilMudariForm ontolex:representation ?feminineIndicativeSecondPersonPluralFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q1775415, wd:Q682111, wd:Q12230930 .
  }

  # MARK: Imperative
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndicativeSecondPersonSingularFiilMudariForm .
    ?masculineIndicativeSecondPersonSingularFiilMudariForm ontolex:representation ?masculineIndicativeSecondPersonSingularFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q499327, wd:Q682111, wd:Q12230930 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndicativeSecondPersonPluralFiilMudariForm .
    ?masculineIndicativeSecondPersonPluralFiilMudariForm ontolex:representation ?masculineIndicativeSecondPersonPluralFiilMudari ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q499327, wd:Q682111, wd:Q12230930 .
  }




}
