name: 🐞 Bug report
description: Report a bug to help us improve Scribe-Data.
labels: ["bug"]
body:
  - type: checkboxes
    id: new-bug
    attributes:
      label: Terms
      options:
        - label: I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
          required: true
        - label: I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    attributes:
      label: Behavior
      placeholder: |
        A concise description of what you're experiencing and what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
