name: 📝 Documentation
description: Suggest improvements or updates to the documentation of Scribe-Data.
type: "task"
labels: ["documentation"]
projects: ["scribe-org/1"]
body:
  - type: checkboxes
    id: doc-enhancement
    attributes:
      label: Terms
      options:
        - label: I have searched all [open documentation issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation)
          required: true
        - label: I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    attributes:
      label: Current Documentation
      placeholder: |
        Provide a brief description or link to the current documentation you want to enhance.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Enhancement
      placeholder: |
        Describe the improvements or changes you'd like to see in the documentation.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
