# tool: scribe-data
# All English (Q1860) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?genitive
  ?firstPerson
  ?secondPerson
  ?thirdPerson
  ?singular
  ?plural

WHERE {
  ?lexeme dct:language wd:Q1860 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonForm .
    ?firstPersonForm ontolex:representation ?firstPerson ;
      wikibase:grammaticalFeature wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonForm .
    ?secondPersonForm ontolex:representation ?secondPerson ;
      wikibase:grammaticalFeature wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonForm .
    ?thirdPersonForm ontolex:representation ?thirdPerson ;
      wikibase:grammaticalFeature wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }
}
