# tool: scribe-data
# All english (Q1860) personal_pronouns (Q468801) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?personal_pronouns
    ?nominative
  ?genitive
  ?firstPerson
  ?singularOblique
  ?singularNominative
  ?thirdPerson
  ?oblique
  ?secondPerson

WHERE {
  ?lexeme dct:language wd:Q1860 ;
  wikibase:lexicalCategory wd:Q468801 ;
  wikibase:lemma ?personal_pronouns .
  FILTER(lang(?personal_pronouns) = "en")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?firstPersonForm .
    ?firstPersonForm ontolex:representation ?firstPerson ;
      wikibase:grammaticalFeature wd:Q21714344 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueForm .
    ?singularObliqueForm ontolex:representation ?singularOblique ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?thirdPersonForm .
    ?thirdPersonForm ontolex:representation ?thirdPerson ;
      wikibase:grammaticalFeature wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueForm .
    ?obliqueForm ontolex:representation ?oblique ;
      wikibase:grammaticalFeature wd:Q1233197 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?secondPersonForm .
    ?secondPersonForm ontolex:representation ?secondPerson ;
      wikibase:grammaticalFeature wd:Q51929049 .
  }
}
