# tool: scribe-data
# All Igbo (Q33578) prepositions (Q4833830) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?preposition
  ?contraction

WHERE {
  ?lexeme dct:language wd:Q33578 ;
    wikibase:lexicalCategory wd:Q4833830 ;
    wikibase:lemma ?preposition .

  # MARK: Contraction

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?contractionForm .
    ?contractionForm ontolex:representation ?contraction ;
      wikibase:grammaticalFeature wd:Q126473 .
  }
}
