# tool: scribe-data
# All Igbo (Q33578) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?noun

WHERE {
  ?lexeme dct:language wd:Q33578 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun .
}
