# tool: scribe-data
# All Russian (Q7737) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularGenitiveFeminine
  ?singularGenitiveMasculine
  ?singularGenitiveNeuter
  ?singularDativeFeminine
  ?singularDativeMasculine
  ?singularDativeNeuter

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveFeminineForm .
    ?singularGenitiveFeminineForm ontolex:representation ?singularGenitiveFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveMasculineForm .
    ?singularGenitiveMasculineForm ontolex:representation ?singularGenitiveMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveNeuterForm .
    ?singularGenitiveNeuterForm ontolex:representation ?singularGenitiveNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeFeminineForm .
    ?singularDativeFeminineForm ontolex:representation ?singularDativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeMasculineForm .
    ?singularDativeMasculineForm ontolex:representation ?singularDativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularDativeNeuterForm .
    ?singularDativeNeuterForm ontolex:representation ?singularDativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q145599, wd:Q1775461 .
  }
}
