# tool: scribe-data
# All Russian (Q7737) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativePlural
  ?genitivePlural
  ?dativePlural
  ?singularFemininePrepositional
  ?singularMasculinePrepositional
  ?singularNeuterPrepositional

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm .
    ?nominativePluralForm ontolex:representation ?nominativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFemininePrepositionalForm .
    ?singularFemininePrepositionalForm ontolex:representation ?singularFemininePrepositional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q2114906 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculinePrepositionalForm .
    ?singularMasculinePrepositionalForm ontolex:representation ?singularMasculinePrepositional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q2114906 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterPrepositionalForm .
    ?singularNeuterPrepositionalForm ontolex:representation ?singularNeuterPrepositional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q2114906 .
  }
}
