SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lemma
  ?adjectiveForm

WHERE {
  
  ?lexeme dct:language wd:Q7838 ;  
          wikibase:lexicalCategory wd:Q34698 ;  
          wikibase:lemma ?lemma .

  
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adjectiveLexicalForm .
    ?adjectiveLexicalForm ontolex:representation ?adjectiveForm .
  } .
}
