# tool: scribe-data
# All Russian (Q7737) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?feminineIndicativePastSingular
  ?masculineIndicativePastSingular
  ?neuterIndicativePastSingular

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineIndicativePastSingularForm .
    ?feminineIndicativePastSingularForm ontolex:representation ?feminineIndicativePastSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q682111, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndicativePastSingularForm .
    ?masculineIndicativePastSingularForm ontolex:representation ?masculineIndicativePastSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q682111, wd:Q1994301, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterIndicativePastSingularForm .
    ?neuterIndicativePastSingularForm ontolex:representation ?neuterIndicativePastSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q682111, wd:Q1994301, wd:Q110786 .
  }
}
