# tool: scribe-data
# All Swedish (Q9027) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularPositiveDefinite
  ?singularMasculinePositiveDefinite
  ?singularCommonPositiveIndefinite
  ?singularNeuterPositiveIndefinite

WHERE {
  ?lexeme dct:language wd:Q9027 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPositiveDefiniteForm .
    ?singularPositiveDefiniteForm ontolex:representation ?singularPositiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q3482678, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculinePositiveDefiniteForm .
    ?singularMasculinePositiveDefiniteForm ontolex:representation ?singularMasculinePositiveDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q3482678, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularCommonPositiveIndefiniteForm .
    ?singularCommonPositiveIndefiniteForm ontolex:representation ?singularCommonPositiveIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1305037, wd:Q3482678, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterPositiveIndefiniteForm .
    ?singularNeuterPositiveIndefiniteForm ontolex:representation ?singularNeuterPositiveIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q3482678, wd:Q53997857 .
  }
}
