# tool: scribe-data
# All french (Q150) personal_pronouns (Q468801) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?personal_pronouns
    ?oblique
  ?nominative
  ?nominativePlural
  ?singularNominative
    WHERE {
    ?lexeme dct:language wd:Q150 ;
        wikibase:lexicalCategory wd:Q468801 ;
        wikibase:lemma ?personal_pronouns .
        FILTER(lang(?personal_pronouns) = "fr")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?obliqueForm .
            ?obliqueForm ontolex:representation ?oblique ;
                wikibase:grammaticalFeature wd:Q1233197 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativePluralForm .
            ?nominativePluralForm ontolex:representation ?nominativePlural ;
                wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNominativeForm .
            ?singularNominativeForm ontolex:representation ?singularNominative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
        }
}