# tool: scribe-data
# All Hindi (from Hindustani Q11051) Proper Nouns.
# Enter this query at https://query.wikidata.org/.
# Note the necessity to filter for "hi" to remove Urdu (ur) words.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?ProperNouns

WHERE {
  ?lexeme dct:language wd:Q11051 ;  # Hindi language (from Hindustani)
    wikibase:lexicalCategory wd:Q147276 ;  # Proper Nouns
    wikibase:lemma ?ProperNouns .

  BIND(lang(?ProperNouns) as ?langProperNouns)
  FILTER(?langProperNouns = "hi")

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]".
  }
}
