# tool: scribe-data
# All Basque (Q8752) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularGenitive
  ?genitivePlural
  ?pluralAblativeInanimate
  ?pluralAblativeAnimate
  ?pluralAllativeInanimate
  ?pluralAllativeAnimate

WHERE {
  ?lexeme dct:language wd:Q8752 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeInanimateForm .
    ?pluralAblativeInanimateForm ontolex:representation ?pluralAblativeInanimate ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986, wd:Q51927539 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeAnimateForm .
    ?pluralAblativeAnimateForm ontolex:representation ?pluralAblativeAnimate ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986, wd:Q51927507 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAllativeInanimateForm .
    ?pluralAllativeInanimateForm ontolex:representation ?pluralAllativeInanimate ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q655020, wd:Q51927539 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAllativeAnimateForm .
    ?pluralAllativeAnimateForm ontolex:representation ?pluralAllativeAnimate ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q655020, wd:Q51927507 .
  }
}
