# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?locativeNeuterSingular
  ?locativeNeuterPlural
  ?locativeNeuterSingularSuperlative
  ?locativeNeuterSingularPositive
  ?locativeNeuterPluralSuperlative
  ?locativeNeuterPluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularForm .
    ?locativeNeuterSingularForm ontolex:representation ?locativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralForm .
    ?locativeNeuterPluralForm ontolex:representation ?locativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularSuperlativeForm .
    ?locativeNeuterSingularSuperlativeForm ontolex:representation ?locativeNeuterSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularPositiveForm .
    ?locativeNeuterSingularPositiveForm ontolex:representation ?locativeNeuterSingularPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralSuperlativeForm .
    ?locativeNeuterPluralSuperlativeForm ontolex:representation ?locativeNeuterPluralSuperlative ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralPositiveForm .
    ?locativeNeuterPluralPositiveForm ontolex:representation ?locativeNeuterPluralPositive ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786, wd:Q3482678 .
  }
}
