# tool: scribe-data
# All Czech (Q9056) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?vocativeMasculineAnimateSingular
  ?vocativeMasculineAnimateSingularComparative
  ?vocativeMasculineAnimateSingularSuperlative
  ?vocativeMasculineAnimateSingularPositive
  ?vocativeMasculineAnimatePluralSuperlative
  ?vocativeMasculineAnimatePluralPositive

WHERE {
  ?lexeme dct:language wd:Q9056 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularForm .
    ?vocativeMasculineAnimateSingularForm ontolex:representation ?vocativeMasculineAnimateSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularComparativeForm .
    ?vocativeMasculineAnimateSingularComparativeForm ontolex:representation ?vocativeMasculineAnimateSingularComparative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786, wd:Q14169499 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularSuperlativeForm .
    ?vocativeMasculineAnimateSingularSuperlativeForm ontolex:representation ?vocativeMasculineAnimateSingularSuperlative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimateSingularPositiveForm .
    ?vocativeMasculineAnimateSingularPositiveForm ontolex:representation ?vocativeMasculineAnimateSingularPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q110786, wd:Q3482678 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimatePluralSuperlativeForm .
    ?vocativeMasculineAnimatePluralSuperlativeForm ontolex:representation ?vocativeMasculineAnimatePluralSuperlative ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q146786, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeMasculineAnimatePluralPositiveForm .
    ?vocativeMasculineAnimatePluralPositiveForm ontolex:representation ?vocativeMasculineAnimatePluralPositive ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q54020116, wd:Q146786, wd:Q3482678 .
  }
}
