# tool: scribe-data
# All Swahili (Q7838) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?singular
  ?plural

WHERE {
  ?lexeme dct:language wd:Q7838 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?singular .
    FILTER(lang(?singular) = "sw")

  # MARK: Plural

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
      FILTER(lang(?plural) = "sw")
  }
}
