# tool: scribe-data
# All estonian (Q9072) verbs (Q24905) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verbs
    ?elativeSupine
  ?pluralPresentFirstPersonImperative
  ?singularPastFirstPersonConditional
  ?pluralPresentThirdPersonIndicative
  ?supine
  ?presentParticipleActivePast
  ?singularPresentFirstPersonConditional
  ?singularPastSecondPersonConditional
  ?presentParticipleActivePresent
  ?activePastConditional
  ?singularPastImperfectThirdPersonIndicative
  ?pastImperfectPluralThirdPersonIndicative
  ?singularPresentSecondPersonConditional
  ?pluralPresentSecondPersonIndicative
  ?singularPastImperfectFirstPersonIndicative
  ?pastImperfectPluralFirstPersonIndicative
  ?infinitive
  ?singularPastImperfectSecondPersonIndicative
  ?pastImperfectPluralSecondPersonIndicative
  ?pluralPresentImperativeSecondPerson
  ?activePresentConditional
  ?pluralPresentFirstPersonIndicative
  ?singularPresentThirdPersonIndicative
  ?pluralPastThirdPersonConditional
  ?inessiveSupine
  ?activePresentImperative
  ?supineTranslative
  ?pluralPresentThirdPersonConditional
  ?pluralPastFirstPersonConditional
  ?pluralPastSecondPersonConditional
  ?singularPresentFirstPersonIndicative
  ?singularPresentSecondPersonIndicative
  ?pluralPresentSecondPersonConditional
  ?pluralPresentFirstPersonConditional
  ?singularPresentImperativeSecondPerson
  ?abessiveSupine

WHERE {
  ?lexeme dct:language wd:Q9072 ;
  wikibase:lexicalCategory wd:Q24905 ;
  wikibase:lemma ?verbs .
  FILTER(lang(?verbs) = "et")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSupineForm .
    ?elativeSupineForm ontolex:representation ?elativeSupine ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q548470 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonImperativeForm .
    ?pluralPresentFirstPersonImperativeForm ontolex:representation ?pluralPresentFirstPersonImperative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastFirstPersonConditionalForm .
    ?singularPastFirstPersonConditionalForm ontolex:representation ?singularPastFirstPersonConditional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q21714344, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonIndicativeForm .
    ?pluralPresentThirdPersonIndicativeForm ontolex:representation ?pluralPresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?supineForm .
    ?supineForm ontolex:representation ?supine ;
      wikibase:grammaticalFeature wd:Q548470 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentParticipleActivePastForm .
    ?presentParticipleActivePastForm ontolex:representation ?presentParticipleActivePast ;
      wikibase:grammaticalFeature wd:Q10345583, wd:Q1317831, wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonConditionalForm .
    ?singularPresentFirstPersonConditionalForm ontolex:representation ?singularPresentFirstPersonConditional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastSecondPersonConditionalForm .
    ?singularPastSecondPersonConditionalForm ontolex:representation ?singularPastSecondPersonConditional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1994301, wd:Q51929049, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentParticipleActivePresentForm .
    ?presentParticipleActivePresentForm ontolex:representation ?presentParticipleActivePresent ;
      wikibase:grammaticalFeature wd:Q10345583, wd:Q1317831, wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePastConditionalForm .
    ?activePastConditionalForm ontolex:representation ?activePastConditional ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q1994301, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastImperfectThirdPersonIndicativeForm .
    ?singularPastImperfectThirdPersonIndicativeForm ontolex:representation ?singularPastImperfectThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastImperfectPluralThirdPersonIndicativeForm .
    ?pastImperfectPluralThirdPersonIndicativeForm ontolex:representation ?pastImperfectPluralThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonConditionalForm .
    ?singularPresentSecondPersonConditionalForm ontolex:representation ?singularPresentSecondPersonConditional ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonIndicativeForm .
    ?pluralPresentSecondPersonIndicativeForm ontolex:representation ?pluralPresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastImperfectFirstPersonIndicativeForm .
    ?singularPastImperfectFirstPersonIndicativeForm ontolex:representation ?singularPastImperfectFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastImperfectPluralFirstPersonIndicativeForm .
    ?pastImperfectPluralFirstPersonIndicativeForm ontolex:representation ?pastImperfectPluralFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infinitiveForm .
    ?infinitiveForm ontolex:representation ?infinitive ;
      wikibase:grammaticalFeature wd:Q179230 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPastImperfectSecondPersonIndicativeForm .
    ?singularPastImperfectSecondPersonIndicativeForm ontolex:representation ?singularPastImperfectSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q12547192, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastImperfectPluralSecondPersonIndicativeForm .
    ?pastImperfectPluralSecondPersonIndicativeForm ontolex:representation ?pastImperfectPluralSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q12547192, wd:Q146786, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentImperativeSecondPersonForm .
    ?pluralPresentImperativeSecondPersonForm ontolex:representation ?pluralPresentImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePresentConditionalForm .
    ?activePresentConditionalForm ontolex:representation ?activePresentConditional ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q192613, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonIndicativeForm .
    ?pluralPresentFirstPersonIndicativeForm ontolex:representation ?pluralPresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentThirdPersonIndicativeForm .
    ?singularPresentThirdPersonIndicativeForm ontolex:representation ?singularPresentThirdPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929074, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastThirdPersonConditionalForm .
    ?pluralPastThirdPersonConditionalForm ontolex:representation ?pluralPastThirdPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q51929074, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSupineForm .
    ?inessiveSupineForm ontolex:representation ?inessiveSupine ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q548470 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePresentImperativeForm .
    ?activePresentImperativeForm ontolex:representation ?activePresentImperative ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q192613, wd:Q22716 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?supineTranslativeForm .
    ?supineTranslativeForm ontolex:representation ?supineTranslative ;
      wikibase:grammaticalFeature wd:Q548470, wd:Q950170 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentThirdPersonConditionalForm .
    ?pluralPresentThirdPersonConditionalForm ontolex:representation ?pluralPresentThirdPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929074, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastFirstPersonConditionalForm .
    ?pluralPastFirstPersonConditionalForm ontolex:representation ?pluralPastFirstPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q21714344, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPastSecondPersonConditionalForm .
    ?pluralPastSecondPersonConditionalForm ontolex:representation ?pluralPastSecondPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1994301, wd:Q51929049, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentFirstPersonIndicativeForm .
    ?singularPresentFirstPersonIndicativeForm ontolex:representation ?singularPresentFirstPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q21714344, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentSecondPersonIndicativeForm .
    ?singularPresentSecondPersonIndicativeForm ontolex:representation ?singularPresentSecondPersonIndicative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q51929049, wd:Q682111 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentSecondPersonConditionalForm .
    ?pluralPresentSecondPersonConditionalForm ontolex:representation ?pluralPresentSecondPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q51929049, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPresentFirstPersonConditionalForm .
    ?pluralPresentFirstPersonConditionalForm ontolex:representation ?pluralPresentFirstPersonConditional ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192613, wd:Q21714344, wd:Q625581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPresentImperativeSecondPersonForm .
    ?singularPresentImperativeSecondPersonForm ontolex:representation ?singularPresentImperativeSecondPerson ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q192613, wd:Q22716, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessiveSupineForm .
    ?abessiveSupineForm ontolex:representation ?abessiveSupine ;
      wikibase:grammaticalFeature wd:Q319822, wd:Q548470 .
  }
}
