# tool: scribe-data
# All Sami (Q33947) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?comitative
  ?genitiveAccusative
  ?genitiveSingular
  ?genitivePlural
  ?comitativeSingular
  ?comitativePlural

WHERE {
  ?lexeme dct:language wd:Q33947 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for se to remove northern (se) words.
  FILTER(lang(?propernoun) = "se")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeForm .
    ?comitativeForm ontolex:representation ?comitative ;
      wikibase:grammaticalFeature wd:Q838581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveAccusativeForm .
    ?genitiveAccusativeForm ontolex:representation ?genitiveAccusative ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeSingularForm .
    ?comitativeSingularForm ontolex:representation ?comitativeSingular ;
      wikibase:grammaticalFeature wd:Q838581, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativePluralForm .
    ?comitativePluralForm ontolex:representation ?comitativePlural ;
      wikibase:grammaticalFeature wd:Q838581, wd:Q146786 .
  }
}
