# tool: scribe-data
# All Sami (Q33947) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?essive
  ?genitivePlural
  ?accusativePlural
  ?pluralLocative
  ?pluralIllative
  ?pluralComitative

WHERE {
  ?lexeme dct:language wd:Q33947 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?propernoun ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for se to remove northern (se) words.
  FILTER(lang(?propernoun) = "se")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?essiveForm .
    ?essiveForm ontolex:representation ?essive ;
      wikibase:grammaticalFeature wd:Q148465 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralForm .
    ?accusativePluralForm ontolex:representation ?accusativePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralLocativeForm .
    ?pluralLocativeForm ontolex:representation ?pluralLocative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q202142 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIllativeForm .
    ?pluralIllativeForm ontolex:representation ?pluralIllative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralComitativeForm .
    ?pluralComitativeForm ontolex:representation ?pluralComitative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q838581 .
  }
}
