# tool: scribe-data
# All Estonian (Q9072) adverbs (Q380057) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adverb
  ?singularAblative
  ?singularIllative
  ?singularInessive
  ?singularElative
  ?singularAllative
  ?singularAdessive

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeForm .
    ?singularAblativeForm ontolex:representation ?singularAblative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIllativeForm .
    ?singularIllativeForm ontolex:representation ?singularIllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInessiveForm .
    ?singularInessiveForm ontolex:representation ?singularInessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularElativeForm .
    ?singularElativeForm ontolex:representation ?singularElative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAllativeForm .
    ?singularAllativeForm ontolex:representation ?singularAllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q655020 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAdessiveForm .
    ?singularAdessiveForm ontolex:representation ?singularAdessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q281954 .
  }
}
