# tool: scribe-data
# All Italian (Q652) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularFeminine
  ?singularMasculine
  ?singularFeminineSuperlative
  ?singularMasculineSuperlative

WHERE {
  ?lexeme dct:language wd:Q652 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineForm .
    ?singularFeminineForm ontolex:representation ?singularFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineForm .
    ?singularMasculineForm ontolex:representation ?singularMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularFeminineSuperlativeForm .
    ?singularFeminineSuperlativeForm ontolex:representation ?singularFeminineSuperlative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775415, wd:Q1817208 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineSuperlativeForm .
    ?singularMasculineSuperlativeForm ontolex:representation ?singularMasculineSuperlative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327, wd:Q1817208 .
  }
}
