# tool: scribe-data
# All Kurmanji (Q36163) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?pluperfectFirstPersonSingularSubjunctive
  ?pluperfectFirstPersonPluralSubjunctive
  ?pluperfectSecondPersonSingularSubjunctive
  ?pluperfectSecondPersonPluralSubjunctive
  ?pluperfectThirdPersonSingularSubjunctive
  ?pluperfectThirdPersonPluralSubjunctive

WHERE {
  ?lexeme dct:language wd:Q36163 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonSingularSubjunctiveForm .
    ?pluperfectFirstPersonSingularSubjunctiveForm ontolex:representation ?pluperfectFirstPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectFirstPersonPluralSubjunctiveForm .
    ?pluperfectFirstPersonPluralSubjunctiveForm ontolex:representation ?pluperfectFirstPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q21714344, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonSingularSubjunctiveForm .
    ?pluperfectSecondPersonSingularSubjunctiveForm ontolex:representation ?pluperfectSecondPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectSecondPersonPluralSubjunctiveForm .
    ?pluperfectSecondPersonPluralSubjunctiveForm ontolex:representation ?pluperfectSecondPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929049, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectThirdPersonSingularSubjunctiveForm .
    ?pluperfectThirdPersonSingularSubjunctiveForm ontolex:representation ?pluperfectThirdPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929074, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluperfectThirdPersonPluralSubjunctiveForm .
    ?pluperfectThirdPersonPluralSubjunctiveForm ontolex:representation ?pluperfectThirdPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q623742, wd:Q51929074, wd:Q146786, wd:Q473746 .
  }
}
