# tool: scribe-data
# All Kurmanji (Q36163) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?perfectFirstPersonSingularSubjunctive
  ?perfectFirstPersonPluralSubjunctive
  ?perfectSecondPersonSingularSubjunctive
  ?perfectSecondPersonPluralSubjunctive
  ?perfectThirdPersonSingularSubjunctive
  ?perfectThirdPersonPluralSubjunctive

WHERE {
  ?lexeme dct:language wd:Q36163 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonSingularSubjunctiveForm .
    ?perfectFirstPersonSingularSubjunctiveForm ontolex:representation ?perfectFirstPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectFirstPersonPluralSubjunctiveForm .
    ?perfectFirstPersonPluralSubjunctiveForm ontolex:representation ?perfectFirstPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q21714344, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonSingularSubjunctiveForm .
    ?perfectSecondPersonSingularSubjunctiveForm ontolex:representation ?perfectSecondPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectSecondPersonPluralSubjunctiveForm .
    ?perfectSecondPersonPluralSubjunctiveForm ontolex:representation ?perfectSecondPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929049, wd:Q146786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonSingularSubjunctiveForm .
    ?perfectThirdPersonSingularSubjunctiveForm ontolex:representation ?perfectThirdPersonSingularSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q110786, wd:Q473746 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?perfectThirdPersonPluralSubjunctiveForm .
    ?perfectThirdPersonPluralSubjunctiveForm ontolex:representation ?perfectThirdPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q625420, wd:Q51929074, wd:Q146786, wd:Q473746 .
  }
}
