# tool: scribe-data
# All Korean (Q9176) Adverbs
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?Postpositions

WHERE {
  VALUES ?postpositionTypes {wd:Q161873} # Postpositions

  ?lexeme dct:language wd:Q9176 ;  # Korean language
    wikibase:lexicalCategory ?postpositionTypes ;
    wikibase:lemma ?Postpositions .  # Return postpositions

}
