# tool: scribe-data
# All Estonian (Q9072) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?genitive
  ?inessive
  ?abessive
  ?genitiveSingular
  ?inessiveSingular
  ?abessiveSingular

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveForm .
    ?inessiveForm ontolex:representation ?inessive ;
      wikibase:grammaticalFeature wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessiveForm .
    ?abessiveForm ontolex:representation ?abessive ;
      wikibase:grammaticalFeature wd:Q319822 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSingularForm .
    ?inessiveSingularForm ontolex:representation ?inessiveSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessiveSingularForm .
    ?abessiveSingularForm ontolex:representation ?abessiveSingular ;
      wikibase:grammaticalFeature wd:Q319822, wd:Q110786 .
  }
}
