# tool: scribe-data
# All German (Q188) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?nominative
  ?accusative
  ?nominativeFeminine
  ?nominativeNeuter
  ?accusativeFeminine
  ?accusativeNeuter

WHERE {
  ?lexeme dct:language wd:Q188 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFeminineForm .
    ?nominativeFeminineForm ontolex:representation ?nominativeFeminine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterForm .
    ?nominativeNeuterForm ontolex:representation ?nominativeNeuter ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineForm .
    ?accusativeFeminineForm ontolex:representation ?accusativeFeminine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterForm .
    ?accusativeNeuterForm ontolex:representation ?accusativeNeuter ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461 .
  }
}
