# tool: scribe-data
# All Basque (Q8752) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?allativeInanimateSingular
  ?allativeInanimatePlural
  ?allativeAnimateSingular
  ?allativeAnimatePlural

WHERE {
  ?lexeme dct:language wd:Q8752 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeInanimateSingularForm .
    ?allativeInanimateSingularForm ontolex:representation ?allativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeInanimatePluralForm .
    ?allativeInanimatePluralForm ontolex:representation ?allativeInanimatePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeAnimateSingularForm .
    ?allativeAnimateSingularForm ontolex:representation ?allativeAnimateSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927507, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeAnimatePluralForm .
    ?allativeAnimatePluralForm ontolex:representation ?allativeAnimatePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927507, wd:Q146786 .
  }
}
