# tool: scribe-data
# All Russian (Q7737) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?partitive
  ?prepositionalSingular
  ?prepositionalPlural
  ?vocativeSingular
  ?partitiveSingular

WHERE {
  ?lexeme dct:language wd:Q7737 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveForm .
    ?partitiveForm ontolex:representation ?partitive ;
      wikibase:grammaticalFeature wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalSingularForm .
    ?prepositionalSingularForm ontolex:representation ?prepositionalSingular ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?prepositionalPluralForm .
    ?prepositionalPluralForm ontolex:representation ?prepositionalPlural ;
      wikibase:grammaticalFeature wd:Q2114906, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeSingularForm .
    ?vocativeSingularForm ontolex:representation ?vocativeSingular ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q110786 .
  }
}
