# tool: scribe-data
# All Latin (Q397) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?genitivePluralFeminine
  ?genitivePluralMasculine
  ?genitivePluralNeuter

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralFeminineForm .
    ?genitivePluralFeminineForm ontolex:representation ?genitivePluralFeminine ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralMasculineForm .
    ?genitivePluralMasculineForm ontolex:representation ?genitivePluralMasculine ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralNeuterForm .
    ?genitivePluralNeuterForm ontolex:representation ?genitivePluralNeuter ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775461 .
  }
}
