# tool: scribe-data
# All Latin (Q397) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?genitiveSingular
  ?dativeSingular
  ?dativePlural
  ?genitiveFemininePlural
  ?genitiveMasculinePlural
  ?genitiveNeuterPlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePluralForm .
    ?genitiveFemininePluralForm ontolex:representation ?genitiveFemininePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveMasculinePluralForm .
    ?genitiveMasculinePluralForm ontolex:representation ?genitiveMasculinePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPluralForm .
    ?genitiveNeuterPluralForm ontolex:representation ?genitiveNeuterPlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q146786 .
  }
}
