# tool: scribe-data
# All Latin (Q397) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?accusativeFeminineSingular
  ?accusativeFemininePlural
  ?accusativeMasculineSingular
  ?accusativeMasculinePlural
  ?accusativeNeuterSingular
  ?accusativeNeuterPlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineSingularForm .
    ?accusativeFeminineSingularForm ontolex:representation ?accusativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFemininePluralForm .
    ?accusativeFemininePluralForm ontolex:representation ?accusativeFemininePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineSingularForm .
    ?accusativeMasculineSingularForm ontolex:representation ?accusativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculinePluralForm .
    ?accusativeMasculinePluralForm ontolex:representation ?accusativeMasculinePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterSingularForm .
    ?accusativeNeuterSingularForm ontolex:representation ?accusativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPluralForm .
    ?accusativeNeuterPluralForm ontolex:representation ?accusativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q146786 .
  }
}
