# tool: scribe-data
# All Latin (Q397) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?nominativePluralFeminine
  ?nominativePluralMasculine
  ?nominativePluralNeuter
  ?accusativePluralFeminine
  ?accusativePluralMasculine
  ?accusativePluralNeuter

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralFeminineForm .
    ?nominativePluralFeminineForm ontolex:representation ?nominativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralMasculineForm .
    ?nominativePluralMasculineForm ontolex:representation ?nominativePluralMasculine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralNeuterForm .
    ?nominativePluralNeuterForm ontolex:representation ?nominativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralFeminineForm .
    ?accusativePluralFeminineForm ontolex:representation ?accusativePluralFeminine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineForm .
    ?accusativePluralMasculineForm ontolex:representation ?accusativePluralMasculine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralNeuterForm .
    ?accusativePluralNeuterForm ontolex:representation ?accusativePluralNeuter ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775461 .
  }
}
