# tool: scribe-data
# Enter this query at https://query.wikidata.org/
# Retrieve Estonian Adverbs with Grammatical Cases (Singular)

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lemma
  ?nominativeSingular
  ?genitiveSingular
  ?partitiveSingular
  ?illativeSingular
  ?inessiveSingular
  ?elativeSingular
  ?allativeSingular
  ?adessiveSingular
  ?ablativeSingular
  ?translativeSingular
  ?essiveSingular
  ?abessiveSingular
  ?comitativeSingular
WHERE {
  ?lexeme dct:language wd:Q9072 ;
          wikibase:lexicalCategory wd:Q380057 ;
          wikibase:lemma ?lemma .
  FILTER(lang(?lemma) = "et")

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularForm .
    ?nominativeSingularForm ontolex:representation ?nominativeSingular ;
    wikibase:grammaticalFeature wd:Q131105 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
    wikibase:grammaticalFeature wd:Q146233 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
    wikibase:grammaticalFeature wd:Q857325 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativeSingularForm .
    ?illativeSingularForm ontolex:representation ?illativeSingular ;
    wikibase:grammaticalFeature wd:Q474668 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSingularForm .
    ?inessiveSingularForm ontolex:representation ?inessiveSingular ;
    wikibase:grammaticalFeature wd:Q282031 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSingularForm .
    ?elativeSingularForm ontolex:representation ?elativeSingular ;
    wikibase:grammaticalFeature wd:Q394253 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeSingularForm .
    ?allativeSingularForm ontolex:representation ?allativeSingular ;
    wikibase:grammaticalFeature wd:Q655020 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adessiveSingularForm .
    ?adessiveSingularForm ontolex:representation ?adessiveSingular ;
    wikibase:grammaticalFeature wd:Q281954 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeSingularForm .
    ?ablativeSingularForm ontolex:representation ?ablativeSingular ;
    wikibase:grammaticalFeature wd:Q156986 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?translativeSingularForm .
    ?translativeSingularForm ontolex:representation ?translativeSingular ;
    wikibase:grammaticalFeature wd:Q950170 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?essiveSingularForm .
    ?essiveSingularForm ontolex:representation ?essiveSingular ;
    wikibase:grammaticalFeature wd:Q148465 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?abessiveSingularForm .
    ?abessiveSingularForm ontolex:representation ?abessiveSingular ;
    wikibase:grammaticalFeature wd:Q319822 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeSingularForm .
    ?comitativeSingularForm ontolex:representation ?comitativeSingular ;
    wikibase:grammaticalFeature wd:Q838581 ;
    wikibase:grammaticalFeature wd:Q110786 .
  }
}
