# tool: scribe-data
# All Slovak (Q9058) adjectives and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adjective
  ?feminineAccusativeSingular
  ?masculineAnimateAccusativeSingular
  ?masculineInanimateAccusativeSingular
  ?neuterAccusativeSingular
  ?masculinePersonalAccusativePlural
  ?notMasculinePersonalAccusativePlural

WHERE {
  ?lexeme dct:language wd:Q9058;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective .

  # MARK: Accustive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineAccusativeSingularForm .
    ?feminineAccusativeSingularForm ontolex:representation ?feminineAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146078, wd:Q110786, wd:Q3482678 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineAnimateAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q54020116, wd:Q146078, wd:Q110786, wd:Q3482678 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineAccusativeSingularForm .
    ?masculineAccusativeSingularForm ontolex:representation ?masculineInanimateAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q52943434, wd:Q146078, wd:Q110786, wd:Q3482678 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterAccusativeSingularForm .
    ?neuterAccusativeSingularForm ontolex:representation ?neuterAccusativeSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q146078, wd:Q110786, wd:Q3482678 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePersonalAccusativePluralForm .
    ?masculinePersonalAccusativePluralForm ontolex:representation ?masculinePersonalAccusativePlural ;
      wikibase:grammaticalFeature wd:Q27918551, wd:Q146078, wd:Q146786, wd:Q3482678 .
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?notMasculinePersonalAccusativePluralForm .
    ?notMasculinePersonalAccusativePluralForm ontolex:representation ?notMasculinePersonalAccusativePlural ;
      wikibase:grammaticalFeature wd:Q54152717, wd:Q146078, wd:Q146786, wd:Q3482678 .
  } .
}
