# tool: scribe-data
# All Estonian verbs and the corresponding forms per case.
# Enter this query at https://query.wikidata.org/

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?conditionalPresentFirstSingular
  ?conditionalPresentSecondSingular
  ?conditionalPresentThirdSingular
  ?conditionalPresentFirstPlural
  ?conditionalPresentSecondPlural
  ?conditionalPresentThirdPlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  # MARK: Conditional Present - First Person Singular
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentFirstSingularForm .
    ?conditionalPresentFirstSingularForm ontolex:representation ?conditionalPresentFirstSingular ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  # MARK: Conditional Present - Second Person Singular
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentSecondSingularForm .
    ?conditionalPresentSecondSingularForm ontolex:representation ?conditionalPresentSecondSingular ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  # MARK: Conditional Present - Third Person Singular
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentThirdSingularForm .
    ?conditionalPresentThirdSingularForm ontolex:representation ?conditionalPresentThirdSingular ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  # MARK: Conditional Present - First Person Plural
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentFirstPluralForm .
    ?conditionalPresentFirstPluralForm ontolex:representation ?conditionalPresentFirstPlural ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  # MARK: Conditional Present - Second Person Plural
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentSecondPluralForm .
    ?conditionalPresentSecondPluralForm ontolex:representation ?conditionalPresentSecondPlural ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  # MARK: Conditional Present - Third Person Plural
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conditionalPresentThirdPluralForm .
    ?conditionalPresentThirdPluralForm ontolex:representation ?conditionalPresentThirdPlural ;
      wikibase:grammaticalFeature wd:Q625581 ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q146786 .
  }
}
