# tool: scribe-data
# All Ukrainian (Q8798) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularNominativeFeminine
  ?singularNominativeMasculine
  ?singularNominativeNeuter
  ?singularGenitiveFeminine
  ?singularGenitiveMasculine
  ?singularGenitiveNeuter

WHERE {
  ?lexeme dct:language wd:Q8798 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeFeminineForm .
    ?singularNominativeFeminineForm ontolex:representation ?singularNominativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeMasculineForm .
    ?singularNominativeMasculineForm ontolex:representation ?singularNominativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeNeuterForm .
    ?singularNominativeNeuterForm ontolex:representation ?singularNominativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveFeminineForm .
    ?singularGenitiveFeminineForm ontolex:representation ?singularGenitiveFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveMasculineForm .
    ?singularGenitiveMasculineForm ontolex:representation ?singularGenitiveMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveNeuterForm .
    ?singularGenitiveNeuterForm ontolex:representation ?singularGenitiveNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775461 .
  }
}
