# tool: scribe-data
# All Ukrainian (Q8798) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularLocativeFeminine
  ?singularLocativeMasculine
  ?singularLocativeNeuter
  ?singularVocativeFeminine
  ?singularVocativeMasculine
  ?singularVocativeNeuter

WHERE {
  ?lexeme dct:language wd:Q8798 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeFeminineForm .
    ?singularLocativeFeminineForm ontolex:representation ?singularLocativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeMasculineForm .
    ?singularLocativeMasculineForm ontolex:representation ?singularLocativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularLocativeNeuterForm .
    ?singularLocativeNeuterForm ontolex:representation ?singularLocativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q202142, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeFeminineForm .
    ?singularVocativeFeminineForm ontolex:representation ?singularVocativeFeminine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeMasculineForm .
    ?singularVocativeMasculineForm ontolex:representation ?singularVocativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularVocativeNeuterForm .
    ?singularVocativeNeuterForm ontolex:representation ?singularVocativeNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q185077, wd:Q1775461 .
  }
}
