# tool: scribe-data
# All Estonian (Q9072) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularNominative
  ?singularGenitive
  ?singularAblative
  ?singularIllative
  ?singularAdessive
  ?singularTranslative

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeForm .
    ?singularAblativeForm ontolex:representation ?singularAblative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIllativeForm .
    ?singularIllativeForm ontolex:representation ?singularIllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAdessiveForm .
    ?singularAdessiveForm ontolex:representation ?singularAdessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q281954 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularTranslativeForm .
    ?singularTranslativeForm ontolex:representation ?singularTranslative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q950170 .
  }
}
