# tool: scribe-data
# All Estonian (Q9072) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?pluralAblative
  ?pluralIllative
  ?pluralInessive
  ?pluralAllative
  ?pluralAdessive
  ?pluralTranslative

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeForm .
    ?pluralAblativeForm ontolex:representation ?pluralAblative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIllativeForm .
    ?pluralIllativeForm ontolex:representation ?pluralIllative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralInessiveForm .
    ?pluralInessiveForm ontolex:representation ?pluralInessive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAllativeForm .
    ?pluralAllativeForm ontolex:representation ?pluralAllative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q655020 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAdessiveForm .
    ?pluralAdessiveForm ontolex:representation ?pluralAdessive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q281954 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralTranslativeForm .
    ?pluralTranslativeForm ontolex:representation ?pluralTranslative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q950170 .
  }
}
