# tool: scribe-data
# All Dagbani (Q32238) adverbs (Q380057) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adverb
  ?singular
  ?adverbOfManner
  ?phrase
  ?singularPlural

WHERE {
  ?lexeme dct:language wd:Q32238 ;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbOfMannerForm .
    ?adverbOfMannerForm ontolex:representation ?adverbOfManner ;
      wikibase:grammaticalFeature wd:Q113320444 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?phraseForm .
    ?phraseForm ontolex:representation ?phrase ;
      wikibase:grammaticalFeature wd:Q187931 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPluralForm .
    ?singularPluralForm ontolex:representation ?singularPlural ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146786 .
  }
}
