# tool: scribe-data
# All Dagbani (Q32238) adverbs (Q380057) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adverb
  ?present
  ?past
  ?singular
  ?plural
  ?adverbial
  ?adverbialLocation
  ?adverbOfManner
  ?locativeAdverb
  ?phrase

WHERE {
  ?lexeme dct:language wd:Q32238 ;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presentForm .
    ?presentForm ontolex:representation ?present ;
      wikibase:grammaticalFeature wd:Q192613 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastForm .
    ?pastForm ontolex:representation ?past ;
      wikibase:grammaticalFeature wd:Q1994301 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbialForm .
    ?adverbialForm ontolex:representation ?adverbial ;
      wikibase:grammaticalFeature wd:Q380012 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbialLocationForm .
    ?adverbialLocationForm ontolex:representation ?adverbialLocation ;
      wikibase:grammaticalFeature wd:Q5978303 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbOfMannerForm .
    ?adverbOfMannerForm ontolex:representation ?adverbOfManner ;
      wikibase:grammaticalFeature wd:Q113320444 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeAdverbForm .
    ?locativeAdverbForm ontolex:representation ?locativeAdverb ;
      wikibase:grammaticalFeature wd:Q1522423 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?phraseForm .
    ?phraseForm ontolex:representation ?phrase ;
      wikibase:grammaticalFeature wd:Q187931 .
  }
}
