# tool: scribe-data
# All Arabic (Q13955) verbs and a portion of the currently implemented tenses for each.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?presFPS ?presSPSM ?presSPSF ?presTPSM ?presTPSF
  ?presSPD ?presTPDM ?presTPDF
  ?presFPP ?presSPPM ?presSPPF

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  # MARK: Present

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presFPSForm .
    ?presFPSForm ontolex:representation ?presFPS ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presSPSMForm .
    ?presSPSMForm ontolex:representation ?presSPSM ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presSPSFForm .
    ?presSPSFForm ontolex:representation ?presSPSF ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presTPSMForm .
    ?presTPSMForm ontolex:representation ?presTPSM ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presTPSFForm .
    ?presTPSFForm ontolex:representation ?presTPSF ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110786 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presSPDForm .
    ?presSPDForm ontolex:representation ?presSPD ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q110022 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presTPDMForm .
    ?presTPDMForm ontolex:representation ?presTPDM ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110022 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presTPDFForm .
    ?presTPDFForm ontolex:representation ?presTPDF ;
      wikibase:grammaticalFeature wd:Q51929074 ;
      wikibase:grammaticalFeature wd:Q110022 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presFPPForm .
    ?presFPPForm ontolex:representation ?presFPP ;
      wikibase:grammaticalFeature wd:Q21714344 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presSPPMForm .
    ?presSPPMForm ontolex:representation ?presSPPM ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q499327 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presSPPFForm .
    ?presSPPFForm ontolex:representation ?presSPPF ;
      wikibase:grammaticalFeature wd:Q51929049 ;
      wikibase:grammaticalFeature wd:Q146786 ;
      wikibase:grammaticalFeature wd:Q1775415 ;
      wikibase:grammaticalFeature wd:Q682111 ;
      wikibase:grammaticalFeature wd:Q12230930
  } .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]".
  }
}
