# tool: scribe-data
# All Arabic (Q13955) verbs and a portion of the currently implemented tenses for each.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?pastFPS ?pastSPSM ?pastSPSF ?pastTPSM ?pastTPSF
  ?pastSPD ?pastTPDM ?pastTPDF
  ?pastFPP ?pastSPPM ?pastSPPF

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  # MARK: Performative Past

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPSForm .
    ?pastFPSForm ontolex:representation ?pastFPS ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSMForm .
    ?pastSPSMForm ontolex:representation ?pastSPSM ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q499327, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPSFForm .
    ?pastSPSFForm ontolex:representation ?pastSPSF ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, wd:Q1775415, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSMForm .
    ?pastTPSMForm ontolex:representation ?pastTPSM ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, wd:Q499327, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPSFForm .
    ?pastTPSFForm ontolex:representation ?pastTPSF ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, wd:Q1775415, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPDForm .
    ?pastSPDForm ontolex:representation ?pastSPD ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110022, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPDMForm .
    ?pastTPDMForm ontolex:representation ?pastTPDM ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110022, wd:Q499327, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastTPDFForm .
    ?pastTPDFForm ontolex:representation ?pastTPDF ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110022, wd:Q1775415, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastFPPForm .
    ?pastFPPForm ontolex:representation ?pastFPP ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPMForm .
    ?pastSPPMForm ontolex:representation ?pastSPPM ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q499327, wd:Q1317831, wd:Q124351233 .
  } 

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastSPPFForm .
    ?pastSPPFForm ontolex:representation ?pastSPPF ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, wd:Q1775415, wd:Q1317831, wd:Q124351233 .
  } 
}
