# tool: scribe-data
# All French (Q150) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineSingularCombinedPastParticiple
  ?masculinePluralCombinedPastParticiple
  ?masculinePastSingularParticiple
  ?masculinePastPluralParticiple
  ?masculinePastSingularParticipleCombinedPastParticiple

WHERE {
  ?lexeme dct:language wd:Q150 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSingularCombinedPastParticipleForm .
    ?masculineSingularCombinedPastParticipleForm ontolex:representation ?masculineSingularCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q110786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePluralCombinedPastParticipleForm .
    ?masculinePluralCombinedPastParticipleForm ontolex:representation ?masculinePluralCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q146786, wd:Q12717679 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastSingularParticipleForm .
    ?masculinePastSingularParticipleForm ontolex:representation ?masculinePastSingularParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastPluralParticipleForm .
    ?masculinePastPluralParticipleForm ontolex:representation ?masculinePastPluralParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculinePastSingularParticipleCombinedPastParticipleForm .
    ?masculinePastSingularParticipleCombinedPastParticipleForm ontolex:representation ?masculinePastSingularParticipleCombinedPastParticiple ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1994301, wd:Q110786, wd:Q814722, wd:Q12717679 .
  }
}
