# tool: scribe-data
# All Ukrainian (Q8798) prepositions and their corresponding cases.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?preposition
  ?case

WHERE {
  # All Ukrainian prepositions.
  ?lexeme dct:language wd:Q8798 ;
    wikibase:lexicalCategory wd:Q4833830 ;
    wikibase:lemma ?lemma .

  # MARK: Corresponding Case

  OPTIONAL {
    ?lexeme wdt:P5713 ?caseForm .
  } .

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]".
    ?lemma rdfs:label ?preposition .
    ?caseForm rdfs:label ?case .
  }
}
