# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?accusativeMasculine
  ?accusativeMasculineDefinite
  ?accusativeMasculineDefiniteSingular
  ?accusativeMasculineDefiniteDual
  ?accusativeMasculineSingularConstruct
  ?accusativeMasculineDualConstruct

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineForm .
    ?accusativeMasculineForm ontolex:representation ?accusativeMasculine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineDefiniteForm .
    ?accusativeMasculineDefiniteForm ontolex:representation ?accusativeMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineDefiniteSingularForm .
    ?accusativeMasculineDefiniteSingularForm ontolex:representation ?accusativeMasculineDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineDefiniteDualForm .
    ?accusativeMasculineDefiniteDualForm ontolex:representation ?accusativeMasculineDefiniteDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q53997851, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineSingularConstructForm .
    ?accusativeMasculineSingularConstructForm ontolex:representation ?accusativeMasculineSingularConstruct ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineDualConstructForm .
    ?accusativeMasculineDualConstructForm ontolex:representation ?accusativeMasculineDualConstruct ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q110022, wd:Q1641446 .
  }
}
