# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?accusativeDual
  ?genitivePluralConstruct
  ?accusativeMasculineIndefinite
  ?accusativePluralConstruct
  ?genitiveAccusativeMasculineDual
  ?accusativeFeminineDualConstruct

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeDualForm .
    ?accusativeDualForm ontolex:representation ?accusativeDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralConstructForm .
    ?genitivePluralConstructForm ontolex:representation ?genitivePluralConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeMasculineIndefiniteForm .
    ?accusativeMasculineIndefiniteForm ontolex:representation ?accusativeMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralConstructForm .
    ?accusativePluralConstructForm ontolex:representation ?accusativePluralConstruct ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveAccusativeMasculineDualForm .
    ?genitiveAccusativeMasculineDualForm ontolex:representation ?genitiveAccusativeMasculineDual ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146078, wd:Q499327, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineDualConstructForm .
    ?accusativeFeminineDualConstructForm ontolex:representation ?accusativeFeminineDualConstruct ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q110022, wd:Q1641446 .
  }
}
