# tool: scribe-data
# All Punjabi Gurmukhi (Q58635) verbs.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  ?lexeme
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb

WHERE {
  VALUES ?verbTypes {wd:Q24905}  # Verb

  # Get all lexemes for Punjabi (Gurmukhi)
  ?lexeme dct:language wd:Q58635 ;               # Punjabi (Gurmukhi)
          wikibase:lexicalCategory ?verbTypes ;   # Filter for verbs
          wikibase:lemma ?verb .

  # Filter for the Punjabi language code (pa)
  FILTER(lang(?verb) = "pnb")

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE]".
  }
}
