# tool: scribe-data
# All Latin (Q397) verbs with active plural.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  (GROUP_CONCAT(DISTINCT ?activePlural; SEPARATOR=", ") AS ?activePluralForms)
  
WHERE {
  # Latin verb lexemes
  ?lexeme dct:language wd:Q397 ;
          wikibase:lexicalCategory wd:Q24905 ;  # Verb
          wikibase:lemma ?verb .

  # Active Plural
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?formActivePlural .
    ?formActivePlural ontolex:representation ?activePlural ;
    wikibase:grammaticalFeature wd:Q146786, wd:Q1317831 .  # Plural, Active voice
    FILTER(LANG(?activePlural) = "la")
    
  }SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],la".
  }
}
GROUP BY ?lexeme ?verb
