# tool: scribe-data
# All Bengali (Bangla Q9610) nouns and their forms in the various cases.
# Enter this query at https://query.wikidata.org/.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?nominative
  ?genitive
  ?accusative
  ?locative

WHERE {
  VALUES ?nounTypes {wd:Q1084 wd:Q147276} # Nouns and proper nouns

  ?lexeme dct:language wd:Q9610 ;
    wikibase:lexicalCategory ?nounTypes ;

  # MARK: Nminative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nomForm .
    ?nomForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 ;
  } .

  # MARK: Genitive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genForm .
    ?genForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 ;
  } .

  # MARK: Accusative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accForm .
    ?accForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q146078 ;
  } .

  # MARK: Locative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locForm .
    ?locForm ontolex:representation ?locative ;
      wikibase:grammaticalFeature wd:Q202142 ;
  } .
}
