# tool: scribe-data
# All Dagbani (Q32238) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?nominative
  ?genitive
  ?oblique

WHERE {
  ?lexeme dct:language wd:Q32238 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueForm .
    ?obliqueForm ontolex:representation ?oblique ;
      wikibase:grammaticalFeature wd:Q1233197 .
  }
}
