# tool: scribe-data
# All swedish (Q9027) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?pronouns
    ?singularNominativeMasculine
  ?singularNeuterDefinite
  ?genitive
  ?singularObliqueMasculine
  ?vocative
  ?nominative
  ?singularCommon
  ?singularMasculine
  ?singularNeuter
  ?plural
  ?singularCommonFeminineMasculine
  ?oblique
  ?singularGenitiveMasculine

WHERE {
  ?lexeme dct:language wd:Q9027 ;
  wikibase:lexicalCategory wd:Q36224 ;
  wikibase:lemma ?pronouns .
  FILTER(lang(?pronouns) = "sv")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeMasculineForm .
    ?singularNominativeMasculineForm ontolex:representation ?singularNominativeMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterDefiniteForm .
    ?singularNeuterDefiniteForm ontolex:representation ?singularNeuterDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveForm .
    ?genitiveForm ontolex:representation ?genitive ;
      wikibase:grammaticalFeature wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularObliqueMasculineForm .
    ?singularObliqueMasculineForm ontolex:representation ?singularObliqueMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1233197, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeForm .
    ?vocativeForm ontolex:representation ?vocative ;
      wikibase:grammaticalFeature wd:Q185077 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeForm .
    ?nominativeForm ontolex:representation ?nominative ;
      wikibase:grammaticalFeature wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularCommonForm .
    ?singularCommonForm ontolex:representation ?singularCommon ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1305037 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularMasculineForm .
    ?singularMasculineForm ontolex:representation ?singularMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNeuterForm .
    ?singularNeuterForm ontolex:representation ?singularNeuter ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularCommonFeminineMasculineForm .
    ?singularCommonFeminineMasculineForm ontolex:representation ?singularCommonFeminineMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q1305037, wd:Q1775415, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueForm .
    ?obliqueForm ontolex:representation ?oblique ;
      wikibase:grammaticalFeature wd:Q1233197 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveMasculineForm .
    ?singularGenitiveMasculineForm ontolex:representation ?singularGenitiveMasculine ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q499327 .
  }
}
