# tool: scribe-data
# All Arabic (Q13955) nouns and their grammatical features.
# Enter this query at https://query.wikidata.org/.

SELECT ?lexemeId ?actualWord (GROUP_CONCAT(?featureLabel; separator=", ") AS ?features) WHERE {
  # MARK: Filter nouns
  ?lexeme dct:language wd:Q13955;  # Language: Arabic (Q13955)
          wikibase:lexicalCategory wd:Q1084.  # Lexical Category: Noun (Q1084)

  # MARK: Retrieve forms
  ?lexeme ontolex:lexicalForm ?form.

  # MARK: Create ID
  BIND(STRAFTER(STR(?form), "entity/") AS ?lexemeId).

  # MARK: Get word
  ?form ontolex:representation ?actualWord.

  # MARK: Get features
  OPTIONAL { ?form wikibase:grammaticalFeature ?feature. }

  # MARK: Labeling
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
    ?feature rdfs:label ?featureLabel.
  }
}
# MARK: Grouping
GROUP BY ?lexemeId ?actualWord
# MARK: Order results
ORDER BY ?lexemeId
