# tool: scribe-data
# All Dagbani (Q32238) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?noun
  ?plural

WHERE {
  ?lexeme dct:language wd:Q32238 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun .

  # MARK: Plural

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }
}
