# tool: scribe-data
# All Arabic (Q13955) prepositions (Q4833830) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?preposition
  ?pluralFeminineSecondPerson
  ?pluralFeminineThirdPerson

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q4833830 ;
    wikibase:lemma ?preposition ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineSecondPersonForm .
    ?pluralFeminineSecondPersonForm ontolex:representation ?pluralFeminineSecondPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralFeminineThirdPersonForm .
    ?pluralFeminineThirdPersonForm ontolex:representation ?pluralFeminineThirdPerson ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q1775415, wd:Q51929074 .
  }
}
