# tool: scribe-data
# All Spanish (Q1321) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?feminineSingular
  ?femininePlural
  ?feminineMasculineNeuter
  ?feminineMasculineSingular
  ?feminineMasculinePlural

WHERE {
  ?lexeme dct:language wd:Q1321 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSingularForm .
    ?feminineSingularForm ontolex:representation ?feminineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?femininePluralForm .
    ?femininePluralForm ontolex:representation ?femininePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineNeuterForm .
    ?feminineMasculineNeuterForm ontolex:representation ?feminineMasculineNeuter ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineSingularForm .
    ?feminineMasculineSingularForm ontolex:representation ?feminineMasculineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculinePluralForm .
    ?feminineMasculinePluralForm ontolex:representation ?feminineMasculinePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q146786 .
  }
}
