# tool: scribe-data
# All Hindi (from Hindustani Q11051) verbs and the currently implemented forms for each.
# Enter this query at https://query.wikidata.org/.

# Note: We need to filter for "hi" to remove Urdu (ur) words.

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?infinitive
  ?directCase
  ?gerund
  ?intransitivePhase
  ?basicPhase
  ?conjParticiple
  ?adverbial
  ?absConstruction
  ?accusative
  ?ergative
  ?additivePhase

WHERE {
  # MARK: Infinitive

  ?lexeme dct:language wd:Q11051 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?infinitive .
    FILTER(lang(?infinitive) = "hi") .

  # MARK: Direct Case

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directCaseForm .
    ?directCaseForm ontolex:representation ?directCase ;
      wikibase:grammaticalFeature wd:Q1751855 .
      FILTER(LANG(?directCase) = "hi") .
  } .

  # MARK: Gerund

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?gerundForm .
    ?gerundForm ontolex:representation ?gerund ;
      wikibase:grammaticalFeature wd:Q1923028 .
      FILTER(LANG(?gerund) = "hi") .
  } .

  # MARK: Intransitive Phase

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?intransitivePhaseForm .
    ?intransitivePhaseForm ontolex:representation ?intransitivePhase ;
      wikibase:grammaticalFeature wd:Q113330736 .
      FILTER(LANG(?intransitivePhase) = "hi") .
  } .

  # MARK: Basic Phase

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?basicPhaseForm .
    ?basicPhaseForm ontolex:representation ?basicPhase ;
      wikibase:grammaticalFeature wd:Q113330960 .
      FILTER(LANG(?basicPhase) = "hi") .
  } .

# MARK: Conjunctive Participle

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?conjParticipleForm .
    ?conjParticipleForm ontolex:representation ?conjParticiple ;
      wikibase:grammaticalFeature wd:Q113133303 .
      FILTER(LANG(?conjParticiple) = "hi") .
  } .

  # MARK: Adverbial

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?adverbialForm .
    ?adverbialForm ontolex:representation ?adverbial ;
      wikibase:grammaticalFeature wd:Q380012 .
      FILTER(LANG(?adverbial) = "hi") .
  } .

  # MARK: Absolute Construction

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?absConstructionForm .
    ?absConstructionForm ontolex:representation ?absConstruction ;
      wikibase:grammaticalFeature wd:Q4669807 .
      FILTER(LANG(?absConstruction) = "hi") .
  } .

  # MARK: Accusative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeForm .
    ?accusativeForm ontolex:representation ?accusative ;
      wikibase:grammaticalFeature wd:Q1233197 .
      FILTER(LANG(?accusative) = "hi") .
  } .

  # MARK: Ergative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ergativeForm .
    ?ergativeForm ontolex:representation ?ergative ;
      wikibase:grammaticalFeature wd:Q1233197 .
      FILTER(LANG(?ergative) = "hi") .
  } .
}
