# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?accusativePluralFeminineIndefinite
  ?accusativePluralFeminineDefinite
  ?accusativePluralMasculineIndefinite
  ?accusativePluralMasculineDefinite

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralFeminineIndefiniteForm .
    ?accusativePluralFeminineIndefiniteForm ontolex:representation ?accusativePluralFeminineIndefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775415, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralFeminineDefiniteForm .
    ?accusativePluralFeminineDefiniteForm ontolex:representation ?accusativePluralFeminineDefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q1775415, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineIndefiniteForm .
    ?accusativePluralMasculineIndefiniteForm ontolex:representation ?accusativePluralMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativePluralMasculineDefiniteForm .
    ?accusativePluralMasculineDefiniteForm ontolex:representation ?accusativePluralMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q146786, wd:Q499327, wd:Q53997851 .
  }
}
