# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?nominativeSingularConstruct
  ?nominativePluralConstruct
  ?nominativeDualConstruct
  ?pausalIndefiniteSingular
  ?pausalDefiniteSingular
  ?nominativePausalMasculineIndefiniteSingular

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeSingularConstructForm .
    ?nominativeSingularConstructForm ontolex:representation ?nominativeSingularConstruct ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralConstructForm .
    ?nominativePluralConstructForm ontolex:representation ?nominativePluralConstruct ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDualConstructForm .
    ?nominativeDualConstructForm ontolex:representation ?nominativeDualConstruct ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110022, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalIndefiniteSingularForm .
    ?pausalIndefiniteSingularForm ontolex:representation ?pausalIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalDefiniteSingularForm .
    ?pausalDefiniteSingularForm ontolex:representation ?pausalDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePausalMasculineIndefiniteSingularForm .
    ?nominativePausalMasculineIndefiniteSingularForm ontolex:representation ?nominativePausalMasculineIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q117262361, wd:Q499327, wd:Q53997857, wd:Q110786 .
  }
}
