# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?singularNominativeFeminineIndefinite
  ?singularNominativeFeminineDefinite
  ?singularNominativeMasculineIndefinite
  ?singularNominativeMasculineDefinite

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeFeminineIndefiniteForm .
    ?singularNominativeFeminineIndefiniteForm ontolex:representation ?singularNominativeFeminineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775415, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeFeminineDefiniteForm .
    ?singularNominativeFeminineDefiniteForm ontolex:representation ?singularNominativeFeminineDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q1775415, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeMasculineIndefiniteForm .
    ?singularNominativeMasculineIndefiniteForm ontolex:representation ?singularNominativeMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeMasculineDefiniteForm .
    ?singularNominativeMasculineDefiniteForm ontolex:representation ?singularNominativeMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105, wd:Q499327, wd:Q53997851 .
  }
}
