# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?accusativeIndefiniteSingular
  ?accusativeIndefinitePlural
  ?accusativeIndefiniteDual
  ?accusativeDefiniteSingular
  ?accusativeDefinitePlural
  ?accusativeDefiniteDual

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefiniteSingularForm .
    ?accusativeIndefiniteSingularForm ontolex:representation ?accusativeIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefinitePluralForm .
    ?accusativeIndefinitePluralForm ontolex:representation ?accusativeIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefiniteDualForm .
    ?accusativeIndefiniteDualForm ontolex:representation ?accusativeIndefiniteDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeDefiniteSingularForm .
    ?accusativeDefiniteSingularForm ontolex:representation ?accusativeDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeDefinitePluralForm .
    ?accusativeDefinitePluralForm ontolex:representation ?accusativeDefinitePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeDefiniteDualForm .
    ?accusativeDefiniteDualForm ontolex:representation ?accusativeDefiniteDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997851, wd:Q110022 .
  }
}
