# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?pausalMasculine
  ?pausalMasculineSingular
  ?pausalMasculinePlural
  ?pausalMasculineDefiniteSingular
  ?pausalMasculineDefinitePlural

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalMasculineForm .
    ?pausalMasculineForm ontolex:representation ?pausalMasculine ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalMasculineSingularForm .
    ?pausalMasculineSingularForm ontolex:representation ?pausalMasculineSingular ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalMasculinePluralForm .
    ?pausalMasculinePluralForm ontolex:representation ?pausalMasculinePlural ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalMasculineDefiniteSingularForm .
    ?pausalMasculineDefiniteSingularForm ontolex:representation ?pausalMasculineDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q499327, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalMasculineDefinitePluralForm .
    ?pausalMasculineDefinitePluralForm ontolex:representation ?pausalMasculineDefinitePlural ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q499327, wd:Q53997851, wd:Q146786 .
  }
}
