# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?genitivePluralFeminineIndefinite
  ?genitivePluralFeminineDefinite
  ?genitivePluralMasculineIndefinite
  ?genitivePluralMasculineDefinite

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralFeminineIndefiniteForm .
    ?genitivePluralFeminineIndefiniteForm ontolex:representation ?genitivePluralFeminineIndefinite ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775415, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralFeminineDefiniteForm .
    ?genitivePluralFeminineDefiniteForm ontolex:representation ?genitivePluralFeminineDefinite ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1775415, wd:Q53997851 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralMasculineIndefiniteForm .
    ?genitivePluralMasculineIndefiniteForm ontolex:representation ?genitivePluralMasculineIndefinite ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q499327, wd:Q53997857 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralMasculineDefiniteForm .
    ?genitivePluralMasculineDefiniteForm ontolex:representation ?genitivePluralMasculineDefinite ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q499327, wd:Q53997851 .
  }
}
