# tool: scribe-data
# All Arabic (Q13955) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?genitiveFeminineDual
  ?genitiveFeminineSingularConstruct
  ?genitiveFemininePluralConstruct
  ?genitiveFeminineDualConstruct

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineDualForm .
    ?genitiveFeminineDualForm ontolex:representation ?genitiveFeminineDual ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularConstructForm .
    ?genitiveFeminineSingularConstructForm ontolex:representation ?genitiveFeminineSingularConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePluralConstructForm .
    ?genitiveFemininePluralConstructForm ontolex:representation ?genitiveFemininePluralConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineDualConstructForm .
    ?genitiveFeminineDualConstructForm ontolex:representation ?genitiveFeminineDualConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110022, wd:Q1641446 .
  }
}
