# tool: scribe-data
# All Punjabi (Q58635) adverbs (Q380057) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adverb
  ?directMasculineSingular
  ?directMasculinePlural
  ?obliqueFeminineSingular
  ?obliqueFemininePlural
  ?obliqueMasculineSingular
  ?obliqueMasculinePlural

WHERE {
  ?lexeme dct:language wd:Q58635 ;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb ;
    schema:dateModified ?lastModified .

  # Note: We need to filter for pnb to remove shahmukhi (pnb) words.
  FILTER(lang(?adverb) = "pnb")

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directMasculineSingularForm .
    ?directMasculineSingularForm ontolex:representation ?directMasculineSingular ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directMasculinePluralForm .
    ?directMasculinePluralForm ontolex:representation ?directMasculinePlural ;
      wikibase:grammaticalFeature wd:Q1751855, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueFeminineSingularForm .
    ?obliqueFeminineSingularForm ontolex:representation ?obliqueFeminineSingular ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueFemininePluralForm .
    ?obliqueFemininePluralForm ontolex:representation ?obliqueFemininePlural ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueMasculineSingularForm .
    ?obliqueMasculineSingularForm ontolex:representation ?obliqueMasculineSingular ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueMasculinePluralForm .
    ?obliqueMasculinePluralForm ontolex:representation ?obliqueMasculinePlural ;
      wikibase:grammaticalFeature wd:Q1233197, wd:Q499327, wd:Q146786 .
  }
}
