# tool: scribe-data
# All Slovak (Q9058) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?accusativeSingular
  ?locativeSingular
  ?locativePlural
  ?accusativeInanimateSingular
  ?locativeInanimateSingular
  ?locativeAnimateSingular

WHERE {
  ?lexeme dct:language wd:Q9058 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeSingularForm .
    ?accusativeSingularForm ontolex:representation ?accusativeSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralForm .
    ?locativePluralForm ontolex:representation ?locativePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeInanimateSingularForm .
    ?accusativeInanimateSingularForm ontolex:representation ?accusativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeInanimateSingularForm .
    ?locativeInanimateSingularForm ontolex:representation ?locativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeAnimateSingularForm .
    ?locativeAnimateSingularForm ontolex:representation ?locativeAnimateSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q51927507, wd:Q110786 .
  }
}
