# tool: scribe-data
# All Tamil (Q5885) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?masculineSimplePast
  ?masculineFuture
  ?masculineSimplePastThirdPerson
  ?masculineFutureThirdPerson
  ?masculineFutureSingular
  ?masculineSimplePastThirdPersonSingular

WHERE {
  ?lexeme dct:language wd:Q5885 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSimplePastForm .
    ?masculineSimplePastForm ontolex:representation ?masculineSimplePast ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1392475 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureForm .
    ?masculineFutureForm ontolex:representation ?masculineFuture ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSimplePastThirdPersonForm .
    ?masculineSimplePastThirdPersonForm ontolex:representation ?masculineSimplePastThirdPerson ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1392475, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureThirdPersonForm .
    ?masculineFutureThirdPersonForm ontolex:representation ?masculineFutureThirdPerson ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q51929074 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineFutureSingularForm .
    ?masculineFutureSingularForm ontolex:representation ?masculineFutureSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q501405, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineSimplePastThirdPersonSingularForm .
    ?masculineSimplePastThirdPersonSingularForm ontolex:representation ?masculineSimplePastThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q1392475, wd:Q51929074, wd:Q110786 .
  }
}
