# tool: scribe-data
# All Danish (Q9035) verbs and the currently implemented tenses for each.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?infinitive
  ?infActive
  ?presActive
  ?pretActive
  ?pastPart
  ?presPart
  ?imperative
  ?presPassive
  ?pretPassive
  ?infPassive

WHERE {
  # MARK: Infinitive

  ?lexeme dct:language wd:Q9035 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?infinitive

  # MARK: Infinitive Active

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infActiveForm .
    ?infActiveForm ontolex:representation ?infActive ;
      wikibase:grammaticalFeature wd:Q179230 ;
      wikibase:grammaticalFeature wd:Q1317831 .
  }

  # MARK: Present Active

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presActiveForm .
    ?presActiveForm ontolex:representation ?presActive ;
      wikibase:grammaticalFeature wd:Q192613 ;
      wikibase:grammaticalFeature wd:Q1317831 .
  }

  # MARK: Preterite Active

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pretActiveForm .
    ?pretActiveForm ontolex:representation ?pretActive ;
      wikibase:grammaticalFeature wd:Q442485 ;
      wikibase:grammaticalFeature wd:Q1317831 .
  }

  # MARK: Past Participle

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pastPartForm .
    ?pastPartForm ontolex:representation ?pastPart ;
      wikibase:grammaticalFeature wd:Q12717679 .
  }

  # MARK: Present Participle

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presPartForm .
    ?presPartForm ontolex:representation ?presPart ;
      wikibase:grammaticalFeature wd:Q10345583 .
  }

  # MARK: Imperative

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?imperativeForm .
    ?imperativeForm ontolex:representation ?imperative ;
      wikibase:grammaticalFeature wd:Q22716 .
  }

  # MARK: Present Passive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?presPassiveForm .
    ?presPassiveForm ontolex:representation ?presPassive ;
      wikibase:grammaticalFeature wd:Q442485 ;
      wikibase:grammaticalFeature wd:Q1194697 .
  }

  # MARK: Preterite Passive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pretPassiveForm .
    ?pretPassiveForm ontolex:representation ?pretPassive ;
      wikibase:grammaticalFeature wd:Q442485 ;
      wikibase:grammaticalFeature wd:Q1194697 .
  }

  # MARK: Infinitive Passive

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?infPassiveForm .
    ?infPassiveForm ontolex:representation ?infPassive ;
      wikibase:grammaticalFeature wd:Q179230 ;
      wikibase:grammaticalFeature wd:Q1194697 .
  }
}
