# tool: scribe-data
# All Estonian (Q9072) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?genitiveSingular
  ?genitivePlural
  ?partitiveSingular
  ?partitivePlural
  ?elativeSingular
  ?elativePlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitivePluralForm .
    ?partitivePluralForm ontolex:representation ?partitivePlural ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSingularForm .
    ?elativeSingularForm ontolex:representation ?elativeSingular ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativePluralForm .
    ?elativePluralForm ontolex:representation ?elativePlural ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q146786 .
  }
}
