# tool: scribe-data
# All Estonian (Q9072) pronouns (Q36224) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?pronoun
  ?singularNominative
  ?singularAblative
  ?singularPartitive
  ?singularElative
  ?singularAllative
  ?singularAdessive

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q36224 ;
    wikibase:lemma ?pronoun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeForm .
    ?singularAblativeForm ontolex:representation ?singularAblative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPartitiveForm .
    ?singularPartitiveForm ontolex:representation ?singularPartitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularElativeForm .
    ?singularElativeForm ontolex:representation ?singularElative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAllativeForm .
    ?singularAllativeForm ontolex:representation ?singularAllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q655020 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAdessiveForm .
    ?singularAdessiveForm ontolex:representation ?singularAdessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q281954 .
  }
}
