# tool: scribe-data
# All English (Q1860) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?simplePresent
  ?simplePresentSecondPerson
  ?simplePresentPlural
  ?simplePresentFirstPersonSingular
  ?simplePresentSecondPersonSingular
  ?simplePresentThirdPersonSingular

WHERE {
  ?lexeme dct:language wd:Q1860 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentForm .
    ?simplePresentForm ontolex:representation ?simplePresent ;
      wikibase:grammaticalFeature wd:Q3910936 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentSecondPersonForm .
    ?simplePresentSecondPersonForm ontolex:representation ?simplePresentSecondPerson ;
      wikibase:grammaticalFeature wd:Q3910936, wd:Q51929049 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentPluralForm .
    ?simplePresentPluralForm ontolex:representation ?simplePresentPlural ;
      wikibase:grammaticalFeature wd:Q3910936, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentFirstPersonSingularForm .
    ?simplePresentFirstPersonSingularForm ontolex:representation ?simplePresentFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q3910936, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentSecondPersonSingularForm .
    ?simplePresentSecondPersonSingularForm ontolex:representation ?simplePresentSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q3910936, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?simplePresentThirdPersonSingularForm .
    ?simplePresentThirdPersonSingularForm ontolex:representation ?simplePresentThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q3910936, wd:Q51929074, wd:Q110786 .
  }
}
