# tool: scribe-data
# All Norwegian (Q25164) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?neuter
  ?indefiniteSingular
  ?feminineIndefinitePlural
  ?feminineDefiniteSingular
  ?feminineDefinitePlural
  ?masculineIndefiniteSingular
  ?masculineIndefinitePlural
  ?masculineDefiniteSingular
  ?masculineDefinitePlural
  ?neuterIndefinitePlural
  ?neuterDefiniteSingular
  ?neuterDefinitePlural

WHERE {
  ?lexeme dct:language wd:Q25164 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  # Note: We need to filter for nn to remove nynorsk (nn) words.
  FILTER(lang(?nouns) = "nn")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterForm .
    ?neuterForm ontolex:representation ?neuter ;
      wikibase:grammaticalFeature wd:Q1775461 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indefiniteSingularForm .
    ?indefiniteSingularForm ontolex:representation ?indefiniteSingular ;
      wikibase:grammaticalFeature wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineIndefinitePluralForm .
    ?feminineIndefinitePluralForm ontolex:representation ?feminineIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDefiniteSingularForm .
    ?feminineDefiniteSingularForm ontolex:representation ?feminineDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineDefinitePluralForm .
    ?feminineDefinitePluralForm ontolex:representation ?feminineDefinitePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndefiniteSingularForm .
    ?masculineIndefiniteSingularForm ontolex:representation ?masculineIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndefinitePluralForm .
    ?masculineIndefinitePluralForm ontolex:representation ?masculineIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDefiniteSingularForm .
    ?masculineDefiniteSingularForm ontolex:representation ?masculineDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineDefinitePluralForm .
    ?masculineDefinitePluralForm ontolex:representation ?masculineDefinitePlural ;
      wikibase:grammaticalFeature wd:Q499327, wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterIndefinitePluralForm .
    ?neuterIndefinitePluralForm ontolex:representation ?neuterIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterDefiniteSingularForm .
    ?neuterDefiniteSingularForm ontolex:representation ?neuterDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuterDefinitePluralForm .
    ?neuterDefinitePluralForm ontolex:representation ?neuterDefinitePlural ;
      wikibase:grammaticalFeature wd:Q1775461, wd:Q53997851, wd:Q146786 .
  }
}
