# tool: scribe-data
# All estonian (Q9072) prepositions (Q4833830) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?prepositions
    ?singularTerminative
  ?singularComitative
  ?singularElative
  ?pluralAblative
  ?pluralIllative
  ?pluralElative
  ?pluralTranslative
  ?pluralTerminative
  ?genitivePlural
  ?pluralComitative
  ?singularGenitive
  ?singularAllative
  ?singularEssive
  ?singularNominative
  ?nominativePlural
  ?singularPartitive
  ?pluralAllative
  ?singularAbessive
  ?pluralEssive
  ?singularInessive
  ?singularAdessive
  ?pluralPartitive
  ?pluralAbessive
  ?singularAblative
  ?singularIllative
  ?pluralInessive
  ?singularTranslative
  ?pluralAdessive

WHERE {
  ?lexeme dct:language wd:Q9072 ;
  wikibase:lexicalCategory wd:Q4833830 ;
  wikibase:lemma ?prepositions .
  FILTER(lang(?prepositions) = "et")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularTerminativeForm .
    ?singularTerminativeForm ontolex:representation ?singularTerminative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q747019 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularComitativeForm .
    ?singularComitativeForm ontolex:representation ?singularComitative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q838581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularElativeForm .
    ?singularElativeForm ontolex:representation ?singularElative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAblativeForm .
    ?pluralAblativeForm ontolex:representation ?pluralAblative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralIllativeForm .
    ?pluralIllativeForm ontolex:representation ?pluralIllative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralElativeForm .
    ?pluralElativeForm ontolex:representation ?pluralElative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralTranslativeForm .
    ?pluralTranslativeForm ontolex:representation ?pluralTranslative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q950170 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralTerminativeForm .
    ?pluralTerminativeForm ontolex:representation ?pluralTerminative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q747019 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralComitativeForm .
    ?pluralComitativeForm ontolex:representation ?pluralComitative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q838581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
    ?singularGenitiveForm ontolex:representation ?singularGenitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAllativeForm .
    ?singularAllativeForm ontolex:representation ?singularAllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q655020 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularEssiveForm .
    ?singularEssiveForm ontolex:representation ?singularEssive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q148465 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularNominativeForm .
    ?singularNominativeForm ontolex:representation ?singularNominative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativePluralForm .
    ?nominativePluralForm ontolex:representation ?nominativePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularPartitiveForm .
    ?singularPartitiveForm ontolex:representation ?singularPartitive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAllativeForm .
    ?pluralAllativeForm ontolex:representation ?pluralAllative ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q655020 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAbessiveForm .
    ?singularAbessiveForm ontolex:representation ?singularAbessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q319822 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralEssiveForm .
    ?pluralEssiveForm ontolex:representation ?pluralEssive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q148465 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularInessiveForm .
    ?singularInessiveForm ontolex:representation ?singularInessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAdessiveForm .
    ?singularAdessiveForm ontolex:representation ?singularAdessive ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q281954 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralPartitiveForm .
    ?pluralPartitiveForm ontolex:representation ?pluralPartitive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAbessiveForm .
    ?pluralAbessiveForm ontolex:representation ?pluralAbessive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q319822 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularAblativeForm .
    ?singularAblativeForm ontolex:representation ?singularAblative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularIllativeForm .
    ?singularIllativeForm ontolex:representation ?singularIllative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralInessiveForm .
    ?pluralInessiveForm ontolex:representation ?pluralInessive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q282031 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularTranslativeForm .
    ?singularTranslativeForm ontolex:representation ?singularTranslative ;
      wikibase:grammaticalFeature wd:Q110786, wd:Q950170 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralAdessiveForm .
    ?pluralAdessiveForm ontolex:representation ?pluralAdessive ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q281954 .
  }
}
