# tool: scribe-data
# All Hindustani (Q11051) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?feminine
  ?masculine
  ?singular
  ?accusativeFeminineSingular
  ?ablativeFeminineSingular

WHERE {
  ?lexeme dct:language wd:Q11051 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  # Note: We need to filter for hi to remove hindi (hi) words.
  FILTER(lang(?noun) = "hi")
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineForm .
    ?feminineForm ontolex:representation ?feminine ;
      wikibase:grammaticalFeature wd:Q1775415 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineForm .
    ?masculineForm ontolex:representation ?masculine ;
      wikibase:grammaticalFeature wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singularForm .
    ?singularForm ontolex:representation ?singular ;
      wikibase:grammaticalFeature wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeFeminineSingularForm .
    ?accusativeFeminineSingularForm ontolex:representation ?accusativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFeminineSingularForm .
    ?ablativeFeminineSingularForm ontolex:representation ?ablativeFeminineSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q110786 .
  }
}
