# tool: scribe-data
# All Japanese (Q5287) proper nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?properNoun

WHERE {
  ?lexeme dct:language wd:Q5287 ;
    wikibase:lexicalCategory wd:Q147276 ;
    wikibase:lemma ?properNoun .
    FILTER(lang(?properNoun) = "ja-hira")
}
