# tool: scribe-data
# Enter this query at https://query.wikidata.org/.
# Retrieve Urdu Adjectives and Grammatical Forms

SELECT DISTINCT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lemma
  ?directCase
  ?singulativeNumeral
  ?collectiveNumeral
  ?obliqueCase
WHERE {
  ?lexeme dct:language wd:Q11051 ;
          wikibase:lexicalCategory wd:Q34698 ;
          wikibase:lemma ?lemma .
  FILTER(lang(?lemma) = "ur")

  # Direct Case
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?directCaseForm .
    ?directCaseForm ontolex:representation ?directCase ;
    wikibase:grammaticalFeature wd:Q1751855 .
    FILTER(LANG(?directCase) = "ur")
  }

  # Singulative Numeral
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singulativeNumeralForm .
    ?singulativeNumeralForm ontolex:representation ?singulativeNumeral ;
    wikibase:grammaticalFeature wd:Q121786 .
    FILTER(LANG(?singulativeNumeral) = "ur")
  }

  # Collective Numeral
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?collectiveNumeralForm .
    ?collectiveNumeralForm ontolex:representation ?collectiveNumeral ;
    wikibase:grammaticalFeature wd:Q161341 .
    FILTER(LANG(?collectiveNumeral) = "ur")
  }

  # Oblique Case
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?obliqueCaseForm .
    ?obliqueCaseForm ontolex:representation ?obliqueCase ;
    wikibase:grammaticalFeature wd:Q551797 .
    FILTER(LANG(?obliqueCase) = "ur")
  }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en".
  }
}
