# tool: scribe-data
# All Polish (Q809) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?pluralVocativePositiveMasculinePersonal
  ?pluralVocativePositiveNotMasculinePersonal
  ?pluralInstrumentalPositiveMasculinePersonalNotMasculinePersonal
  ?pluralLocativePositiveMasculinePersonalNotMasculinePersonal

WHERE {
  ?lexeme dct:language wd:Q809 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralVocativePositiveMasculinePersonalForm .
    ?pluralVocativePositiveMasculinePersonalForm ontolex:representation ?pluralVocativePositiveMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q185077, wd:Q3482678, wd:Q27918551 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralVocativePositiveNotMasculinePersonalForm .
    ?pluralVocativePositiveNotMasculinePersonalForm ontolex:representation ?pluralVocativePositiveNotMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q185077, wd:Q3482678, wd:Q54152717 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralInstrumentalPositiveMasculinePersonalNotMasculinePersonalForm .
    ?pluralInstrumentalPositiveMasculinePersonalNotMasculinePersonalForm ontolex:representation ?pluralInstrumentalPositiveMasculinePersonalNotMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q192997, wd:Q3482678, wd:Q27918551, wd:Q54152717 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralLocativePositiveMasculinePersonalNotMasculinePersonalForm .
    ?pluralLocativePositiveMasculinePersonalNotMasculinePersonalForm ontolex:representation ?pluralLocativePositiveMasculinePersonalNotMasculinePersonal ;
      wikibase:grammaticalFeature wd:Q146786, wd:Q202142, wd:Q3482678, wd:Q27918551, wd:Q54152717 .
  }
}
