# tool: scribe-data
# All Spanish (Q1321) adjectives (Q34698) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?adjective
  ?feminineMasculineSingular
  ?feminineMasculinePlural
  ?feminineSecondPersonSingular
  ?feminineSecondPersonPlural
  ?feminineThirdPersonSingular
  ?feminineThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q1321 ;
    wikibase:lexicalCategory wd:Q34698 ;
    wikibase:lemma ?adjective ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculineSingularForm .
    ?feminineMasculineSingularForm ontolex:representation ?feminineMasculineSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineMasculinePluralForm .
    ?feminineMasculinePluralForm ontolex:representation ?feminineMasculinePlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSecondPersonSingularForm .
    ?feminineSecondPersonSingularForm ontolex:representation ?feminineSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineSecondPersonPluralForm .
    ?feminineSecondPersonPluralForm ontolex:representation ?feminineSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineThirdPersonSingularForm .
    ?feminineThirdPersonSingularForm ontolex:representation ?feminineThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminineThirdPersonPluralForm .
    ?feminineThirdPersonPluralForm ontolex:representation ?feminineThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1775415, wd:Q51929074, wd:Q146786 .
  }
}
