# tool: scribe-data
# All Estonian (Q9072) proper_nouns (Q147276) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?propernoun
  ?partitiveSingular
  ?partitivePlural
  ?illativeSingular
  ?illativePlural
  ?terminativeSingular
  ?terminativePlural

WHERE {
  ?lexeme dct:language wd:Q9072 ;
      wikibase:lexicalCategory wd:Q147276 ;
      wikibase:lemma ?propernoun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveSingularForm .
    ?partitiveSingularForm ontolex:representation ?partitiveSingular ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitivePluralForm .
    ?partitivePluralForm ontolex:representation ?partitivePlural ;
      wikibase:grammaticalFeature wd:Q857325, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativeSingularForm .
    ?illativeSingularForm ontolex:representation ?illativeSingular ;
      wikibase:grammaticalFeature wd:Q474668, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativePluralForm .
    ?illativePluralForm ontolex:representation ?illativePlural ;
      wikibase:grammaticalFeature wd:Q474668, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?terminativeSingularForm .
    ?terminativeSingularForm ontolex:representation ?terminativeSingular ;
      wikibase:grammaticalFeature wd:Q747019, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?terminativePluralForm .
    ?terminativePluralForm ontolex:representation ?terminativePlural ;
      wikibase:grammaticalFeature wd:Q747019, wd:Q146786 .
  }
}
