# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?locativeMasculineSingular
  ?locativeMasculinePlural
  ?locativeCommonSingular
  ?locativeCommonPlural
  ?locativeNeuterSingular
  ?locativeNeuterPlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculineSingularForm .
    ?locativeMasculineSingularForm ontolex:representation ?locativeMasculineSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeMasculinePluralForm .
    ?locativeMasculinePluralForm ontolex:representation ?locativeMasculinePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q499327, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeCommonSingularForm .
    ?locativeCommonSingularForm ontolex:representation ?locativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeCommonPluralForm .
    ?locativeCommonPluralForm ontolex:representation ?locativeCommonPlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1305037, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterSingularForm .
    ?locativeNeuterSingularForm ontolex:representation ?locativeNeuterSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeNeuterPluralForm .
    ?locativeNeuterPluralForm ontolex:representation ?locativeNeuterPlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q1775461, wd:Q146786 .
  }
}
