# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?genitiveFeminineSingular
  ?genitiveFemininePlural
  ?genitiveFemininePassiveFutureSingularParticiple
  ?genitiveFemininePassiveFuturePluralParticiple
  ?genitiveFemininePassivePerfectSingularParticiple
  ?genitiveFeminineActiveFutureSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularForm .
    ?genitiveFeminineSingularForm ontolex:representation ?genitiveFeminineSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePluralForm .
    ?genitiveFemininePluralForm ontolex:representation ?genitiveFemininePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePassiveFutureSingularParticipleForm .
    ?genitiveFemininePassiveFutureSingularParticipleForm ontolex:representation ?genitiveFemininePassiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q1194697, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePassiveFuturePluralParticipleForm .
    ?genitiveFemininePassiveFuturePluralParticipleForm ontolex:representation ?genitiveFemininePassiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q1194697, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFemininePassivePerfectSingularParticipleForm .
    ?genitiveFemininePassivePerfectSingularParticipleForm ontolex:representation ?genitiveFemininePassivePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q1194697, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineActiveFutureSingularParticipleForm .
    ?genitiveFeminineActiveFutureSingularParticipleForm ontolex:representation ?genitiveFeminineActiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q1317831, wd:Q501405, wd:Q110786, wd:Q814722 .
  }
}
