# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?accusativeCommonSingular
  ?accusativeCommonPlural
  ?accusativeCommonActivePresentSingularParticiple
  ?accusativeCommonActivePresentPluralParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeCommonSingularForm .
    ?accusativeCommonSingularForm ontolex:representation ?accusativeCommonSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1305037, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeCommonPluralForm .
    ?accusativeCommonPluralForm ontolex:representation ?accusativeCommonPlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1305037, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeCommonActivePresentSingularParticipleForm .
    ?accusativeCommonActivePresentSingularParticipleForm ontolex:representation ?accusativeCommonActivePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1305037, wd:Q1317831, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeCommonActivePresentPluralParticipleForm .
    ?accusativeCommonActivePresentPluralParticipleForm ontolex:representation ?accusativeCommonActivePresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1305037, wd:Q1317831, wd:Q192613, wd:Q146786, wd:Q814722 .
  }
}
