# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?genitiveNeuterSingular
  ?genitiveNeuterPassiveFuturePluralParticiple
  ?genitiveNeuterPassivePerfectSingularParticiple
  ?genitiveNeuterPassivePerfectPluralParticiple
  ?genitiveNeuterActiveFutureSingularParticiple
  ?genitiveNeuterActiveFuturePluralParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterSingularForm .
    ?genitiveNeuterSingularForm ontolex:representation ?genitiveNeuterSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPassiveFuturePluralParticipleForm .
    ?genitiveNeuterPassiveFuturePluralParticipleForm ontolex:representation ?genitiveNeuterPassiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1194697, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPassivePerfectSingularParticipleForm .
    ?genitiveNeuterPassivePerfectSingularParticipleForm ontolex:representation ?genitiveNeuterPassivePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1194697, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPassivePerfectPluralParticipleForm .
    ?genitiveNeuterPassivePerfectPluralParticipleForm ontolex:representation ?genitiveNeuterPassivePerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1194697, wd:Q625420, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterActiveFutureSingularParticipleForm .
    ?genitiveNeuterActiveFutureSingularParticipleForm ontolex:representation ?genitiveNeuterActiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1317831, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterActiveFuturePluralParticipleForm .
    ?genitiveNeuterActiveFuturePluralParticipleForm ontolex:representation ?genitiveNeuterActiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1317831, wd:Q501405, wd:Q146786, wd:Q814722 .
  }
}
