# tool: scribe-data
# All Latin (Q397) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?genitiveNeuterPlural
  ?genitiveActivePresentSingularParticiple
  ?genitiveActivePresentPluralParticiple
  ?genitiveNeuterPassiveFutureSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPluralForm .
    ?genitiveNeuterPluralForm ontolex:representation ?genitiveNeuterPlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveActivePresentSingularParticipleForm .
    ?genitiveActivePresentSingularParticipleForm ontolex:representation ?genitiveActivePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1317831, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveActivePresentPluralParticipleForm .
    ?genitiveActivePresentPluralParticipleForm ontolex:representation ?genitiveActivePresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1317831, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveNeuterPassiveFutureSingularParticipleForm .
    ?genitiveNeuterPassiveFutureSingularParticipleForm ontolex:representation ?genitiveNeuterPassiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775461, wd:Q1194697, wd:Q501405, wd:Q110786, wd:Q814722 .
  }
}
