# tool: scribe-data
# All Basque (Q8752) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?partitive
  ?plural
  ?genitiveSingular
  ?genitivePlural
  ?dativeSingular
  ?dativePlural
  ?instrumentalSingular
  ?instrumentalPlural
  ?locativeSingular
  ?locativePlural
  ?inessiveSingular
  ?inessivePlural
  ?allativeSingular
  ?allativePlural
  ?locativeInanimateSingular
  ?locativeInanimatePlural
  ?ablativeInanimateSingular
  ?ablativeInanimatePlural
  ?ablativeAnimateSingular
  ?ablativeAnimatePlural
  ?inessiveInanimateSingular
  ?inessiveInanimatePlural
  ?inessiveAnimateSingular
  ?inessiveAnimatePlural
  ?allativeInanimateSingular
  ?allativeInanimatePlural
  ?allativeAnimateSingular
  ?allativeAnimatePlural

WHERE {
  ?lexeme dct:language wd:Q8752 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?partitiveForm .
    ?partitiveForm ontolex:representation ?partitive ;
      wikibase:grammaticalFeature wd:Q857325 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pluralForm .
    ?pluralForm ontolex:representation ?plural ;
      wikibase:grammaticalFeature wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveSingularForm .
    ?genitiveSingularForm ontolex:representation ?genitiveSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralForm .
    ?genitivePluralForm ontolex:representation ?genitivePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeSingularForm .
    ?dativeSingularForm ontolex:representation ?dativeSingular ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePluralForm .
    ?dativePluralForm ontolex:representation ?dativePlural ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalSingularForm .
    ?instrumentalSingularForm ontolex:representation ?instrumentalSingular ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?instrumentalPluralForm .
    ?instrumentalPluralForm ontolex:representation ?instrumentalPlural ;
      wikibase:grammaticalFeature wd:Q192997, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeSingularForm .
    ?locativeSingularForm ontolex:representation ?locativeSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativePluralForm .
    ?locativePluralForm ontolex:representation ?locativePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveSingularForm .
    ?inessiveSingularForm ontolex:representation ?inessiveSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessivePluralForm .
    ?inessivePluralForm ontolex:representation ?inessivePlural ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeSingularForm .
    ?allativeSingularForm ontolex:representation ?allativeSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativePluralForm .
    ?allativePluralForm ontolex:representation ?allativePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeInanimateSingularForm .
    ?locativeInanimateSingularForm ontolex:representation ?locativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?locativeInanimatePluralForm .
    ?locativeInanimatePluralForm ontolex:representation ?locativeInanimatePlural ;
      wikibase:grammaticalFeature wd:Q202142, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeInanimateSingularForm .
    ?ablativeInanimateSingularForm ontolex:representation ?ablativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeInanimatePluralForm .
    ?ablativeInanimatePluralForm ontolex:representation ?ablativeInanimatePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeAnimateSingularForm .
    ?ablativeAnimateSingularForm ontolex:representation ?ablativeAnimateSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927507, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeAnimatePluralForm .
    ?ablativeAnimatePluralForm ontolex:representation ?ablativeAnimatePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927507, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveInanimateSingularForm .
    ?inessiveInanimateSingularForm ontolex:representation ?inessiveInanimateSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveInanimatePluralForm .
    ?inessiveInanimatePluralForm ontolex:representation ?inessiveInanimatePlural ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveAnimateSingularForm .
    ?inessiveAnimateSingularForm ontolex:representation ?inessiveAnimateSingular ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q51927507, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?inessiveAnimatePluralForm .
    ?inessiveAnimatePluralForm ontolex:representation ?inessiveAnimatePlural ;
      wikibase:grammaticalFeature wd:Q282031, wd:Q51927507, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeInanimateSingularForm .
    ?allativeInanimateSingularForm ontolex:representation ?allativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeInanimatePluralForm .
    ?allativeInanimatePluralForm ontolex:representation ?allativeInanimatePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeAnimateSingularForm .
    ?allativeAnimateSingularForm ontolex:representation ?allativeAnimateSingular ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927507, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?allativeAnimatePluralForm .
    ?allativeAnimatePluralForm ontolex:representation ?allativeAnimatePlural ;
      wikibase:grammaticalFeature wd:Q655020, wd:Q51927507, wd:Q146786 .
  }
}
