# tool: scribe-data
# All Basque (Q8752) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?ablativeInanimateSingular
  ?ablativeInanimatePlural
  ?ablativeAnimateSingular
  ?ablativeAnimatePlural

WHERE {
  ?lexeme dct:language wd:Q8752 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeInanimateSingularForm .
    ?ablativeInanimateSingularForm ontolex:representation ?ablativeInanimateSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927539, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeInanimatePluralForm .
    ?ablativeInanimatePluralForm ontolex:representation ?ablativeInanimatePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927539, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeAnimateSingularForm .
    ?ablativeAnimateSingularForm ontolex:representation ?ablativeAnimateSingular ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927507, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeAnimatePluralForm .
    ?ablativeAnimatePluralForm ontolex:representation ?ablativeAnimatePlural ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q51927507, wd:Q146786 .
  }
}
