# tool: scribe-data
# All Estonian (Q9072) personal_pronouns (Q468801) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?personalpronoun
  ?illative
  ?elative
  ?comitative
  ?illativeSingular
  ?elativeSingular
  ?comitativeSingular

WHERE {
  ?lexeme dct:language wd:Q9072 ;
    wikibase:lexicalCategory wd:Q468801 ;
    wikibase:lemma ?personalpronoun ;
    schema:dateModified ?lastModified .

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativeForm .
    ?illativeForm ontolex:representation ?illative ;
      wikibase:grammaticalFeature wd:Q474668 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeForm .
    ?elativeForm ontolex:representation ?elative ;
      wikibase:grammaticalFeature wd:Q394253 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeForm .
    ?comitativeForm ontolex:representation ?comitative ;
      wikibase:grammaticalFeature wd:Q838581 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?illativeSingularForm .
    ?illativeSingularForm ontolex:representation ?illativeSingular ;
      wikibase:grammaticalFeature wd:Q474668, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?elativeSingularForm .
    ?elativeSingularForm ontolex:representation ?elativeSingular ;
      wikibase:grammaticalFeature wd:Q394253, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?comitativeSingularForm .
    ?comitativeSingularForm ontolex:representation ?comitativeSingular ;
      wikibase:grammaticalFeature wd:Q838581, wd:Q110786 .
  }
}
