# tool: scribe-data
# All estonian (Q9072) personal_pronouns (Q468801) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?personal_pronouns
    ?singularElative
  ?singularIllative
  ?singularGenitive
  ?abessive
  ?singularAdessive
  ?partitive
  ?ablative
  ?comitative
  ?nominative
  ?terminative
  ?inessive
  ?singularAbessive
  ?essive
  ?allative
  ?singularPartitive
  ?singularAblative
  ?singularComitative
  ?singularNominative
  ?singularTerminative
  ?translative
  ?elative
  ?singularInessive
  ?genitive
  ?illative
  ?singularEssive
  ?adessive
  ?singularAllative
  ?singularTranslative
    WHERE {
    ?lexeme dct:language wd:Q9072 ;
        wikibase:lexicalCategory wd:Q468801 ;
        wikibase:lemma ?personal_pronouns .
        FILTER(lang(?personal_pronouns) = "et")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularElativeForm .
            ?singularElativeForm ontolex:representation ?singularElative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q394253 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularIllativeForm .
            ?singularIllativeForm ontolex:representation ?singularIllative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q474668 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularGenitiveForm .
            ?singularGenitiveForm ontolex:representation ?singularGenitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?abessiveForm .
            ?abessiveForm ontolex:representation ?abessive ;
                wikibase:grammaticalFeature wd:Q319822 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAdessiveForm .
            ?singularAdessiveForm ontolex:representation ?singularAdessive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q281954 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?partitiveForm .
            ?partitiveForm ontolex:representation ?partitive ;
                wikibase:grammaticalFeature wd:Q857325 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?ablativeForm .
            ?ablativeForm ontolex:representation ?ablative ;
                wikibase:grammaticalFeature wd:Q156986 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?comitativeForm .
            ?comitativeForm ontolex:representation ?comitative ;
                wikibase:grammaticalFeature wd:Q838581 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?terminativeForm .
            ?terminativeForm ontolex:representation ?terminative ;
                wikibase:grammaticalFeature wd:Q747019 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?inessiveForm .
            ?inessiveForm ontolex:representation ?inessive ;
                wikibase:grammaticalFeature wd:Q282031 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAbessiveForm .
            ?singularAbessiveForm ontolex:representation ?singularAbessive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q319822 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?essiveForm .
            ?essiveForm ontolex:representation ?essive ;
                wikibase:grammaticalFeature wd:Q148465 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?allativeForm .
            ?allativeForm ontolex:representation ?allative ;
                wikibase:grammaticalFeature wd:Q655020 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularPartitiveForm .
            ?singularPartitiveForm ontolex:representation ?singularPartitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q857325 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAblativeForm .
            ?singularAblativeForm ontolex:representation ?singularAblative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q156986 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularComitativeForm .
            ?singularComitativeForm ontolex:representation ?singularComitative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q838581 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNominativeForm .
            ?singularNominativeForm ontolex:representation ?singularNominative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularTerminativeForm .
            ?singularTerminativeForm ontolex:representation ?singularTerminative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q747019 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?translativeForm .
            ?translativeForm ontolex:representation ?translative ;
                wikibase:grammaticalFeature wd:Q950170 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?elativeForm .
            ?elativeForm ontolex:representation ?elative ;
                wikibase:grammaticalFeature wd:Q394253 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularInessiveForm .
            ?singularInessiveForm ontolex:representation ?singularInessive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q282031 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?illativeForm .
            ?illativeForm ontolex:representation ?illative ;
                wikibase:grammaticalFeature wd:Q474668 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularEssiveForm .
            ?singularEssiveForm ontolex:representation ?singularEssive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q148465 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?adessiveForm .
            ?adessiveForm ontolex:representation ?adessive ;
                wikibase:grammaticalFeature wd:Q281954 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularAllativeForm .
            ?singularAllativeForm ontolex:representation ?singularAllative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q655020 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularTranslativeForm .
            ?singularTranslativeForm ontolex:representation ?singularTranslative ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q950170 .
        }
}