# tool: scribe-data
# All Russian (Q7737) prepositions (Q4833830) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?preposition
  ?grammaticalCase

WHERE {
  ?lexeme dct:language wd:Q7737 ;
    wikibase:lexicalCategory wd:Q4833830 ;
    wikibase:lemma ?lemma .

  # MARK: Case

  OPTIONAL {
    ?lexeme wdt:P5713 ?caseForm .
  }

  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?lemma rdfs:label ?preposition .
    ?caseForm rdfs:label ?grammaticalCase .
  }
}
