# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?nominativeMasculine
  ?nominativeDual
  ?pausalPlural
  ?genitivePluralConstruct
  ?nominativeFeminineDualConstruct
  ?genitiveAccusativeMasculineDual

WHERE {
  ?lexeme dct:language wd:Q13955 ;
      wikibase:lexicalCategory wd:Q1084 ;
      wikibase:lemma ?noun ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeMasculineForm .
    ?nominativeMasculineForm ontolex:representation ?nominativeMasculine ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q499327 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDualForm .
    ?nominativeDualForm ontolex:representation ?nominativeDual ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?pausalPluralForm .
    ?pausalPluralForm ontolex:representation ?pausalPlural ;
      wikibase:grammaticalFeature wd:Q117262361, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitivePluralConstructForm .
    ?genitivePluralConstructForm ontolex:representation ?genitivePluralConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeFeminineDualConstructForm .
    ?nominativeFeminineDualConstructForm ontolex:representation ?nominativeFeminineDualConstruct ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775415, wd:Q110022, wd:Q1641446 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveAccusativeMasculineDualForm .
    ?genitiveAccusativeMasculineDualForm ontolex:representation ?genitiveAccusativeMasculineDual ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146078, wd:Q499327, wd:Q110022 .
  }
}
