# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?genitiveIndefiniteSingular
  ?genitiveIndefinitePlural
  ?genitiveIndefiniteDual
  ?genitiveFeminineIndefinitePlural
  ?genitiveFeminineDefiniteSingular
  ?genitiveFeminineSingularConstruct

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveIndefiniteSingularForm .
    ?genitiveIndefiniteSingularForm ontolex:representation ?genitiveIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveIndefinitePluralForm .
    ?genitiveIndefinitePluralForm ontolex:representation ?genitiveIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveIndefiniteDualForm .
    ?genitiveIndefiniteDualForm ontolex:representation ?genitiveIndefiniteDual ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q53997857, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineIndefinitePluralForm .
    ?genitiveFeminineIndefinitePluralForm ontolex:representation ?genitiveFeminineIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineDefiniteSingularForm .
    ?genitiveFeminineDefiniteSingularForm ontolex:representation ?genitiveFeminineDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?genitiveFeminineSingularConstructForm .
    ?genitiveFeminineSingularConstructForm ontolex:representation ?genitiveFeminineSingularConstruct ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q1775415, wd:Q110786, wd:Q1641446 .
  }
}
