# tool: scribe-data
# All Arabic (Q13955) nouns (Q1084) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?noun
  ?nominativeDefiniteSingular
  ?nominativeDefinitePlural
  ?nominativeDefiniteDual
  ?accusativeIndefiniteSingular
  ?accusativeIndefinitePlural
  ?accusativeIndefiniteDual

WHERE {
  ?lexeme dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q1084 ;
    wikibase:lemma ?noun ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDefiniteSingularForm .
    ?nominativeDefiniteSingularForm ontolex:representation ?nominativeDefiniteSingular ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q53997851, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDefinitePluralForm .
    ?nominativeDefinitePluralForm ontolex:representation ?nominativeDefinitePlural ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q53997851, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeDefiniteDualForm .
    ?nominativeDefiniteDualForm ontolex:representation ?nominativeDefiniteDual ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q53997851, wd:Q110022 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefiniteSingularForm .
    ?accusativeIndefiniteSingularForm ontolex:representation ?accusativeIndefiniteSingular ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefinitePluralForm .
    ?accusativeIndefinitePluralForm ontolex:representation ?accusativeIndefinitePlural ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeIndefiniteDualForm .
    ?accusativeIndefiniteDualForm ontolex:representation ?accusativeIndefiniteDual ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q53997857, wd:Q110022 .
  }
}
