# tool: scribe-data
# All danish (Q9035) pronouns (Q36224) and their forms.
# Enter this query at https://query.wikidata.org/.

SELECT
    (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
    ?pronouns
    ?oblique
  ?nonGenitive
  ?singularNeuter
  ?singularCommonNonGenitive
  ?singularNeuterNonGenitive
  ?genitivePlural
  ?nominative
  ?genitiveFeminine
  ?genitiveMasculine
  ?plural
  ?common
  ?singularCommonGenitive
  ?neuter
  ?genitive
  ?singularCommon
  ?pluralNonGenitive
  ?singularGenitiveNeuter
    WHERE {
    ?lexeme dct:language wd:Q9035 ;
        wikibase:lexicalCategory wd:Q36224 ;
        wikibase:lemma ?pronouns .
        FILTER(lang(?pronouns) = "da")
    
        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?obliqueForm .
            ?obliqueForm ontolex:representation ?oblique ;
                wikibase:grammaticalFeature wd:Q1233197 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nonGenitiveForm .
            ?nonGenitiveForm ontolex:representation ?nonGenitive ;
                wikibase:grammaticalFeature wd:Q98946930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNeuterForm .
            ?singularNeuterForm ontolex:representation ?singularNeuter ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1775461 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularCommonNonGenitiveForm .
            ?singularCommonNonGenitiveForm ontolex:representation ?singularCommonNonGenitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1305037, wd:Q98946930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularNeuterNonGenitiveForm .
            ?singularNeuterNonGenitiveForm ontolex:representation ?singularNeuterNonGenitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1775461, wd:Q98946930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitivePluralForm .
            ?genitivePluralForm ontolex:representation ?genitivePlural ;
                wikibase:grammaticalFeature wd:Q146233, wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?nominativeForm .
            ?nominativeForm ontolex:representation ?nominative ;
                wikibase:grammaticalFeature wd:Q131105 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveFeminineForm .
            ?genitiveFeminineForm ontolex:representation ?genitiveFeminine ;
                wikibase:grammaticalFeature wd:Q146233, wd:Q1775415 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveMasculineForm .
            ?genitiveMasculineForm ontolex:representation ?genitiveMasculine ;
                wikibase:grammaticalFeature wd:Q146233, wd:Q499327 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralForm .
            ?pluralForm ontolex:representation ?plural ;
                wikibase:grammaticalFeature wd:Q146786 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?commonForm .
            ?commonForm ontolex:representation ?common ;
                wikibase:grammaticalFeature wd:Q1305037 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularCommonGenitiveForm .
            ?singularCommonGenitiveForm ontolex:representation ?singularCommonGenitive ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1305037, wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?neuterForm .
            ?neuterForm ontolex:representation ?neuter ;
                wikibase:grammaticalFeature wd:Q1775461 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?genitiveForm .
            ?genitiveForm ontolex:representation ?genitive ;
                wikibase:grammaticalFeature wd:Q146233 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularCommonForm .
            ?singularCommonForm ontolex:representation ?singularCommon ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q1305037 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?pluralNonGenitiveForm .
            ?pluralNonGenitiveForm ontolex:representation ?pluralNonGenitive ;
                wikibase:grammaticalFeature wd:Q146786, wd:Q98946930 .
        }

        OPTIONAL {
            ?lexeme ontolex:lexicalForm ?singularGenitiveNeuterForm .
            ?singularGenitiveNeuterForm ontolex:representation ?singularGenitiveNeuter ;
                wikibase:grammaticalFeature wd:Q110786, wd:Q146233, wd:Q1775461 .
        }
}