# tool: scribe-data
# All Korean (Q9176) adverbs (Q380057) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?adverb

WHERE {
  ?lexeme dct:language wd:Q9176 ;
    wikibase:lexicalCategory wd:Q380057 ;
    wikibase:lemma ?adverb .
}
