# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?indicativeActiveFutureFirstPersonSingular
  ?indicativeActivePerfectFirstPersonSingular
  ?indicativeActivePerfectThirdPersonSingular
  ?indicativeActivePastImperfectFirstPersonSingular
  ?indicativeActivePluperfectThirdPersonSingular
  ?indicativeActiveFuturePerfectThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActiveFutureFirstPersonSingularForm .
    ?indicativeActiveFutureFirstPersonSingularForm ontolex:representation ?indicativeActiveFutureFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q501405, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePerfectFirstPersonSingularForm .
    ?indicativeActivePerfectFirstPersonSingularForm ontolex:representation ?indicativeActivePerfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q625420, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePerfectThirdPersonSingularForm .
    ?indicativeActivePerfectThirdPersonSingularForm ontolex:representation ?indicativeActivePerfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q625420, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePastImperfectFirstPersonSingularForm .
    ?indicativeActivePastImperfectFirstPersonSingularForm ontolex:representation ?indicativeActivePastImperfectFirstPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q12547192, wd:Q21714344, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePluperfectThirdPersonSingularForm .
    ?indicativeActivePluperfectThirdPersonSingularForm ontolex:representation ?indicativeActivePluperfectThirdPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q623742, wd:Q51929074, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActiveFuturePerfectThirdPersonPluralForm .
    ?indicativeActiveFuturePerfectThirdPersonPluralForm ontolex:representation ?indicativeActiveFuturePerfectThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q501405, wd:Q625420, wd:Q51929074, wd:Q146786 .
  }
}
