# tool: scribe-data
# All Latin (Q397) verbs and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?SecondSingularIndicativePassive
  ?SecondSingularImpPassive
  ?ZeroInfinitivePassive
  ?ZeroInfinitiveActive
  ?GenitiveSingularActiveParticiple
  ?GenitivePluralActiveParticiple


WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  # Common value for Future Tense
  VALUES ?presenttense { wd:Q192613 }


  # second person, singular, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondSingularIndicativePassiveForm .
    ?SecondSingularIndicativePassiveForm ontolex:representation ?SecondSingularIndicativePassive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # second person, singular, present tense, imperative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondSingularImpPassiveForm .
    ?SecondSingularImpPassiveForm ontolex:representation ?SecondSingularImpPassive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, ?presenttense, wd:Q22716, wd:Q1194697 .
  }

  # zero person, present tense, infinitive, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ZeroInfinitivePassiveForm .
    ?ZeroInfinitivePassiveForm ontolex:representation ?ZeroInfinitivePassive ;
      wikibase:grammaticalFeature wd:Q88778575, ?presenttense, wd:Q179230, wd:Q1194697 .
  }

  # zero person, present tense, infinitive, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ZeroInfinitiveActiveForm .
    ?ZeroInfinitiveActiveForm ontolex:representation ?ZeroInfinitiveActive ;
      wikibase:grammaticalFeature wd:Q88778575, ?presenttense, wd:Q179230, wd:Q1317831 .
  }

  # genitive case, singular, present tense, active, participle
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?GenitiveSingularActiveParticipleForm .
    ?GenitiveSingularActiveParticipleForm ontolex:representation ?GenitiveSingularActiveParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q110786, ?presenttense, wd:Q1317831, wd:Q814722 .
  }

  # genitive case, plural, present tense, active, participle
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?GenitivePluralActiveParticipleForm .
    ?GenitivePluralActiveParticipleForm ontolex:representation ?GenitivePluralActiveParticiple ;
      wikibase:grammaticalFeature wd:Q146233, wd:Q146786, ?presenttense, wd:Q1317831, wd:Q814722 .
  }
}
