# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?dativePresentSingularParticiple
  ?dativePresentPluralParticiple
  ?dativePassiveFuturePluralParticiple
  ?dativePassivePerfectPluralParticiple
  ?vocativeCommonPresentPluralParticiple
  ?vocativeCommonActivePresentPluralParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePresentSingularParticipleForm .
    ?dativePresentSingularParticipleForm ontolex:representation ?dativePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePresentPluralParticipleForm .
    ?dativePresentPluralParticipleForm ontolex:representation ?dativePresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePassiveFuturePluralParticipleForm .
    ?dativePassiveFuturePluralParticipleForm ontolex:representation ?dativePassiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1194697, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativePassivePerfectPluralParticipleForm .
    ?dativePassivePerfectPluralParticipleForm ontolex:representation ?dativePassivePerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1194697, wd:Q625420, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeCommonPresentPluralParticipleForm .
    ?vocativeCommonPresentPluralParticipleForm ontolex:representation ?vocativeCommonPresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1305037, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeCommonActivePresentPluralParticipleForm .
    ?vocativeCommonActivePresentPluralParticipleForm ontolex:representation ?vocativeCommonActivePresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1305037, wd:Q1317831, wd:Q192613, wd:Q146786, wd:Q814722 .
  }
}
