# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?accusativeNeuterSingularSupine
  ?accusativeNeuterPresentSingularParticiple
  ?accusativeNeuterPresentPluralParticiple
  ?accusativeNeuterFutureSingularParticiple
  ?accusativeNeuterFuturePluralParticiple
  ?accusativeNeuterActivePresentSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterSingularSupineForm .
    ?accusativeNeuterSingularSupineForm ontolex:representation ?accusativeNeuterSingularSupine ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q110786, wd:Q548470 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPresentSingularParticipleForm .
    ?accusativeNeuterPresentSingularParticipleForm ontolex:representation ?accusativeNeuterPresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPresentPluralParticipleForm .
    ?accusativeNeuterPresentPluralParticipleForm ontolex:representation ?accusativeNeuterPresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterFutureSingularParticipleForm .
    ?accusativeNeuterFutureSingularParticipleForm ontolex:representation ?accusativeNeuterFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterFuturePluralParticipleForm .
    ?accusativeNeuterFuturePluralParticipleForm ontolex:representation ?accusativeNeuterFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterActivePresentSingularParticipleForm .
    ?accusativeNeuterActivePresentSingularParticipleForm ontolex:representation ?accusativeNeuterActivePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q1317831, wd:Q192613, wd:Q110786, wd:Q814722 .
  }
}
