# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?nominativeNeuterPresentPluralParticiple
  ?nominativeNeuterFutureSingularParticiple
  ?nominativeNeuterPerfectPluralParticiple
  ?nominativeNeuterPassiveFutureSingularParticiple
  ?nominativeNeuterPassiveFuturePluralParticiple
  ?nominativeNeuterActiveFutureSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPresentPluralParticipleForm .
    ?nominativeNeuterPresentPluralParticipleForm ontolex:representation ?nominativeNeuterPresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterFutureSingularParticipleForm .
    ?nominativeNeuterFutureSingularParticipleForm ontolex:representation ?nominativeNeuterFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPerfectPluralParticipleForm .
    ?nominativeNeuterPerfectPluralParticipleForm ontolex:representation ?nominativeNeuterPerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q625420, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPassiveFutureSingularParticipleForm .
    ?nominativeNeuterPassiveFutureSingularParticipleForm ontolex:representation ?nominativeNeuterPassiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q1194697, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterPassiveFuturePluralParticipleForm .
    ?nominativeNeuterPassiveFuturePluralParticipleForm ontolex:representation ?nominativeNeuterPassiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q1194697, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?nominativeNeuterActiveFutureSingularParticipleForm .
    ?nominativeNeuterActiveFutureSingularParticipleForm ontolex:representation ?nominativeNeuterActiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q131105, wd:Q1775461, wd:Q1317831, wd:Q501405, wd:Q110786, wd:Q814722 .
  }
}
