# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?dativeFeminineFutureSingularParticiple
  ?dativeFemininePerfectSingularParticiple
  ?dativeFemininePassiveFutureSingularParticiple
  ?dativeFemininePassivePerfectSingularParticiple
  ?dativeFeminineActiveFutureSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineFutureSingularParticipleForm .
    ?dativeFeminineFutureSingularParticipleForm ontolex:representation ?dativeFeminineFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePerfectSingularParticipleForm .
    ?dativeFemininePerfectSingularParticipleForm ontolex:representation ?dativeFemininePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePassiveFutureSingularParticipleForm .
    ?dativeFemininePassiveFutureSingularParticipleForm ontolex:representation ?dativeFemininePassiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q1194697, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFemininePassivePerfectSingularParticipleForm .
    ?dativeFemininePassivePerfectSingularParticipleForm ontolex:representation ?dativeFemininePassivePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q1194697, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?dativeFeminineActiveFutureSingularParticipleForm .
    ?dativeFeminineActiveFutureSingularParticipleForm ontolex:representation ?dativeFeminineActiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q145599, wd:Q1775415, wd:Q1317831, wd:Q501405, wd:Q110786, wd:Q814722 .
  }
}
