# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?activeImperativeSecondPersonSingular
  ?activeImperativePresentSecondPersonSingular
  ?activeImperativePresentSecondPersonPlural
  ?activeImperativeFutureSecondPersonSingular
  ?activeImperativeFutureSecondPersonPlural
  ?activeImperativeFutureThirdPersonPlural

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativeSecondPersonSingularForm .
    ?activeImperativeSecondPersonSingularForm ontolex:representation ?activeImperativeSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativePresentSecondPersonSingularForm .
    ?activeImperativePresentSecondPersonSingularForm ontolex:representation ?activeImperativePresentSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q192613, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativePresentSecondPersonPluralForm .
    ?activeImperativePresentSecondPersonPluralForm ontolex:representation ?activeImperativePresentSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q192613, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativeFutureSecondPersonSingularForm .
    ?activeImperativeFutureSecondPersonSingularForm ontolex:representation ?activeImperativeFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q501405, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativeFutureSecondPersonPluralForm .
    ?activeImperativeFutureSecondPersonPluralForm ontolex:representation ?activeImperativeFutureSecondPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q501405, wd:Q51929049, wd:Q146786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativeFutureThirdPersonPluralForm .
    ?activeImperativeFutureThirdPersonPluralForm ontolex:representation ?activeImperativeFutureThirdPersonPlural ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q501405, wd:Q51929074, wd:Q146786 .
  }
}
