# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?accusativeNeuterPerfectSingularParticiple
  ?accusativeNeuterPerfectPluralParticiple
  ?ablativeActivePresentSingularParticiple
  ?ablativeActivePresentPluralParticiple
  ?ablativeActiveFuturePluralParticiple
  ?accusativeNeuterPassivePerfectPluralParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
      wikibase:lexicalCategory wd:Q24905 ;
      wikibase:lemma ?verb ;
      schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPerfectSingularParticipleForm .
    ?accusativeNeuterPerfectSingularParticipleForm ontolex:representation ?accusativeNeuterPerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPerfectPluralParticipleForm .
    ?accusativeNeuterPerfectPluralParticipleForm ontolex:representation ?accusativeNeuterPerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q625420, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeActivePresentSingularParticipleForm .
    ?ablativeActivePresentSingularParticipleForm ontolex:representation ?ablativeActivePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1317831, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeActivePresentPluralParticipleForm .
    ?ablativeActivePresentPluralParticipleForm ontolex:representation ?ablativeActivePresentPluralParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1317831, wd:Q192613, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeActiveFuturePluralParticipleForm .
    ?ablativeActiveFuturePluralParticipleForm ontolex:representation ?ablativeActiveFuturePluralParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1317831, wd:Q501405, wd:Q146786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?accusativeNeuterPassivePerfectPluralParticipleForm .
    ?accusativeNeuterPassivePerfectPluralParticipleForm ontolex:representation ?accusativeNeuterPassivePerfectPluralParticiple ;
      wikibase:grammaticalFeature wd:Q146078, wd:Q1775461, wd:Q1194697, wd:Q625420, wd:Q146786, wd:Q814722 .
  }
}
