# tool: scribe-data
# All Latin (Q397) verbs and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?verb
  ?ThirdPluralIndicativePassive
  ?ThirdPluralIndicativeActive
  ?FirstSingularIndicativePassive
  ?ThirdSingularIndicativePassive
  ?SecondSingularIndicativeActive
  ?ThirdSingularIndicativeActive
  ?FirstPluralIndicativePassive
  ?FirstPluralIndicativeActive
  ?SecondPluralIndicativePassive
  ?SecondPluralActivePassive
  ?SecondPluralImperativePassive


WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .

  # Common value for Future Tense
  VALUES ?presenttense { wd:Q192613 }

  # third person, plural, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ThirdPluralIndicativePassiveForm .
    ?ThirdPluralIndicativePassiveForm ontolex:representation ?ThirdPluralIndicativePassive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # third person, plural, present tense, indicative, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ThirdPluralIndicativeActiveForm .
    ?ThirdPluralIndicativeActiveForm ontolex:representation ?ThirdPluralIndicativeActive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q146786, ?presenttense, wd:Q682111, wd:Q1317831 .
  }

  # first person, singular, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?FirstSingularIndicativePassiveForm .
    ?FirstSingularIndicativePassiveForm ontolex:representation ?FirstSingularIndicativePassive ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q110786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # third person, singular, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ThirdSingularIndicativePassiveForm .
    ?ThirdSingularIndicativePassiveForm ontolex:representation ?ThirdSingularIndicativePassive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # second person, singular, present tense, indicative, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondSingularIndicativeActiveForm .
    ?SecondSingularIndicativeActiveForm ontolex:representation ?SecondSingularIndicativeActive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q110786, ?presenttense, wd:Q682111, wd:Q1317831 .
  }

  # third person, singular, present tense, indicative, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ThirdSingularIndicativeActiveForm .
    ?ThirdSingularIndicativeActiveForm ontolex:representation ?ThirdSingularIndicativeActive ;
      wikibase:grammaticalFeature wd:Q51929074, wd:Q110786, ?presenttense, wd:Q682111, wd:Q1317831 .
  }

  # first person, plural, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?FirstPluralIndicativePassiveForm .
    ?FirstPluralIndicativePassiveForm ontolex:representation ?FirstPluralIndicativePassive ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # first person, plural, present tense, indicative, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?FirstPluralIndicativeActiveForm .
    ?FirstPluralIndicativeActiveForm ontolex:representation ?FirstPluralIndicativeActive ;
      wikibase:grammaticalFeature wd:Q21714344, wd:Q146786, ?presenttense, wd:Q682111, wd:Q1317831 .
  }

  # second person, plural, present tense, indicative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondPluralIndicativePassiveForm .
    ?SecondPluralIndicativePassiveForm ontolex:representation ?SecondPluralIndicativePassive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, ?presenttense, wd:Q682111, wd:Q1194697 .
  }

  # second person, plural, present tense, imperative, active
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondPluralImperativeActiveForm .
    ?SecondPluralImperativeActiveForm ontolex:representation ?SecondPluralActivePassive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, ?presenttense, wd:Q22716, wd:Q1317831 .
  }

  # second person, plural, present tense, imperative, passive
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?SecondPluralImperativePassiveForm .
    ?SecondPluralImperativePassiveForm ontolex:representation ?SecondPluralImperativePassive ;
      wikibase:grammaticalFeature wd:Q51929049, wd:Q146786, ?presenttense, wd:Q22716, wd:Q1194697 .
  }
}
