# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?ablativeFeminineFutureSingularParticiple
  ?ablativeFemininePerfectSingularParticiple
  ?ablativeFemininePassiveFutureSingularParticiple
  ?ablativeFemininePassivePerfectSingularParticiple
  ?ablativeFeminineActiveFutureSingularParticiple

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFeminineFutureSingularParticipleForm .
    ?ablativeFeminineFutureSingularParticipleForm ontolex:representation ?ablativeFeminineFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFemininePerfectSingularParticipleForm .
    ?ablativeFemininePerfectSingularParticipleForm ontolex:representation ?ablativeFemininePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFemininePassiveFutureSingularParticipleForm .
    ?ablativeFemininePassiveFutureSingularParticipleForm ontolex:representation ?ablativeFemininePassiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q1194697, wd:Q501405, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFemininePassivePerfectSingularParticipleForm .
    ?ablativeFemininePassivePerfectSingularParticipleForm ontolex:representation ?ablativeFemininePassivePerfectSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q1194697, wd:Q625420, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?ablativeFeminineActiveFutureSingularParticipleForm .
    ?ablativeFeminineActiveFutureSingularParticipleForm ontolex:representation ?ablativeFeminineActiveFutureSingularParticiple ;
      wikibase:grammaticalFeature wd:Q156986, wd:Q1775415, wd:Q1317831, wd:Q501405, wd:Q110786, wd:Q814722 .
  }
}
