# tool: scribe-data
# All Latin (Q397) verbs (Q24905) and the given forms.
# Enter this query at https://query.wikidata.org/.

SELECT
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID)
  ?lastModified
  ?verb
  ?activePresentInfinitive
  ?vocativePresentSingularParticiple
  ?vocativeActivePresentSingularParticiple
  ?indicativeActivePluperfectSecondPersonSingular
  ?activeImperativeFutureSecondPersonSingular
  ?activePerfectSecondPersonPluralSubjunctive

WHERE {
  ?lexeme dct:language wd:Q397 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb ;
    schema:dateModified ?lastModified .
    
  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePresentInfinitiveForm .
    ?activePresentInfinitiveForm ontolex:representation ?activePresentInfinitive ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q52434245 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativePresentSingularParticipleForm .
    ?vocativePresentSingularParticipleForm ontolex:representation ?vocativePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?vocativeActivePresentSingularParticipleForm .
    ?vocativeActivePresentSingularParticipleForm ontolex:representation ?vocativeActivePresentSingularParticiple ;
      wikibase:grammaticalFeature wd:Q185077, wd:Q1317831, wd:Q192613, wd:Q110786, wd:Q814722 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?indicativeActivePluperfectSecondPersonSingularForm .
    ?indicativeActivePluperfectSecondPersonSingularForm ontolex:representation ?indicativeActivePluperfectSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1317831, wd:Q623742, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activeImperativeFutureSecondPersonSingularForm .
    ?activeImperativeFutureSecondPersonSingularForm ontolex:representation ?activeImperativeFutureSecondPersonSingular ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q22716, wd:Q501405, wd:Q51929049, wd:Q110786 .
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?activePerfectSecondPersonPluralSubjunctiveForm .
    ?activePerfectSecondPersonPluralSubjunctiveForm ontolex:representation ?activePerfectSecondPersonPluralSubjunctive ;
      wikibase:grammaticalFeature wd:Q1317831, wd:Q625420, wd:Q51929049, wd:Q146786, wd:Q473746 .
  }
}
